### ISSUE TITLE
Typing closing " (double quote) inserts escaped double quote pair (\"\") instead of closing " pair.

### ISSUE THREAD

**Issue by ftravers** [abo-abo/lispy#101]
Typing: "fenton" gives -> "fenton\"\""
When it should just close the double quote pair, not add a set of escaped double quotes.

**Comment by abo-abo** [comment]
> just close the double quote pair

Any pair should never be un-closed. It always starts closed. You type `"fenton"` by pressing <kbd>"</kbd> once to insert `""` and then `fenton`.

**Comment by ftravers** [comment]
![anim](https://cloud.githubusercontent.com/assets/443507/9460348/35218072-4b2f-11e5-924e-6eec08fcca55.gif)

**Comment by abo-abo** [comment]
Your screencast looks correct to me. I can only guess that you want to insert `"Fenton \""` instead of `"Fenton\"\""`.  You could press <kbd>C-d</kbd> for that.  Or use `lispy-doublequote` instead of `lispy-quotes`.

**Comment by rprimus** [comment]
Tue Sep  1 11:58:35 BST 2015

Greetings.   I agree with the OP.  Coming from paredit,  it is the expected  behaviour.

From paredit:

```
;;;   ( inserts `()', leaving the point in the middle;
;;;   ) moves the point over the next closing delimiter;
;;;   " inserts `""' if outside a string, or inserts an escaped
;;;      double-quote if in the middle of a string, or moves over the
;;;      closing double-quote if at the end of a string; 
```

The 'skip-over" should *only* happen when **point** on the closing quote.

Could there be at least an option to change the behaviour? 

(All rests on interpretation of being still 'inside' a string.)

**Comment by abo-abo** [comment]
> From paredit.el:
> 
>   (cond ((paredit-in-string-p)
>          (if (eq (point) (- (paredit-enclosing-string-end) 1))
>              (forward-char)             ; Just move past the closing quote.
> ...
> 
> Could there be at least a custom variable that would toggle the behaviour?

Of course. Just use `lispy-doublequote` which behaves exactly like this, instead of `lispy-quotes`.

`lispy-doublequote` is bound to <kbd>"</kbd> in `lispy-mode-map-paredit`, and `lispy-quotes` is bound
to <kbd>"</kbd> in `lispy-mode-map-lispy`.
