### ISSUE TITLE
lispy-goto support for ClojureScript

### ISSUE THREAD

**Issue by ftravers** [abo-abo/lispy#102]
Can ClojureScript be supported for the various lispy-goto function?  Loving the extension otherwise!  Most stuff just works in *.cljs files anyway.

**Comment by abo-abo** [comment]
Lispy simply depends on `clojure-semantic` for Clojure parsing. I don't know much about Clojurescript, maybe you can make it work with this code:

```elisp
(add-to-list 'semantic-new-buffer-setup-functions
             (cons 'clojurescript-mode 'wisent-clojure-default-setup))
```

**Comment by sp3ctum** [comment]
I use this instead:

```lisp

;; Go to the definition of the symbol at point
(evil-define-key 'normal clojure-mode-map (kbd "C-.") 'cider-jump-to-var)
(evil-define-key 'normal clojure-mode-map (kbd "C-,") 'cider-jump-back)
```

**Comment by abo-abo** [comment]
Alright, whatever works for you. But as far as I know, CIDER is only aware of the loaded code, while lispy's <kbd>g</kbd> can jump to un-loaded code as well.

**Comment by sp3ctum** [comment]
Yes, you're right. Only after the code is evaluated can it be jumped to, using cider-jump-to-var.

**Comment by ag91** [comment]
Another approach to handle this if the fantastic goto of lispy does not work is:

```
(defun lispy-use-cider-if-no-semantic (fn &rest r)
    (if (cider-connected-p) (call-interactively #'xref-find-definitions)  (apply fn r)))
  (advice-add 'lispy-goto-symbol :around #'lispy-use-cider-if-no-semantic)
```

Anyway, thanks for this amazing mode! I am messing around a lot of code because I started just recently, but when I get it right... it is just so cooool!

**Comment by cstby** [comment]
Cider now prefers xref as a default rather than `cider-find-var)`. See https://github.com/clojure-emacs/cider/commit/15b6d205b6311453349144afc20d7ac4a820b0ab. Lispy could probably use

**Comment by abo-abo** [comment]
Just tested this now, since I'm playing with ClojureScript recently. As @ftravers says, most stuff just works for cljs anyway. So I think we can close this issue.

A possible cool development is https://github.com/borkdude/edamame by @borkdude. Since it provides line info, maybe it could be used in place of `clojure-semantic`? I'm not too happy with `clojure-semantic` anyway: it's slow to parse, and often the cache gets corrupted.
