### ISSUE TITLE
New cider debugger unusable due to conflicting key bindings

### ISSUE THREAD

**Issue by sp3ctum** [abo-abo/lispy#103]
Take this function:
```
(defn letters-in-order? [word]
  (= word (apply str (sort word))))
```

Using cider-0.10 (still a snapshot), `C-u C-M-x` will instrument it for debugging. The mode for debugging will use key bindings for navigation in the debugged form, much like edebug will for elisp.

The problem is, lispy's keybindings overwrite the default ones somehow, and cider cannot detect these commands. For example, `n` should be `next` in the `cider--debug-mode` but when lispy-mode is active, `n` points to `special-lispy-new-copy` instead.

When lispy-mode is disabled, `n` points to this:

```lisp
n runs the command cider-debug-mode-send-reply (found in
cider--debug-mode-map), which is an interactive compiled Lisp function
in ‘~/git/emacs.d/elpa/cider-20150820.852/cider-debug.el’.

It is bound to q, e, i, l, o, c, n.

(cider-debug-mode-send-reply COMMAND &optional KEY)

Reply to the message that started current bufer's debugging session.
COMMAND is sent as the input option.  KEY can be provided to reply to a
specific message.
```

**Comment by sp3ctum** [comment]
I feel lispy's keybindings are a bit invasive. If I'm not mistaken, they are set in a couple of keymaps so overwriting them is tricky. Here's my configuration, see how I removed them:

```lisp
(define-key evil-insert-state-map (kbd "C-k") 'nil)
(define-key global-map (kbd "C-k") 'lispy-kill)

(defun my-remove-lispy-key (key)
  (define-key lispy-mode-map-base key nil)
  (define-key lispy-mode-map-lispy key nil)
  (define-key lispy-mode-map-oleh key nil)
  (define-key lispy-mode-map-paredit key nil)
  (define-key lispy-mode-map-special key nil)
  (define-key lispy-mode-map-x key nil))

(eval-after-load 'lispy
  `(progn
     (my-remove-lispy-key (kbd "C-a"))
     (my-remove-lispy-key (kbd "C-<return>"))
     (my-remove-lispy-key (kbd "M-<return>"))
     (global-set-key (kbd "C-ä") 'lispy-kill-at-point)

     ;; copy (yank) the current thing
     (lispy-define-key lispy-mode-map (kbd "y") 'lispy-new-copy)

     ;; switch o, d
     (lispy-define-key lispy-mode-map (kbd "o") 'lispy-different)
     (lispy-define-key lispy-mode-map (kbd "d") 'lispy-other-mode)

     ;; switch f, i
     (lispy-define-key lispy-mode-map (kbd "f") 'special-lispy-tab)
     (lispy-define-key lispy-mode-map (kbd "i") 'special-lispy-flow)))

(add-hook 'emacs-lisp-mode-hook (lambda () (lispy-mode 1)))
(add-hook 'clojure-mode-hook (lambda () (lispy-mode 1)))

(setq lispy-eval-display-style 'overlay)

(provide 'my-lispy-config)
```

**Comment by abo-abo** [comment]
Look at the code of `lispy--edebug-commandp`: it handles this issue for edebug. A similar approach can be made for CIDER. But I suggest to wait a while, since CIDER gets updated a lot, and what works now may break very soon in the future.

**Comment by sp3ctum** [comment]
Ah, that looks perfect! Good to know this might be covered pretty easily.

I agree on waiting, though would like to point out cider's goal is to "try to be consistent with edebug", as stated [in cider's debugger keybindings documentation](https://github.com/clojure-emacs/cider#keys).

**Comment by sp3ctum** [comment]
I tried it out locally, overwriting lispy stuff. It seems to work very well.
I'll open a pull request later.
