### ISSUE TITLE
Unwanted whitespace after sexp manipulation

### ISSUE THREAD

**Issue by lionel-** [abo-abo/lispy#105]
Calling one of `(lispy-move-left)`, `(lispy-move-right)` or `(lispy-down-slurp)` when point is at `|` below causes unwanted whitespace to appear.

```lisp
(

 |(sexp)
 (sexp))
```

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by lionel-** [comment]
Works great, thanks for the quick fix.
