### ISSUE TITLE
(lispy-down) gets confused with string

### ISSUE THREAD

**Issue by lionel-** [abo-abo/lispy#107]
Calling `(lispy-down)` at `|` below moves the point into the string and triggers an "Unexpected" event.
```
(|(sexp1 (sexp2)
		(sexp3 "string")))
```

**Comment by lionel-** [comment]
it doesn't happen when the sexp is well indented

**Comment by abo-abo** [comment]
The general assumption is that the code is well-indented. Otherwise, it takes a lot more computing time for basic commands.  So I think it should be left as is for now.

**Comment by lionel-** [comment]
ah ok, thanks.

It happened while I was browsing some internal Emacs code. I don't understand why so much of the historical code is weirdly indented, it makes it difficult to read. I suppose it has something to do with the 72 char limit.
