### ISSUE TITLE
eldoc overrides minibuffer eval results

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#109]
For example, eval any elisp in the scratch buffer using `lispy-eval` and `eval-last-sexp`. `lispy-eval` shows the result until eldoc overrides it, while `eval-last-sexp` will continue to show the result.

**Comment by abo-abo** [comment]
Thanks. You can use a similar code for other commands as well:

    (eldoc-remove-command 'special-lispy-eval)
