### ISSUE TITLE
Question: mode based dispatch for lispy specials

### ISSUE THREAD

**Issue by cmccloud** [abo-abo/lispy#111]
I was thinking about the best way to configure lispy special keys to behave differently depending on the current mode(s). 
I mocked up something for major-modes that I think I can extend, but I thought I would check to see if you have any thoughts about a better way to go about this. 

Right now I'm thinking about something like this:
```
(defun lispy-define-key-for-modes (key alist)
        (eval `(defun ,(intern (concat "lispy-generic-key--" key)) ()
                 (interactive)
                 (when (assoc major-mode ',alist)
                   (funcall (cdr (assoc major-mode ',alist))))))
        (lispy-define-key lispy-mode-map (kbd key)
                          (intern (concat "lispy-generic-key--" key))))

(lispy-define-key-for-modes "o" '((emacs-lisp-mode . some-func)
                                  (clojure-mode . some-other-func)))

```

Thanks for lispy, btw. Really incredible.

**Comment by abo-abo** [comment]
The `lispy-define-key` function already generates a `lambda` (almost `defun`) statement via `lispy--insert-or-call`.  So you'd be doing it twice your way.

A mechanism is already in place that can work for you:

```elisp
(lispy-define-key map "a" 'lispy-ace-symbol
      :override '(cond ((looking-at lispy-outline)
                        (lispy-meta-return))))
```

The above will forward to `self-insert-command` or `lispy-ace-symbol`. But if `(looking-at lispy-outline)` is true, then instead to `lispy-meta-return`.

The only thing for you to do is to change the conditional to check for `major-mode`.

**Comment by cmccloud** [comment]
Thanks, I didn't realize that existed. Much appreciated.
