### ISSUE TITLE
lispy-fill for comments should use comment-indent-new-line

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#113]
Take the following snippet as an example, in the scratch buffer with `emacs-lisp-mode`:

```
(define-key lispy-mode-map-paredit (kbd "DEL") nil) ; Smartparens delete works better than lispy delete--lispy has some unresolved bugs with deletion of opening delimiters.
```

Calling lispy-fill in comment body:
```
(define-key lispy-mode-map-paredit (kbd "DEL") nil) ; Smartparens delete works
                                                    ; better than lispy
                                                    ; delete--lispy has some
                                                    ; unresolved bugs with
                                                    ; deletion of opening
                                                    ; delimiters.
```

Calling lispy-fill at `;` character:
```
(define-key lispy-mode-map-paredit (kbd "DEL") nil) ; Smartparens delete works
                                        ; better than lispy
                                        ; delete--lispy has some
                                        ; unresolved bugs with
                                        ; deletion of opening
                                        ; delimiters.
```

Manually calling `indent-new-comment-line` at fill-width:
```
(define-key lispy-mode-map-paredit (kbd "DEL") nil) ; Smartparens delete works
                                        ; better than lispy delete--lispy has
                                        ; some unresolved bugs with deletion of
                                        ; opening delimiters.
```

I think if case 2 could be replaced with case 3, it would make for the most readable comments.

**Comment by abo-abo** [comment]
`lispy-fill` just forwards to `fill-paragraph` in both cases that you describe.  That is a built-in command, and I think it works OK.

You can try to advise `fill-paragraph` or `lispy-fill` if you want. Personally, I always place comments on their own line, and not after any expression.

**Comment by sooheon** [comment]
Ok that makes sense. Would you consider changing the behaviour of lispy-comment when just infront of the last closing parens, then? Currently, lispy comment from `(foo|)` gives `(foo) ;`, encouraging comment after expressions. Could it give
```
(foo
 ;; |
 )
```
instead?

**Comment by abo-abo** [comment]
Good idea, thanks.

**Comment by sooheon** [comment]
Should we add one more test case:
```
(should (string= (lispy-with "((foo)|)" ";")
                 "((foo)\n ;; |\n )"))
```
The logic should still hold the same, that if I'm inserting a comment between the two closing parens, the comment should end up between the two closing parens, not after the final closing paren.

**Comment by abo-abo** [comment]
Thanks again.
