### ISSUE TITLE
lispy-goto candidate string length miscalculation with (fringe-mode 0)

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#117]
<img width="676" alt="screen shot 2015-09-07 at 12 32 13 pm" src="https://cloud.githubusercontent.com/assets/302945/9708819/7c195ab8-555c-11e5-90f9-cd43f2fa2c2b.png">
This occurs with any frame width smaller than 80.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by sooheon** [comment]
Thanks. It's good, but `(- (window-width) 3)` is tickling my ocd, I think it can safely be `(- (window-width) 1)` unless it's to avoid some edge case? Also, the strings which require "..." appended still are off by 1.

<img width="676" alt="screen shot 2015-09-08 at 12 43 48 am" src="https://cloud.githubusercontent.com/assets/302945/9720020/091b70c8-55c5-11e5-9f04-95dc0bbdf181.png">
