### ISSUE TITLE
Calling lispy-goto populates company-begin-commands incorrectly

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#118]
Not sure if lisps-goto is the only culprit, but here is my company-begin-commands after manual definition: `'(self-insert-command)` and here it is after running special-lispy-goto: 
```
(special-swiper special-digit-argument special-lispy-tilde special-lispy-repeat special-lispy-ace-subword special-lispy-visit special-lispy-edebug-stop special-lispy-x special-lispy-ediff-regions special-lispy-back special-lispy-new-copy special-lispy-teleport special-lispy-view special-lispy-ace-char special-lispy-ace-paren special-lispy-undo special-lispy-clone special-lispy-widen special-lispy-narrow special-lispy-shifttab special-lispy-tab special-lispy-beginning-of-defun special-lispy-eval-and-insert special-lispy-eval special-lispy-mark-list special-lispy-ace-symbol-replace special-lispy-ace-symbol special-lispy-stringify special-lispy-alt-multiline special-lispy-oneline special-lispy-move-down special-lispy-move-up special-lispy-convolute special-lispy-join special-lispy-raise-some special-lispy-raise special-lispy-splice special-lispy-barf special-lispy-slurp special-lispy-outline-goto-child special-lispy-outline-prev special-lispy-outline-next special-lh-knight/body special-lispy-occur special-lispy-paste special-lispy-eval-other-window special-lispy-other-mode special-lispy-different special-lispy-up special-lispy-down special-lispy-flow special-lispy-left special-lispy-right special-lispy-goto-mode special-lispy-other-space special-lispy-move-right special-lispy-up-slurp special-lispy-down-slurp special-lispy-move-left special-lispy-goto-elisp-commands special-lispy-goto-def-ace special-lispy-goto-def-down special-lispy-quit special-pop-tag-mark special-lispy-follow special-lispy-goto-projectile special-lispy-goto-recursive special-lispy-goto-local special-lispy-goto self-insert-command org-self-insert-command orgtbl-self-insert-command c-scope-operator c-electric-colon c-electric-lt-gt c-electric-slash)
```

After this happens, company tries to run after every special action, giving me errors like 
```
Company: An error occurred in auto-begin
Nothing to complete
```
Which clutters the mini buffer after eval and such. If you need more detailed repro steps or debugging, I can try if you give me some instructions.

**Comment by abo-abo** [comment]
Your `company-begin-commands` look to be correct. They are modified after loading lispy, since in `lispy-mode` each character you type in is not inserted not by `self-insert-command`, but instead e.g. "g" is inserted by `special-lispy-goto`, so company needs to know that in order to show completion popup after you type `g`.

I don't have this bug with [my company settings](https://github.com/abo-abo/oremacs/blob/github/oleh/modes/ora-company.el). See if they differ from your settings.

**Comment by sooheon** [comment]
I have not encountered this bug recently, and I think it's actually more complicated and doesn't involve `company-begin-commands`. I'll see if I can find a more reliable way to reproduce.

**Comment by abo-abo** [comment]
Please reopen if the issue still exists.
