### ISSUE TITLE
`lispy-tab` fails in Clojure on symbols and keywords containing #

### ISSUE THREAD

**Issue by Peeja** [abo-abo/lispy#120]
I discovered this while working with Hiccup-style templating. `lispy-tab`ing the following sexp:

```clojure
[:h1#first-heading]
```

replaces the sexp with `nil`. It has the same result for any sexp which contains a keyword containing `#`, even if deeply nested. It also happens for symbols, which are also allowed to contain `#` in Clojure, as in:

```clojure
(foo#bar)
```

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by Peeja** [comment]
Works great, thanks!

Has `lispy-tab` always required an nREPL connection for Clojure, or is that new?

**Comment by abo-abo** [comment]
> Has lispy-tab always required an nREPL connection for Clojure, or is that new?

This wasn't (and isn't) the case, as far as I'm aware. If you can reproduce, please file a new bug.
Only eval-related functions should require a nREPL connection.
