### ISSUE TITLE
`lispy-tab` requires an nREPL connection in Clojure

### ISSUE THREAD

**Issue by Peeja** [abo-abo/lispy#121]
Apparently that's not intentional.

https://github.com/abo-abo/lispy/issues/120#issuecomment-139267781

In a Clojure file, without an nREPL connection, if I `lispy-tab` any sexp, I get "No active nREPL connections" and the sexp isn't reformatted. Looking at the backtrace, I think this may be a new Cider bug. Does that look right? On the one hand, I'm not clear why `lispy-tab` invokes `clojure-mode`; on the other, I'm not sure why `clojure-mode` errors if there's no nREPL connection yet.

If this looks like a Cider bug to you, go ahead and close this and I'll open an issue over there.

```
Debugger entered--Lisp error: (error "No active nREPL connections")
  signal(error ("No active nREPL connections"))
  error("No active nREPL connections")
  (if (cider-connected-p) nil (error "No active nREPL connections"))
  cider-ensure-connected()
  cider-current-connection()
  cider-current-ns()
  cider-refresh-font-lock()
  cider-mode()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook clojure-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook clojure-mode-hook))
  run-mode-hooks(clojure-mode-hook)
  clojure-mode()
  lispy--read("(foo\n       bar)")
  lispy--normalize-1()
  lispy-tab()
  call-interactively(lispy-tab)
  (cond ((lispy--edebug-commandp) (call-interactively lispy--edebug-command)) ((region-active-p) (call-interactively (quote lispy-tab))) ((lispy--in-string-or-comment-p) (call-interactively (quote self-insert-command))) ((or (lispy-left-p) (lispy-right-p) (and (lispy-bolp) (looking-at ";"))) (call-interactively (quote lispy-tab))) (t (setq this-command (quote self-insert-command)) (call-interactively (quote self-insert-command))))
  special-lispy-tab()
  call-interactively(special-lispy-tab nil nil)
  command-execute(special-lispy-tab)
```

**Comment by Peeja** [comment]
I should add that *with* an active connection, `lispy-tab` behaves as expected.

**Comment by abo-abo** [comment]
From this backtrace it's clear that an active connection is needed by `clojure-mode`, which `lispy-tab` needs in order to indent Clojure code according to Clojure rules.  So you should file this bug against `clojure-mode` instead, or maybe check some hooks in your config.

**Comment by Peeja** [comment]
Yeah, it seems fishy, because I know `clojure-mode`/`cider-mode` doesn't need an nREPL connection when I open a Clojure file. Can you elaborate on what `lispy-tab`/`lispy--read` uses `clojure-mode` for? Is it running in a new buffer somewhere? That would help me write a useful issue for the Cider team.

**Comment by abo-abo** [comment]
Basically, each mode knows its own indentation level. `lispy-tab` reads an expression in its own buffer, then inserts it in a temporary buffer of a particular mode, then calls `indent-region` and inserts the result from the temporary buffer into the original buffer.
