### ISSUE TITLE
Include `/` as subword delimiter for Clojure?

### ISSUE THREAD

**Issue by Peeja** [abo-abo/lispy#123]
For Clojure especially, but perhaps for Elisp too, it would be nice if `/` delimited a subword. I often want to use <kbd>-</kbd> to jump to the name part of a namespace-qualified symbol, but Lispy currently doesn't give me that option. It does appear to sort of half-recognize it as a subword delimiter, though, so maybe this is a bug. Let me explain what I mean:

```clj
|(clj-time/minus (clj-time/now) (clj-time/days 1))
```

(Where `|` is point.)

This uses `clj-time` to calculate 1 day ago. Let's say I'd like to change this to 1 day from now. I can do that by changing `minus` to `plus`. I'd like to mark `minus` to change it, so I press <kbd>-</kbd>:

```clj
|(c⒜lj-t⒝ime/minus (⒞clj-t⒟ime/now) (⒠clj-t⒡ime/days 1⒢))
```

(Where `⒜`, etc. are the highlighted ace characters.)

Notice that `-` doesn't let me jump to `minus` (or `now` or `days`). However, if I press <kbd>b</kbd>, I get:

```clj
(clj-|[time]/minus (clj-time/now) (clj-time/days 1))
```

(Where `[…]` is the region.)

Since <kbd>-</kbd> doesn't appear to recognize `/` as a subword delimiter, I would have expected all of `time/minus` to be marked (though I'm glad that it's not). Even better, look what happens when I press <kbd>j</kbd>:

```clj
(clj-time/|[minus] (clj-time/now) (clj-time/days 1))
```

Hey, that's what I was after to begin with! So, at least I've got a reasonable workaround. But if `/` delimits a subword here, why doesn't `-` let me jump to it?

I wouldn't be surprised if there's a good reason for it, but if not please consider this a bug report or feature request as appropriate. :)

**Comment by abo-abo** [comment]
> I wouldn't be surprised if there's a good reason for it, but if not please consider this a bug report or feature request as appropriate. :)

There's no good reason, except that I rarely use `foo/bar` notation. This should be fixed now, thanks for the suggestion.

**Comment by Peeja** [comment]
Thanks! :cake:
