### ISSUE TITLE
lispy-mark-symbol from lispy-right in clojure

### ISSUE THREAD

**Issue by drorbemet** [abo-abo/lispy#124]
Can the following behaviour be reproduced and is it a bug?
What should be marked after lispy-mark-symbol at lispy-right?

after lispy-mark-symbol [3] is marked
```` clojure
([3])| -> (|[3])
  ([3] )| -> (|[3] )
````

But her M-m marks 3] instead of 3 or [3]
```` clojure
([ 3])| -> |3]
  ([2 4] [1 2] [1 3])|
````

after M-m lispy-mark-symbol
args} is marked not args or {:key args}
```` clojure
(defn some-func
  "comment"
  [&args]
  {:key args})|
````

after M-m lispy-mark-symbol
} ist marked not (* args) or {:key (* args)}

```` clojure
(defn some-func
  "comment"
  [&args]
  {:key (* args)})|
````

**Comment by abo-abo** [comment]
Thanks.
