### ISSUE TITLE
lispy-unbind-variable with clojure let form

### ISSUE THREAD

**Issue by drorbemet** [abo-abo/lispy#128]
Can the following behaviour be reproduced and is it a bug?
- starting state
```` clojure
(defn foobar []
  (let |[x 10 y 20 z 30]
    (+ 1 x y z)
    (+ 2 x z y)
    (+ 3 y x z)
    (+ 4 y z x)
    (+ 5 z x y)
    (+ 6 z y x)))
````
- after lispy-unbind-variable the let vector with the left binds [y 20 z 30] is missing
```` clojure
(defn foobar []
  (let |(+ 1 10 y z)
    (+ 2 10 z y)
    (+ 3 y 10 z)
    (+ 4 y z 10)
    (+ 5 z 10 y)
    (+ 6 z y 10)))
````

**Comment by bcarrell** [comment]
I don't think `lispy-unbind-variable` supports Clojure.

**Comment by drorbemet** [comment]
As far as I understood to support Clojure is one of lispy's goals.

**Comment by bcarrell** [comment]
It might be, but I don't think this particular function works with Clojure at the current time.  It's not a bug; it's just not implemented.

**Comment by abo-abo** [comment]
It's true that not yet implemented for Clojure. In any case, the starting state should be for Clojure:

```clojure
(defn foobar []
  (let [~x| 10 y 20 z 30]
    (+ 1 x y z)
    (+ 2 x z y)
    (+ 3 y x z)
    (+ 4 y z x)
    (+ 5 z x y)
    (+ 6 z y x)))
```

The usual notation is that `|` is the point and `~` is the mark.

**Comment by abo-abo** [comment]
Should work now, please test. You can bind `lispy-unbind-variable-clojure` in your config if you don't want to call it from special.  Otherwise, just mark the var and press <kbd>xu</kbd>.
