### ISSUE TITLE
Is there a way to cut/kill a sexp?

### ISSUE THREAD

**Issue by ftravers** [abo-abo/lispy#129]
C-d doesn't put it in the kill ring for me.
C-k kills the sexp and it's following siblings.

I just want to cut/kill the current sexp, say while I'm sitting on the opening paren.  I'm sure I'm just missing it and it's somewhere.

**Comment by abo-abo** [comment]
<kbd>C-,</kbd> (`lispy-kill-at-point`) will kill the containing list, opening and closing paren count as part of a list.
Also <kbd>n</kbd> (`lispy-new-copy`) will copy the current thing (list or region) to the kill ring, so <kbd>n C-d</kbd> from left or <kbd>n DEL</kbd> from right will cut.

**Comment by ftravers** [comment]
Ahhh, that lispy-kill-at-point, does just the thing!

Thank you abo-abo, for one of my favorite plugins!!!

**Comment by ftravers** [comment]
cut/kill for regions.

I see 'lispy-delete' cut/kills for highlighted regions, whereas 'lispy-kill-at-point' seems to duplicate the highlighted item and put it on the next line?!?

It would be nice to have the same key/key-chord do the semantic cut/kill for either sexp or highlighted region.  Am I missing something again?

Thanks so much abo-abo for this killer pluggin, loving it more everyday!

**Comment by abo-abo** [comment]
> I see 'lispy-delete' cut/kills for highlighted regions,

This shouldn't be true. `lispy-delete` should only delete, it never modifies the kill ring.

> whereas 'lispy-kill-at-point' seems to duplicate the highlighted item and put it on the next line?!?

You're right. The behavior of <kbd>C-,</kbd> when the region is active is a bit strange.  I never noticed this before because I always use <kbd>C-w</kbd> when the region is active. I've fixed this just now.

> Thanks so much abo-abo for this killer pluggin, loving it more everyday!

You're welcome, keep digging up those bugs:)
