### ISSUE TITLE
lispy-backspace Deletes Entire Comments When at BOL

### ISSUE THREAD

**Issue by noctuid** [abo-abo/lispy#131]
For example, if the point is on an empty line just below a function definition or something, it will just delete the line back to the end paren.

Before:
```
(....)
|
```
After:
```
(...)|
```

On the other hand, when a comment is on the line before the point, the comment lines will be deleted entirely.

Before:
```
;; comment
;; comment
|
```
After:
```
|
```

I think it would be preferable to just delete to the previous end of line all the time when at the beginning of the line (or at least have an option for this). I keep accidentally deleting my comments.

**Comment by abo-abo** [comment]
This is the intended behavior, since a comment can be seen as an atom (unless you're inside a comment). Pressing <kbd>DEL</kbd> before an atom should delete it.

For example: `(foo) |(bar)` -> <kbd>DEL</kbd> -> `|(bar)`.

Additionally, if it did a simple `delete-backward-char`, like you propose, what should be done here:

```elisp
;; foo
|(bar
  (baz))
```

- `delete-backward-char` will result in unbalanced parens.
- commenting the full sexp isn't straightforward, unless it's on a single line.
- only moving the point instead of deleting isn't straightforward.

I'd be happy to add some customization if there's a reasonable solution to the corner cases that it entails.

**Comment by noctuid** [comment]
The current behaviour makes sense based on the case you describe. Commenting the full sexp doesn't seem like an expected result of hitting backspace there. Deleting the comment in that case does seem like the best option (and most expected when thinking of it as an atom). The times I'm accidentally deleting whole comments are after I've hit RET to go to a newline and decided to change what I wrote, so there is never a sexp after the point. 

I see that `lispy-delete-backward` already takes into account a lot of different cases. If its more straightforward and not too complicated to change the behaviour just for the case where the point is on an empty line after a comment, I think it would nice to have an option for that. If you think that would be a bad idea, I think it would be nice to have an option to treat each comment line as an atom instead of all consecutive comment lines as a single atom.

**Comment by abo-abo** [comment]
Thanks for bringing this up. Let me know if the change on the empty lines is sufficient.

> treat each comment line as an atom instead of all consecutive comment lines as a single atom.

I've thought about this. The main counter-argument to comment lines being atoms is that if you move comment lines around with e.g. <kbd>w</kbd>/<kbd>s</kbd>, the comment no longer makes sense.  So the comment has to be the atom. However, you can split unrelated comments with one or more newlines.

**Comment by noctuid** [comment]
Thank you; it's working well.

That makes sense. Are `w` and `s` supposed to work with comments split by newlines though?

**Comment by abo-abo** [comment]
Yes, they're considered independent comments. Starting from:

```elisp
~;; tricky|
(foo)

;; easy
(bar)
```

You can swap two comments with <kbd>sskw</kbd>. Weird case, but generally moving a comment wrt. code can be useful.

**Comment by noctuid** [comment]
Trying that example gives me "Unexpected" in the echo area. Is some configuration needed? Should I make an issue?

**Comment by abo-abo** [comment]
Please do. This functionality should work without extra configuration.
