### ISSUE TITLE
How to Unbind a Key?

### ISSUE THREAD

**Issue by noctuid** [abo-abo/lispy#132]
I realize that there have been at least four issues asking about how to type "]" and "[", but I actually want to unbind these keys (as opposed to using `}`). I have tried `(define-key lispy-mode-map "]" nil)` without success and thought maybe I was doing it incorrectly, but I notice that in another issue this is the way you recommend unbinding. Any ideas on why this isn't working?

In the `lispy-mode-map` this key is showing up twice when I do this (first as `(93)` and then as `(93 . lispy-forward)`).

**Comment by abo-abo** [comment]
You need to unbind it in a place where it was bound:

```elisp
(define-key lispy-mode-map-lispy (kbd "[") nil)
;; (lispy-set-key-theme '(special lispy c-digits))
```

`lispy-mode-map` is a composed of several keymaps, depending on the call to `lispy-set-key-theme`.

**Comment by noctuid** [comment]
Thank you for the explanation.
