### ISSUE TITLE
lispy-newline-indent Drags End of CL Block Comment Down With It

### ISSUE THREAD

**Issue by noctuid** [abo-abo/lispy#133]
Here is an example where `/` represents the point:
```
#|
... common lisp block comment ...
|#/
```
After using `lispy-newline-indent` or `lispy-newline-indent-plain`, the point will still remain at the end of the block comment and the `|#` will be moved down a line:
```
#|
... block comment ...

|#/
```

**Comment by abo-abo** [comment]
Thanks.
