### ISSUE TITLE
Some Commands Do Not Work When Before a Comment

### ISSUE THREAD

**Issue by noctuid** [abo-abo/lispy#134]
I have the latest lispy from MELPA. When pressing `s` or `w` in special at the beginning of the line before a comment, "Unexpected" appears for me in the echo area. They work before `;;;` comments though.

I don't know if these commands are meant to work before comments, but `lispy-clone` also gives "Unexpected", and `lispy-tab` often acts strangely by deleting backwards and sometimes leaving unmatched parens.  Here is an example where `|` represents the point (tested where this was the only text in a scratch buffer in emacs lisp mode):

```
;; comment
(defun test ()
  |;; message something
  (message "baz"))
```

Pressing `lispy-tab` will delete the entire defun and result in the following:
```
;; comment|
```

Here is another example.
```
(defun test2 ()
  "Docstring."
  (let ((foo "bar")
        (baz "qux"))
    |;; message something
    (message "wow")))
```
Pressing `lispy-tab` here will jump to the the final paren of the defun and delete it:
```
(defun test2 ()
  "Docstring."
  (let ((foo "bar")
        (baz "qux"))
    ;; message something
    (message "wow"))|
```
The longer the function is, the weirder `lispy-tab` seems to act before a comment. Sometimes it won't do anything. Other times it will delete stuff and insert a "nil" in place of what it deleted. It works fine before `;;; Code:` though.

Another strange command I found is `lispy-oneline`. When before multiple consecutive comment lines that are separated from any code, it deletes parts of those comments. When there is only one comment line, it will jump to the end of it.

All the other lispy keys I've tried work fine before comments (or do nothing because they wouldn't make sense to use before a comment).

**Comment by abo-abo** [comment]
Thanks for the test cases. The comment handling is relatively new, and previously the intent was to have the comment marked with a region before working on it.

But there's no reason for this not to work without a region. Well, the reason previously was that you can't get to a comment with common commands. Usually, I get to a comment with <kbd>mk</kbd> on the sexp right after the comment.

**Comment by sooheon** [comment]
Found another case which may be related:
```
(defun test ()
  "doc"
  |(foo bar)) ;; comment
```
lispy-kill with cursor at that point will leave parens unbalanced as well.

**Comment by abo-abo** [comment]
Thanks, please check.

**Comment by noctuid** [comment]
@abo-abo Thanks, most everything seems to be working now. `lispy-oneline` and `lispy-tab` still delete all but the first line of consecutive comment lines that are separated from code though.

**Comment by abo-abo** [comment]
@noctuid Could you open a new issue for `lispy-oneline` and `lispy-tab` with a specific code example?
