### ISSUE TITLE
Nested expressions and 2e (comment eval)

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#135]
```
(((+ 1 2 3)|))
```
with point at |, pressing 2e unbalances parens like 
```
(((+ 1 2 3)
;; => 6))
```
I think this has to do with a previous change to lispy-comment to move comments to newlines when in-between parens. I think either 
```
(((+ 1 2 3)
;; => 6
   ))
```
or 
```
(((+ 1 2 3) ;; => 6
   ))
```
Could work in this case, the second might be preferable if you're inside a nested expression and eval'ing and printing a lot.

**Comment by abo-abo** [comment]
Thanks.
