### ISSUE TITLE
`lispy-flow` briefly shows `f`

### ISSUE THREAD

**Issue by Peeja** [abo-abo/lispy#137]
This might be more of a config/interaction problem than a problem with Lispy itself, especially if no one else is seeing this, but it's starting to bug me (mostly because I can't figure out why the heck it happens). When I press <kbd>f</kbd> to `lispy-flow`, I briefly see the `f` in the buffer.

![lispy-flow](https://cloud.githubusercontent.com/assets/2407/10891776/d2ffec10-816d-11e5-8e22-7142cb3356e3.gif)

The same doesn't happen with any other navigation commands.

**Comment by abo-abo** [comment]
Can you reproduce with `emacs -Q`? It might be some advice/key-chord/other package interfering.

**Comment by Peeja** [comment]
Hmm, I can't. But <kbd>f</kbd> is bound to `special-lispy-flow`, so it's not being wrapped that way. Is there a way to see if there's any advice attached?

**Comment by abo-abo** [comment]
> Hmm, I can't.

Try bisecting your init.el. Comment out half, see if the bug stays, subdivide again etc.

> But f is bound to special-lispy-flow, so it's not being wrapped that way. Is there a way to see if there's any advice attached?

Try grepping your config for `defadvice` or `add-function`. Also `helm-manage-advice`.

**Comment by zilongshanren** [comment]
@abo-abo 
I could confirm this issue, I'm using Spacemacs latest develop branch.

**Comment by abo-abo** [comment]
Figured out the culprit: evil-escape-mode. Toggle that mode off and the problem disappears. You can also raise an issue in https://github.com/syl20bnr/evil-escape/ if you need that package.

**Comment by Peeja** [comment]
Ah, of course! Thanks, I'll close.

I don't actually use Evil anymore (I use Spacemacs in Holy Mode), so I'm not going to file the issue over there, but if @zilongshanren or someone else who comes across this issue wants to see this fixed, that's the next step.
