### ISSUE TITLE
lispy-tab in clojure purges character literals

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#138]
In Clojure,
```
{\e 16782 \a 12574 \i 11674 \r 11042 \t 10959
 \o 10466 \n 9413 \s 8154 \l 8114 \c 6968
 \u 5373 \p 4809 \m 4735 \d 4596 \h 4058
 \g 3380 \b 3121 \y 2938 \f 2157 \v 1574
 \w 1388 \k 1235 \x 507 \z 356 \q 343 \j 220}
```
`i` at the opening brace will strip the `\` from the character literals.
```
{e 16782 a 12574 i 11674 r 11042 t 10959
 o 10466 n 9413 s 8154 l 8114 c 6968
 u 5373 p 4809 m 4735 d 4596 h 4058
 g 3380 b 3121 y 2938 f 2157 v 1574
 w 1388 k 1235 x 507 z 356 q 343 j 220}
```

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by sooheon** [comment]
Thanks, it fixes single character cases. However, other characters like `\space` `\backspace` still get trimmed.

**Comment by abo-abo** [comment]
Could you point me to the official spec for these character escapes?

**Comment by sooheon** [comment]
Here: http://clojure.org/reader under literals is what I could find. They are java.lang.Character literals.

**Comment by yuhan0** [comment]
This is still an issue for some symbol characters:
```clojure
(str \! \@ \# \$ \% \& \* )
;; =lispy-tab=>
(str ! @ \# $ % & *)

```

In particular, `\#` at the end of a form will eat up the closing paren, breaking the code structure:
```clojure
(str \#)
;; =lispy-tab=> 
(str \#
```

**Comment by abo-abo** [comment]
@yuhan0 Thanks, please test.
