### ISSUE TITLE
lispy-goto causes "Company: an error occured in auto-begin" error

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#142]
The previous issue was closed, but I found that it is much more reproducible now. I'm on 25.0.50.1. With emacs -Q, the following consistently reproduces it for me:

1. M-x package-initialize
2. Open init.el of .emacs.d (just some .el file for lispy-goto to parse)
2. M-x company-mode
2. M-x lispy-mode
3. Call lispy-goto with `g` at special, make a completion or quit with C-g, and then move about with lispy special keys (d, j, k, etc.)

In the minibuffer, I see "Nothing to complete", and the Messages buffer shows that 

    Company: An error occurred in auto-begin
    Nothing to complete

is being spammed on every lispy-special action.

Can anyone else confirm?

**Comment by nixmaniack** [comment]
I tried reproducing this in clean emacs with company and lispy with no success. But I faced this when using Spacemacs. I had a hunch that it was invoking at some point `indent-for-tab-command` which caused company to pop up. I faced this mostly when deleting `lispy-delete-backward`.

**Comment by sooheon** [comment]
Hm, I wonder why it reproduces for me with emacs -Q, then. Could it be that package-initialize is loading whatever other package is causing the problem?

**Comment by abo-abo** [comment]
The issue is caused by `company-capf` in `company-backends`. I've turned that off years ago, so I never experienced the bug:

```elisp
(setq company-backends
      '(company-elisp
        ;; company-semantic
        ;; company-capf
        (company-dabbrev-code company-gtags company-etags
         company-keywords)
        company-files
        company-dabbrev))
```

**Comment by sooheon** [comment]
Exactly what functionality do you lose by turning it off? I don't quite get what all these different backends do.

**Comment by abo-abo** [comment]
I don't miss anything currently, `company-mode`-wise.

**Comment by sooheon** [comment]
I'm finding that company-capf is actually pretty crucial for "intelligent" completions with cider, at least. Here are two comparison pics. Any ideas how to fix this interaction? 

<img width="732" alt="screen shot 2015-11-22 at 10 14 32 pm" src="https://cloud.githubusercontent.com/assets/302945/11323984/7add7c42-9166-11e5-8187-7ab5348aee3c.png">
<img width="732" alt="screen shot 2015-11-22 at 10 13 34 pm" src="https://cloud.githubusercontent.com/assets/302945/11323983/7adc9840-9166-11e5-834d-3045b8da9959.png">

**Comment by abo-abo** [comment]
I can't get the second screenshot with the default value of `company-backends`. What are your settings?

**Comment by sooheon** [comment]
`company-backends` is `(company-capf
 (company-dabbrev-code company-gtags company-etags company-keywords)
 company-files company-dabbrev)`, and the extra [annotations](https://github.com/clojure-emacs/cider#completion-annotations) are from cider.

**Comment by cmccloud** [comment]
I noticed the same issue. Removing the various special-lispy commands from the company-begin-commands list seemed to fix the problem. I'm not sure if this will have unintended consequences though. Any thoughts @abo-abo ?

**Comment by abo-abo** [comment]
@cmccloud Cleaning `company-begin-commands` used to lead to `special-lispy-*` commands not triggering company even if not is special. Is it not still the case now?

**Comment by cmccloud** [comment]
@abo-abo company behaves correctly for me so long as `self-insert-command` remains in `company-begin-commands`.

**Comment by abo-abo** [comment]
@cmccloud Thanks for confirming.
@sooheon Please check if this fixes your issue.

**Comment by lionel-** [comment]
@abo-abo works great, thanks!
