### ISSUE TITLE
Clojure: Typing { or [ after ` adds an extra space

### ISSUE THREAD

**Issue by Peeja** [abo-abo/lispy#143]
In Clojure, if I type <kbd>`</kbd> followed by <kbd>{</kbd>, I get an extra space between the characters. The same happens for <kbd>[</kbd>. <kbd>(</kbd> works correctly, as do all three after <kbd>'</kbd>.

That is, the various combinations come out as:

```
'()
`()
'{}
` {}
'[]
` []
```

**Comment by abo-abo** [comment]
Thanks.

**Comment by Peeja** [comment]
You're the best! Thanks!
