### ISSUE TITLE
lispy-tab doesn't work as expected

### ISSUE THREAD

**Issue by vkz** [abo-abo/lispy#145]
`lispy-tab` is a bit confusing. Performed on the outline it does hide it. Unfortunately, it doesn't seem to reverse the action. With no other means of unhiding the outline (like say in `narrow-to-page`) this is really confusing behaviour.

PS: ref section for http://oremacs.com/lispy/#lispy-shifttab suggests looking at `lispy.el` for how to set the `outline-regexp`. I think this code is no longer there.

**Comment by abo-abo** [comment]
> lispy-tab is a bit confusing. Performed on the outline it does hide it. Unfortunately, it doesn't seem to reverse the action.

It should un-hide it if you press <kbd>i</kbd> once more. You can test this with cloning the repository and running `make elisp` in terminal. It will load Emacs with lispy and no other config.

> PS: ref section for http://oremacs.com/lispy/#lispy-shifttab suggests looking at lispy.el for how to set the outline-regexp. I think this code is no longer there.

Thanks, I've updated the docs.
