### ISSUE TITLE
Lispy breaks imenu

### ISSUE THREAD

**Issue by ReneFroger** [abo-abo/lispy#146]
Hi abo-abo!

After installing Lispy, I noticed that <kbd>M-x imenu</kbd> was not working
anymore for Emacs Lisp files with functions.
Maybe I'm wrong, but I tested it with empty Emacs config. This issue arises only
when Lispy is enabled.

My configuration file for Lispy: 

    (use-package lispy
        :defer 3
        :config

        (add-hook 'emacs-lisp-mode-hook (lambda () (lispy-mode 1)))

        (eval-after-load "lispy"
            `(progn
            ;; replace a global binding with own function
            (define-key lispy-mode-map (kbd "C-e") 'my-custom-eol)
            ;; replace a global binding with major-mode's default
            (define-key lispy-mode-map (kbd "C-j") nil)
            ;; replace a local binding
            (lispy-define-key lispy-mode-map "s" 'lispy-down)))
    )

When enabled, the output of <kbd>M-x imenu</kbd> stays empty for .`el` files. 

I get only the error message 

    imenu-unavailable-error: imenu unavailable: "No items suitable for an index found in this buffer"

When googling around, it seems there is no explaination yet on the internet or
none had stumbled this error earlier. 

So I'm wondering why Lispy affects Imenu for Emacs Lisp?

**Comment by abo-abo** [comment]
> So I'm wondering why Lispy affects Imenu for Emacs Lisp?

It seems to be a bug in `semantic-mode`: when turned on, it sets `imenu-create-index-function` to `semantic-create-imenu-index`, which works only when `semantic-mode` is on.  However, when `semantic-mode` is turned off, it doesn't reset `imenu-create-index-function` to a sane value.

You can work-around the bug by enabling `semantic-mode`. You can also report this as an Emacs bug.

Alternatively, you can just rely on <kbd>g</kbd> (`lispy-goto`), which is superior to `imenu`.

**Comment by ReneFroger** [comment]
I found `lispy-goto` too much, I just wanted to have a list of defined functions in the lisp-file without any fuzz. When enabling `semantic-mode`, the imenu is still not working. Are you sure `imenu` is working after enabling `semantic-mode`?

**Comment by zilongshanren** [comment]
@abo-abo  
I also meet this issue now... Doe this bug fixed in Emacs 25?

**Comment by abo-abo** [comment]
Restart Emacs, see if it fixes it.

**Comment by zilongshanren** [comment]
@abo-abo  
Thanks, I will give it a try

**Comment by zilongshanren** [comment]
@abo-abo 
It works like a charm, thanks.
