### ISSUE TITLE
void-variable lh-knight

### ISSUE THREAD

**Issue by tuhdo** [abo-abo/lispy#148]
It occurs with latest `lispy`, when I tried to load with `(require 'lispy)`.

**Comment by abo-abo** [comment]
Please try to reinstall lispy. Such a simple problem would have been caught by Travis CI; I'm testing with emacs from ppa:cassou/emacs and emacs-snapshot from ppa:ubuntu-elisp - both work fine.

If that doesn't work, try installing hydra before installing lispy.

**Comment by tuhdo** [comment]
Installing hydra resolved the issue. Thanks.
