### ISSUE TITLE
Document f and b

### ISSUE THREAD

**Issue by Wilfred** [abo-abo/lispy#149]
Playing with lispy today, it took me a while to find out how to move into a list. I eventually found that it's `f` and `b` for this basic movement.

I think they'd be great candidates for https://github.com/abo-abo/lispy#introduction but I can't see them in the readme at all. http://oremacs.com/lispy/ mentions `f` as `lispy-flow`, but shows `b` as lispy-store-region-and-buffer` (whereas it's bound to `special-lispy-back` as far as I can see).

**Comment by abo-abo** [comment]
Thanks, don't hesitate to comment if you find more badly worded/structured stuff :)
