### ISSUE TITLE
How to insert an actual `[`?

### ISSUE THREAD

**Issue by zilti** [abo-abo/lispy#151]
How can I insert an actual `[`? All it ever does due to the binding is jump back to the beginning of the sexp. Is there a shortcut I've overlooked, or do I have to re-map the command?

**Comment by abo-abo** [comment]
<kbd>{</kbd> inserts `{}` and <kbd>}</kbd> inserts `[]`.

Also <kbd>C-q [</kbd> inserts `[` and <kbd>C-q ]</kbd> inserts `]`.
