### ISSUE TITLE
Syntax highlighting for minibuffer results of lispy-eval?

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#152]
For example, the result of cider-eval-last-sexp when echoed in the minibuffer is syntax highlighted. Is it possible to have this for lispy as well?

**Comment by abo-abo** [comment]
Please give an example of how this is useful.

**Comment by abo-abo** [comment]
Thanks, added. And it does look nice and somehow useful (e.g. highlighted keys in maps). May result in delays when your evaluation result is a megabyte or so.
