### ISSUE TITLE
Some initial comments

### ISSUE THREAD

**Issue by Malabarba** [abo-abo/lispy#155]
Hi Oleh,
As I'm giving lispy a first try, I thought I'd tell you about some obstacles I'm running into. I hope this doesn't come out as whiny, lispy is really spiking my interest. I'm just trying to convey what it's like to try lispy for the first time.

- It's generally bad to override `C-[number]`. I suppose this was motivated by the fact that lispy let's you use just `[number]` for prefix args. However, let's say there's a global command I frequently invoke with `C-1 C-backspace` everywhere else, it's annoying to have to remember that I have to use `1 C-backspace` in this buffer because lispy is active here.
- `lispy-kill-sentence` before a sexp doesn't add it to the kill-ring. I've no idea why a kill command wouldn't use the kill-ring.

**Comment by Malabarba** [comment]
By the way, this is from someone who just did `M-x lispy-mode` and started learning keybinds from the Readme.

**Comment by abo-abo** [comment]
Hi Arthur,

> I hope this doesn't come out as whiny

I'm glad to hear your opinion. Lispy is quite opinionated and therefore inaccessible to many users; maybe more compromises can be made to make it more accessible while keeping the speed and convenience.

> It's generally bad to override C-[number]. I suppose this was motivated by the fact that lispy let's you use just [number] for prefix args. However, let's say there's a global command I frequently invoke with C-1 C-backspace everywhere else, it's annoying to have to remember that I have to use 1 C-backspace in this buffer because lispy is active here.

My thinking at the time was that `M-[number]` is the standard way to pass numeric prefixes, and `C-[number]` is the backup. Since I provide an easy way to add a prefix arg, I felt OK taking over the backup; I still didn't touch `M-[number]`. Still, there's a very easy way to disable the `C-[number]` bindings:

Instead of the default:

    (lispy-set-key-theme '(special lispy c-digits))

Use:

    (lispy-set-key-theme '(special lispy))

Or even (for Paredit fans):

    (lispy-set-key-theme '(special paredit))

> lispy-kill-sentence before a sexp doesn't add it to the kill-ring. I've no idea why a kill command wouldn't use the kill-ring.

I use it for deletion 99% of the time. But it should kill always:

```elisp
(defun lispy-kill-sentence ()
  "Kill until the end of current string or list."
  (interactive)
  (let ((bnd (lispy--bounds-dwim)))
    (if (or (lispy-left-p) (looking-at "\""))
        (kill-region (car bnd) (cdr bnd))
      (setq bnd (or (lispy--bounds-string)
                    (lispy--bounds-list)))
      (kill-region (point) (1- (cdr bnd))))))
```

Can you give a specific situation for which this doesn't work?

**Comment by Malabarba** [comment]
> My thinking at the time was that M-[number] is the standard way to pass numeric prefixes, and C-[number] is the backup. 

I don't know why. :-) C-[number] is much more convenient when the command in question is bound to a C- key.

Anyway, you explain it on the Readme. And the defaults are really the choice of the author anyway.

> Instead of the default:  
> (lispy-set-key-theme '(special lispy c-digits))  
> Use:  
> (lispy-set-key-theme '(special lispy))  

Thanks. I found this in the Readme eventually.

> I use it for deletion 99% of the time. But it should kill always:  
>
>    (defun lispy-kill-sentence ()
>      "Kill until the end of current string or list."
>      (interactive)
>      (let ((bnd (lispy--bounds-dwim)))
>        (if (or (lispy-left-p) (looking-at "\""))
>            (kill-region (car bnd) (cdr bnd))
>          (setq bnd (or (lispy--bounds-string)
>                        (lispy--bounds-list)))
>          (kill-region (point) (1- (cdr bnd))))))
>
> Can you give a specific situation for which this doesn't work?

Maybe it's because I'm on the stable release?
Here's what it looks like to me 

    (defun lispy-kill-sentence ()
      "Kill until the end of current string or list."
      (interactive)
      (if (or (lispy-left-p) (looking-at "\""))
          (lispy-delete 1)
        (let ((bnd
               (or (lispy--bounds-string)
                   (lispy--bounds-list))))
          (kill-region (point) (1- (cdr bnd))))))

**Comment by abo-abo** [comment]
OK, seems I can close this one then. I'll tag a new release that includes the fix soon-ish.
