### ISSUE TITLE
Messages from lispy frequently get replaced by eldoc

### ISSUE THREAD

**Issue by Malabarba** [abo-abo/lispy#156]
- Write something like `(defvar t (let ((x 1)) x))`. 
- Place point before `(let` and hit `xf`. 
- You'll briefly get a message like  `special-lispy-x: ...` which will be quickly replaced by eldoc.

**Comment by abo-abo** [comment]
Thanks. Now both <kbd>e</kbd> and <kbd>x</kbd> don't trigger eldoc. Which isn't too bad, since the most important trigger is <kbd>SPC</kbd>, right?

I never user eldoc myself, an occasional `lispy-arglist-inline` is enough for me.

**Comment by Malabarba** [comment]
> since the most important trigger is SPC, right?

Yeah, I think so.
