### ISSUE TITLE
lispy-colon insert space after when looking at a ( in lisp-mode

### ISSUE THREAD

**Issue by PuercoPop** [abo-abo/lispy#158]
This is highly disruptive when trying to write plists, for example. Is this intended? It works fine in elisp.

**Comment by abo-abo** [comment]
Can you give an example (buffer state1/buffer state2)? Seems to work fine for me.

**Comment by PuercoPop** [comment]
To be more clear, type `(:` I get `( :`. On any buffer in lisp-mode (for common lisp)

**Comment by abo-abo** [comment]
Thanks. You can also turn the extra space completely off if you want; customize `lispy-colon-no-space-regex` to ".".
