### ISSUE TITLE
navigating mixed forms with lispy-up and lispy-down

### ISSUE THREAD

**Issue by drorbemet** [abo-abo/lispy#160]
Maybe after calling lispy-up in a mixed form like this:
(symbol "string" :keyword |(sexp1) (sexp2)
the cursor could move further up to keyword and mark it with a region?
(symbol "string" |```:keyword``` (sexp1) (sexp2)
But when moving back with lispy-down from a region on :keyword, ```(sexp1)``` will be marked with a region.
I'm uncertain, what kind of conventions are the long term goal here.

**Comment by abo-abo** [comment]
Using <kbd>mk</kbd> works fine here. With the current approach, it's possible to traverse only lists if you choose, or both lists and symbols if you choose.  Removing the ability to choose would be bad.

**Comment by drorbemet** [comment]
Ok of course I want to be able to choose, I get it, thanks.
