### ISSUE TITLE
navigating and manipulating mixed pairs

### ISSUE THREAD

**Issue by drorbemet** [abo-abo/lispy#161]
I have difficulties finding the proper idioms for navigating and manipulating forms with mixed pairs like in a (let [symbol1 (sexp1) symbol2 (sexp2)]) or clojure maps {:keyword (value)} and similar structures.

Some operations I recently tried are:
mark one pair with a region
lispy-up one pair
lispy-down one pair

lispy-oneline a form of pairs
lispy-multiline a form of pairs -> putting one pair in one line

**Comment by abo-abo** [comment]
Not sure what the question is here. What exactly do you want to do?

**Comment by drorbemet** [comment]
Yes, ok, I will have to narrow this one down.
