### ISSUE TITLE
undoing multiple raises on a region

### ISSUE THREAD

**Issue by drorbemet** [abo-abo/lispy#163]
Which conventions reguarding lispy-undo could help to be able to undo multiple calls to lispy-raise on a region?
lispy-undo drops the region throwing me of the wagon while trying to restore a lispy-raise

Maybe there is a better workflow that helps to to avoid this situation all together?

**Comment by abo-abo** [comment]
The code relies on Emacs' `undo` command, which doesn't undo the changes in mark position. I'd rather not try to implement my own mechanism that saves the mark after each command.  Do you have a case where losing the region on `undo` is important instead of just annoying?

**Comment by drorbemet** [comment]
Ok, I understand. It's just annoying at first. In the meantime I figured if that should persist I will prefer lispy-teleport and delete the left overs.
