### ISSUE TITLE
lispy-mark with braces and brackets

### ISSUE THREAD

**Issue by drorbemet** [abo-abo/lispy#164]
lispy-mark on |["string with spaces"] -> [```"string with spaces"]|``` includes the closing bracket or brace in the region
and with braces too |{" "} -> {```" "}|```

**Comment by abo-abo** [comment]
You mean `lispy-mark-symbol` here? Because `lispy-mark` seems to work fine.

**Comment by abo-abo** [comment]
Thanks.
