### ISSUE TITLE
wrapping an application on a region with lispy-parens

### ISSUE THREAD

**Issue by drorbemet** [abo-abo/lispy#167]
- this case C-u (
lispy-parens with universal-argument on

 |(sexp) -> (| (sexp))

- versus that case C-u (
lispy-parens with universal-argument on 

```"string"|``` -> |("string") 
but I expected (| "string")

Or would that behaviour collide with other more frequent use cases?

**Comment by abo-abo** [comment]
I don't understand, the current behavior is what you expect:

```elisp
(should (string= (lispy-with "\"string\"|" (kbd "C-u") "(")
                 "(| \"string\")"))
;; => t
```

**Comment by drorbemet** [comment]
I found two surprises, the former and an other one. 
I'll list all cases to check:

a) lispy-parens or (lispy-parens 4)
b) cursor left or cursor right
c) region on or off
d) symbol or form (symbol) with parens
e) linebreak yes or no
f) clojure or emacs lisp

2^6 cases for round parens, braces and brackets

- a) (lispy-parens 4),
  - b) with cursor right
    - c) region on
      - d) symbol
        - e) no linebreak
          - f) clojure:
```"string"|``` -> |("string") but I expected (| "string")
Yes, when region is off, (lispy-parens 4) works,
but when region is on it behaves like lispy-parens
|(wrapping and putting cursor on the left outer).

        - e) linebreak
          - f) clojure:
(linebreak
 |"string") -> Message "Marker does not point anywhere."
     - d) form
       - e) linebreak
         - f) clojure:
(linebreak
 |("string")) -> Message "Marker does not point anywhere."

**Comment by drorbemet** [comment]
Do you understand my description of the two issues?

**Comment by abo-abo** [comment]
Thanks, let me know if all problems are fixed.
