### ISSUE TITLE
calling lispy-parens with universal-argument from emacs-lisp

### ISSUE THREAD

**Issue by drorbemet** [abo-abo/lispy#168]
This seems to be an emacs lisp question.
I didn't find out yet how to pass a universal-argument.
How do I call lispy-parens with universal-argument from emacs-lisp so that I can bind it to a single keybinding?

the following don't work ... 
```
(defun lispy-parens-u ()
  (interactive)
  (lispy-parens t))

(defun lispy-parens-u ()
  (interactive)
  (progn (universal-argument)
         (lispy-parens)))

(defun lispy-parens-u ()
  (interactive)
  (let ((current-prefix-arg t))
    (lispy-parens)))
```

**Comment by abo-abo** [comment]
It's `(lispy-parens 4)`. <kbd>C-u</kbd> translates to `4`, <kbd>C-u C-u</kbd> to `16` etc. See `universal-argument` entry in the Emacs manual.
