### ISSUE TITLE
lispy-mark-symbol from the right side of a string

### ISSUE THREAD

**Issue by drorbemet** [abo-abo/lispy#169]
- calling lispy-mark-symbol on
cursor on the right side of "string" with a space after that
(defn fname "string"| \[\] (symbols in a form))
selects symbols
(defn fname "string" \[\] (```symbols|``` in a form))
instead of "string"
(defn fname ```"string"|``` \[\] (symbols in a form))

- similar
calling lispy-mark-symbol here works as expected
(defn fname ```"string"|```) 
bun when we have a space after the "string" and the cursor like this
(defn fname "string"| )
the enclosing form is selected
```(defn fname "string" )|```
instead of the "string"
(defn fname ```"string"|``` )

**Comment by abo-abo** [comment]
Thanks.
