### ISSUE TITLE
lispy-kill kills siblings on multi-line expression

### ISSUE THREAD

**Issue by thwg** [abo-abo/lispy#171]
This appears to be the same issue as #85, but occurs when the point is not on a parenthesis.  If the point is on an opening paren, the behavior works as expected.

Using <kbd>C-k</kbd> at the point of a quote reader macro, or elsewise prior to the opening paren will kill the rest of the siblings, iff the following expression spans multiple lines.  This seems to be surprising behavior.

Single line behavior (no siblings killed, unless on the same line):

```emacs-lisp
(expr0
 |'(expr1)
  '(expr2)) ;; =>
(expr0
 |
  '(expr2))
```

Multiple line behavior (all following siblings killed):

```emacs-lisp
(expr0
 |'(expr1
    )
  '(expr2)) ;; =>
(expr0
 |)
```

My expected behavior would be to kill the remainder of the expression that started on the current line (to keep parens balanced), but not the rest of the siblings.

**Comment by abo-abo** [comment]
That is a good enough rule, if the parens match on the current line, kill them. Otherwise, kill everything up to the end of parent expression.
Looking for an opening delimiter and trying to kill the found sexp complicates things, especially considering that command is meant for lines, not sexps.

**Comment by thwg** [comment]
Hmm, okay -- makes sense to me.

I'm still converting over to the lispy model from old paredit habits. <kbd>C-,</kbd> seems to be a better fit   for me now when paired with lispy movement.
