### ISSUE TITLE
Some feature not work properly on cljc

### ISSUE THREAD

**Issue by DogLooksGood** [abo-abo/lispy#173]
After `#?`, `(` should not auto insert an space. And the `i` command will delete the whole expression with `#?` in it.

**Comment by abo-abo** [comment]
Can you give some example code? I don't remember what the syntax of `#?` is supposed to be.

**Comment by DogLooksGood** [comment]
#? is used in http://dev.clojure.org/display/design/Reader+Conditionals

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by DogLooksGood** [comment]
Here's another prefix `#?@` need to be fixed.

**Comment by abo-abo** [comment]
What does that do?

**Comment by DogLooksGood** [comment]
`#?@` will expand the content, just like `~@` in macro.
```clojure
(ns test
  #?@(:clj
       [(:require a)
        (:import b)]))
```
will be
```clojure
(ns test
  (:require a)
  (:import b))
```
