### ISSUE TITLE
lispy-tab and lispy-oneline Delete Comments

### ISSUE THREAD

**Issue by noctuid** [abo-abo/lispy#178]
For example, with the point at either of the following positions marked by `|`
```
|;; comment line 1
|;; comment line 2
```
using `lispy-tab` or `lispy-oneline` will result in the following:

```
;; comment line 1|
```

This doesn't happen for `lispy-oneline`if the comments are in an s expression, but the comment lines are swapped. For example,
```
(defun test ()
  |;; comment 1
  ;; comment 2
  ;; comment 3
  (setq baz 0))
```
becomes
```
;; comment 3
;; comment 2
;; comment 1
|(defun test () (setq baz 0))
```

`lispy-tab` still deletes all comment lines but the first resulting in this:
```
(defun test ()
  ;; comment 1|
  (setq baz 0))
```

**Comment by abo-abo** [comment]
Thanks, please check.

**Comment by noctuid** [comment]
Thanks, it's working as expected now.
