### ISSUE TITLE
Make hydra a direct dependency of lispy

### ISSUE THREAD

**Issue by nixmaniack** [abo-abo/lispy#180]
Looked at [this](https://github.com/abo-abo/lispy/blob/240ab2a3642fb9fe3509a1858819dcd6c3378503/lispy.el#L6863-L6874). If hydra is needed why not add it to `Package-Requires`?

I had also faced the issue mentioned here https://github.com/abo-abo/lispy/issues/148 where the comment explains to install hydra, so I think it makes sense to add it as a direct dependency.

**Comment by abo-abo** [comment]
Thanks.

**Comment by nixmaniack** [comment]
Thank you!
