### ISSUE TITLE
lispy-goto-symbol slime error

### ISSUE THREAD

**Issue by dpsutton** [abo-abo/lispy#182]
I am able to call lispy-goto and manually select my tag. However, when i call lispy goto-symbol, I get an error from slime: `The value "random-elt" is not of type CHARACTER.`.

**Comment by abo-abo** [comment]
Works fine for me. For LISP, `lispy-goto-symbol` only calls:

```elisp
(slime-edit-definition (or (thing-at-point 'symbol t)
                           (lispy--current-function)))
```

Few places it can go wrong, likely `slime-edit-definition` doesn't work, but then it's a SLIME issue.

**Comment by dpsutton** [comment]
ah ok. Thanks for looking into it. I'll mark this closed

**Comment by Ambrevar** [comment]
I've got the same issue, and I believe that what @abo-abo reported was only true in a Common Lisp buffer, not in the SLIME REPL.

Indeed, I get the error

> lispy-goto-symbol: no handler for slime-repl-mode in ‘lispy-goto-symbol-alist’

when I call `lispy-goto-symbol` in a SLIME REPL.
This is because the slime-repl-mode (the major mode of the SLIME REPL) is not registered in `lispy-goto-symbol-alist`.

If I add it, it fixes the issue:

```lisp
(setq lispy-goto-symbol-alist '((clojure-mode lispy-goto-symbol-clojure le-clojure)
                                (clojurescript-mode lispy-goto-symbol-clojurescript le-clojure)
                                (scheme-mode lispy-goto-symbol-scheme le-scheme)
                                (lisp-mode lispy-goto-symbol-lisp le-lisp)
                                (slime-repl-mode lispy-goto-symbol-lisp le-lisp)
                                (python-mode lispy-goto-symbol-python le-python)))
```

**Comment by abo-abo** [comment]
@Ambrevar added, thanks.

**Comment by Ambrevar** [comment]
Thanks!

**Comment by Ambrevar** [comment]
Actually we would need to add `slime-mrepl-mode` and `sly-mrepl-mode` ;)

**Comment by abo-abo** [comment]
Added, thanks.

**Comment by Ambrevar** [comment]
Thanks for the prompt fix!
