### ISSUE TITLE
lispy-comment regression

### ISSUE THREAD

**Issue by thwg** [abo-abo/lispy#184]
This change, https://github.com/abo-abo/lispy/commit/d0759a405e932cd7aebfa0855750beba89cf1767, seems to cause `lispy-comment` to no longer work when outside of an sexpr if there are any characters after the point on the line.

```emacs-lisp
|lorem ipsum
```
<kbd>;</kbd> will result in no comment being inserted.

**Comment by abo-abo** [comment]
Thanks.
