### ISSUE TITLE
lispytutor

### ISSUE THREAD

**Issue by seanirby** [abo-abo/lispy#185]
Hey @abo-abo,

I've spent the past couple of days with lispy and I think its excellent.   Nice work.  

All the examples you've included in the README are helpful but I think lispy could really use a tutor file/command like the one that comes with vim, ```vimtutor```.  In case you haven't used it, it just opens a text file thats broken up into sections.  Each section explains related keybindings followed by an exercise and a review.  It usually takes about 15-20 minutes to complete.  I think its the best way to learn a lot of keybindings because you're learning by doing, and you don't have to juggle with a separate window.

Would you open to including this with lispy?  I'd be happy to write a first draft since it would help me learn lispy.   What do you think?

**Comment by abo-abo** [comment]
> I've spent the past couple of days with lispy and I think its excellent. Nice work.

Thanks.

> All the examples you've included in the README are helpful but I think lispy could really use a tutor file/command like the one that comes with vim, vimtutor. 

I had the same idea a while back, but never got to finalizing it.

> Would you open to including this with lispy? I'd be happy to write a first draft since it would help me learn lispy. What do you think?

Have a look at the file I just pushed (I've made it looking at vimtutor). Feel free to improve/extend it and send a PR.

**Comment by seanirby** [comment]
Great, I'll check it out.
