### ISSUE TITLE
tab-always-indent issue when set to 'complete

### ISSUE THREAD

**Issue by drot** [abo-abo/lispy#192]
Hello and thank you for this wonderful package. I have encountered the following problem, when I enable the following option ```(setq tab-always-indent 'complete)``` and have the point at the following place (on the paren): 
```
(use-package foo
  :config
  |)
```
Pressing backspace will of course move the point:
```
(use-package foo
  :config|)
```
But it will also initialize ```completion-at-point``` via ```ivy``` which is annoying and I'm guessing it's not the intended behavior. This is on ```GNU Emacs 25.0.90.1 (i686-pc-linux-gnu, GTK+ Version 3.18.7) of 2016-01-31```

**Comment by abo-abo** [comment]
Thanks. I also read @bbatsov's article and tried the customization; had no idea it was there :)
