### ISSUE TITLE
A feature for jumping to top-level directly?

### ISSUE THREAD

**Issue by DogLooksGood** [abo-abo/lispy#193]
instead of using `]qa` ?

**Comment by abo-abo** [comment]
You can use <kbd>C-M-a</kbd> globally or <kbd>A</kbd> in special.

**Comment by DogLooksGood** [comment]
That's what I looking for, Thx

**Comment by DogLooksGood** [comment]
BTW, <kbd>C-M-a</kbd> or <kbd>A</kbd> work not properly when there's a prefix.
Here's a example:
```clojure
#?(:clj
    (defn hello []))
```
The cursor will jump to `#` instead of `(`.

**Comment by abo-abo** [comment]
`lispy-beginning-of-defun` just calls `beginning-of-defun`, which is where it goes. In Emacs, a defun starts in the first column, in all languages.

If the above code is a common occurrence in Clojure, open a new issue.
