### ISSUE TITLE
Some Suggestions for New Commands

### ISSUE THREAD

**Issue by noctuid** [abo-abo/lispy#197]
I'm putting all of these suggestions in one issue because they are somewhat related.

## Barf to Point
For example, `lispy-barf-to-point` would transform the following

```
(list a| b c)
```

to
```
(list a)| b c
```

I'd think it should also transform this
```
(list a |b c)
```

to this
```
(list a)| b c
```

In words, it would barf to closest sexp before the point.

## Slurp to Max
This command would slurp as far as possible. As an example, it would undo the last command. Here is another example transformation:
```
(list (list)|
      :a 1
      :b 2
      :c 3)
```

to
```
(list (list
       :a 1
       :b 2
       :c 3)|)
```

Unlike the previous command, this could be bound in special. This is basically the behavior of using a high number digit argument with `lispy-slurp` currently, but it would be nice to have an actual command instead of relying on this

## Wrap to EOL
Most often when I'm entering an open paren with text after the point instead of the end of line, I either slurp to the end of line or to the max position (like in the previous example).This command would be similar `lispy-parens`'s wrap except it would wrap all the sexps on the current line following the point instead of just one. Here is an example:

```
(let (|a "foo")
  (message "foo"))
```
would become

```
(let (|(a "foo"))
  (message "foo"))
```

**Comment by abo-abo** [comment]
Thanks for the suggestions. While it doesn't hurt to implement all of them (and at least put them into the Paredit map or something), for the default `lispy-mode` I'm most interested in making the commands composable instead of multiplying their amount.

> Barf to Point

This could be done (eventually) with <kbd>M-j /</kbd> - `lispy-split` and `lispy-splice`.  The thing is that `lispy-splice` tries to get back into special - that may be not the best thing to do.

What do you think of this instead?
```elisp
(should (string=
         (lispy-with "(a) |(b c)" "/")
         "(a) |b c"))
```

> Slurp to Max
> This is basically the behavior of using a high number digit argument with lispy-slurp currently

How about giving a <kbd>0</kbd> digit argument would make the command go until it fails? This way, <kbd>0&gt;</kbd> would do what you want.

> Wrap to EOL

I like this. Since the default wrapping is <kbd>C-u (</kbd>, how about using <kbd>M-2 (</kbd> for the new command?

**Comment by sooheon** [comment]
Since this is inspired by the discussion on parinfer on reddit emacs right now, once these are implemented the addition of a parinfer-map could be cool. Lispy-paren could also wrap-to-eol by default, and `)` would barf to point rather than exit sexp to right.

**Comment by abo-abo** [comment]
I'll have to try this Parinfer when it comes out on MELPA. Currently, I don't see what the fuss is about: it seems about as powerful as `electric-pair-mode`.

**Comment by sooheon** [comment]
The two things I said above are cool default behaviors, imo. All the nonsense about inferring scope by indentation, I agree is useless to someone who doesn't want to manually indent anyway (indentation should be a function of pair management and scope, not the other way around).

**Comment by tuhdo** [comment]
> The two things I said above are cool default behaviors, imo. All the nonsense about inferring scope by indentation, I agree is useless to someone who doesn't want to manually indent anyway (indentation should be a function of pair management and scope, not the other way around).

These things should not depend on each other. You can have both indentation and scope inference. `adjust-parens` can put sexp based on its indentation without having to maually indent.

`parinfer` has the suggested features that we are discussing for adding to `lispy`.

**Comment by noctuid** [comment]
> I like this. Since the default wrapping is C-u (, how about using M-2 ( for the new command?

Since slurping and wrapping are similar, it might make sense to have the same arguments for slurping/wrapping (slurp/wrap a certain number of sexps, slurp/wrap to the eol, slurp/wrap as far as possible).

> I'll have to try this Parinfer when it comes out on MELPA. Currently, I don't see what the fuss is 
about: it seems about as powerful as electric-pair-mode.

It has some nice features that come from the inference (all the features in the two issues I posted). However, its methodology requires the user to manually re-indent to prevent code breakage or to know when breakage will occur and switch to a separate mode. If you're curious, you might want to read [here](https://github.com/noctuid/parinfer-notes#downsides-of-parinfer) where I list parinfer's flaws with some demos. I also have done matching demos for parinfer's features showing they can be done without its flaws [here](https://github.com/noctuid/parinfer-notes#parinfer-examples-done-without-need-for-two-distinct-modes).

> the addition of a parinfer-map could be cool

I agree. Though some of parinfer's behavior makes no sense if you're not considering its inference-based indentation. For example, should backspace before a close paren still slurp as far as possible in parinfer-map?

**Comment by noctuid** [comment]
@abo-abo I previously misunderstood your question about `lispy-splice`. I like your proposed new behavior better than `lispy-splice`'s current behavior. I've been using my own splice command that doesn't move the point after splicing.

As for `barf-to-point`, I think it should put the point in special.

**Comment by abo-abo** [comment]
OK, have a go at it if you like. I don't have much time this week.

**Comment by noctuid** [comment]
What do you think about having the arguments for wrapping and slurping being the same?

| positive arg                    |     0             | negative arg      |
|---------------------------------|:-----------------:|:-----------------:|
| slurp/wrap that number of sexps | slurp/wrap to eol | slurp/wrap to max |

**Comment by abo-abo** [comment]
Sounds good.

**Comment by noctuid** [comment]
Okay, I will try to make another pull request.
