### ISSUE TITLE
Adjust Parens Functionality

### ISSUE THREAD

**Issue by noctuid** [abo-abo/lispy#198]
This is not really a necessary functionality since `adjust-parens.el` works fine with lispy. I do think it might be nice if this functionality was built-in though. For example, smartparens has `sp-indent-adjust-sexp` and `sp-dedent-adjust-sexp`.

As for what this would actually do, `adjust-parens` provides two commands that usually either slurp to the end of line or barf behind the point. Probably a more accurate way to think of it is that the indent function slurps the sexps on the current line (or the point if there are none) into the previous sexp. It is similar to `lispy-up-slurp` except that it behaves differently on an empty line and slurps all the sexps on the line instead of only the current one.

`adjust-parens` describes itself like this:
> This package provides commands for indenting and dedenting Lisp
code such that close parentheses and brackets are automatically
adjusted to be consistent with the new level of indentation.

A simple example for the indent command:
```
(let ((a 1)))
|
```

to
```
(let ((a 1))
  |)
```

to
```
(let ((a 1)
      |))
```

to
```
(let ((a 1
         |)))
```

The dedent command would undo each of these steps one at a time. 

Here is an example where a sexp follows the point:
```
(let ((a 1)
      (b 2))
  |(c 3))
```

to
```
(let ((a 1)
      (b 2)
      |(c 3)))
```

And if there are multiple sexps on the line:
```
(let ((a 1)
      (b 2))
  |(c 3) (d 4))
```

becomes
```
(let ((a 1)
      (b 2)
      |(c 3) (d 4)))
```

As a note, `adjust-parens`'s commands will do nothing if the point is not preceded by the bol and optionally whitespace. Smartparens' commands will act differently. For example, the indent command will have the same result here:
```
(let ((a 1)
      (b 2))
  (c 3) |(d 4))
```

However, it will fail if inside either the `(d 4)` or `(d 4)` sexp. I only use this funcionality at the start of the first sexp on the line, so I can't really say if one or the other is preferable

The dedent command for smartparens will barf either to the point or behind the point (inconsistently it seems).

```
(let ((a 1)
      (b 2))
  (c 3) (|c 5))
```
becomes
```
(let ((a 1)
      (b 2))
  (c 3) (|)c 5)
```

On the other hand
```
(let ((a 1)
      (b 2))
  (c 3) (c| 5))
```

```
(let ((a 1)
      (b 2))
  (c 3) (c| )5)
```

If you do decide to add this functionality to lispy, I think that it would be preferable to either only have it work when `(looking-back "^[[:space:]]*")` or to consistently end after the close paren in special when dedenting in such a situation.

**Comment by abo-abo** [comment]
> A simple example for the indent command:

That's pretty cool, I wasn't aware of this package. Although I've had a similar idea, but in reverse.  Have you tried this command?

> (define-key map (kbd "<return>") 'lispy-alt-line)

It goes from:

    (let ((a 1|)))

to

    (let ((a 1
            |)))

to

    (let ((a 1)
          |))

to

    (let ((a 1))
      |)

to

    (let ((a 1)))
    |

i.e. it lets you append to each list, and re-indents after skipping.  What do you think about putting this command somewhere in the defaults? I'm not sure about binding it to <kbd>RET</kbd> though, the users might find it confusing.

I think this new command, the reverse of `lispy-alt-line` could fit nicely on <kbd>C-DEL</kbd>.

> The dedent command would undo each of these steps one at a time.

This looks exactly like <kbd>ok</kbd>, for a single sexp and for two sexps marked with a region.

> The dedent command for smartparens will barf either to the point or behind the point (inconsistently it seems).

This one looks like <kbd>ol</kbd>.

> If you do decide to add this functionality to lispy, I think that it
> would be preferable to either only have it work when (looking-back
> "^[[:space:]]*") or to consistently end after the close paren in
> special when dedenting in such a situation.

I think <kbd>o</kbd> should maybe be extended to a `hjkl` hydra that manipulates either the cursor or a sexp or a region. The cursor part would handle the `lisp-indent-adjust-parens` part and the sexp/region would handle the `lisp-dedent-adjust-parens` part. The only problem here is that I probably won't like to have to remember to quit the hydra.

**Comment by noctuid** [comment]
I wasn't familiar with that `lispy-alt-line`; that's pretty cool. It's actually pretty similar to the dedent command. It does a little more by acting as enter and also doesn't behave the same when the point is followed by a sexp:
```
(let ((a 1
         |(some sexp))))
```
becomes
```
(let ((a 1
         (some sexp)
         |)))
```
instead of 
```
(let ((a 1)
      |(some sexp)))
```
> I'm not sure about binding it to RET though, the users might find it confusing.

As far as I understand, it behaves differently mostly in situations where you wouldn't normally use RET anyway. It's a better keybinding than I what I currently have for the dedent command (shift tab). This would be unexpected behavior for RET though:

```
(message "hello %s" |name)
```
becomes
```
(message "hello %s" name
              |)
```

Also,
```
(message |"hello %s" name)
```
becomes
```
(message "hello %s"
         |name)
```
Is this the intended behavior?

> This looks exactly like ok

Yep, my initial comparison was to `lispy-up-slurp`, but it doesn't behave as the indent command does if you are not in special (it has strange behavior).

> This one looks like ol.

`lispy-moves-right` is also similar dedent command for what I've tried, but again it behaves weird outside of special.

As for the hydra, I'm not sure I understand exactly what you are proposing. By default, adjust-parens binds tab to the indent command and shift tab to the dedent command. I use aggressive indent so the tab binding isn't a problem for me, but these probably shouldn't be the lispy defaults.

**Comment by abo-abo** [comment]
> Is this the intended behavior?

The one with `message` wasn't, but the other one was. I use `lispy-alt-line` (bound to <kbd>RET</kbd>) when entering new code.
Example: 

```elisp
(should (string= (lispy-with-clojure "|"
                                       "(let}baz}a b c"
                                       (lispy-alt-line)
                                       (lispy-alt-line)
                                       "foo(bar a"
                                       (lispy-alt-line)
                                       "(bar b"
                                       (lispy-alt-line)
                                       (lispy-alt-line)
                                       (lispy-alt-line)
                                       (lispy-alt-line)
                                       "(")
                   "(let [baz [a b c]\n      foo (bar a\n               (bar b))]\n  (|))"))
```

The command is supposed to go through the reasonable places where I might want to add new code, and make some space.  And then if I skip that space, put it back to normal.

**Comment by noctuid** [comment]
I think the only case where `ok`/`lispy-up-slurp` is lacking the behavior of the indent command is when the point is not before any sexp. I think it would make sense to make it work the same in that situation and maybe provide an alias to make it more obvious that it's the same as the smartparens and adjust-parens equivalents.

As for `ol`/`lispy-move-right`, it is only the same when the sexp at point is at the end of a sexp. Otherwise the equiavlent is to mark the current sexp, slurp as far as possible, and then use `ol`. I think it would be nice to have a dedicated/separate dedent command. What do you think?

**Comment by abo-abo** [comment]
Yes, let's start with a dedicated dedent command. Then see if we can integrate it somewhere with a binding.
