### ISSUE TITLE
Consider allowing alternate barf/slurp bindings

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#199]
Currently, `<` and `>` in special barf and slurp as appropriate to the command name. As a quirk, the arrow directions match with the movement of the closing pair, but not with the opening pair. An alternate style, where `<` and `>` alternate barfing and slurping depending on whether it is called from opening special or closing special, like [evil-cleverparens](https://github.com/luxbock/evil-cleverparens#slurping-and-barfing), would be nice, as it would be easy to remember that at special, `<>` moves the delimiter at point in the indicated direction.

**Comment by abo-abo** [comment]
I disagree here:

- `>` denotes the "greater" mathematical sign - use it when you want to make your list size greater.
- `<` denotes the "lesser" mathematical sign - use it when you want to make your list size lesser.

These commands are designed with simplicity in mind: you don't have to think if you're on the open delimiter or closing delimiter, you just have to know if you want to grow or shirk your list.

**Comment by sooheon** [comment]
Ah I had not thought of them as "greater" "lesser" signs, that's a nice mnemonic.

> you don't have to think if you're on the open delimiter or closing delimiter, you just have to know if you want to grow or shirk your list.

Still, one would have to consider the direction they would like the grow the list, or to shrink it away from? I think you still need to be aware whether you are at opening or closing parens.

At least for me, where my cursor is is usually clear enough, and relative position and direction are very perceptual concepts, requiring almost no thought. I can simply think, wherever my cursor happens to be: "as long as I'm in special, `<` will move that delimiter in that direction on the screen". It's very direct, and allows for the kind of distraction minimizing flow that lispy delivers so well in general.

**Comment by abo-abo** [comment]
As you prefer. For me, this would be confusing:

- `>` - slurp when from the right, but barf when from the left
- `<` - barf when from the right, but slurp when from the left

Feel free to PR with replacements, `lispy-slurp-or-barf-left` and `lispy-slurp-or-barf-right`, I guess.  Or just use `lispy-mode-map-evilcp`.
