### ISSUE TITLE
lispy knight requires hydra to be loaded

### ISSUE THREAD

**Issue by benswift** [abo-abo/lispy#201]
When using lispy but not hydra (i.e. no `(require 'hydra)` in my init file) if I try and use the lispy knight hydra I get the message
```
lh-knight/body: Symbol's function definition is void: hydra-default-pre
```
Calling `(require 'hydra)` fixes the problem.

Obviously this is a very minor issue, but is there a reason it isn't either done automatically or the error handled more gracefully (e.g. as is done for the multiple cursors interaction stuff). I guess it might just be because most lispy users are hydra users anyway?

**Comment by abo-abo** [comment]
Thanks. The automated tests didn't catch this problem.

**Comment by benswift** [comment]
No worries mate.
