### ISSUE TITLE
adding lispy support to other lisp modes

### ISSUE THREAD

**Issue by benswift** [abo-abo/lispy#203]
Currently, lispy has support for elisp, clojure and scheme. What's the best way to add support for a new lisp? Most of the navigation and editing commands work out of the box (yay s-expressions) and I can write equivalent versions of e.g. `lispy-eval` and `lispy-follow`, but how should I plug them in to lispy-mode?

I guess there are two options:
1. keep adding the mode-specific stuff to `lispy.el`, as is currently being done
2. implement them elsewhere (e.g. in the other lisp's major mode, or in my `.emacs`) and then hook them into lispy-mode, perhaps through advices?

I guess my question is more about the future - are there any plans for a plugin-style interface, or should I just duct-tape the support in through advices and `eval-after-load` and whatnot? I'm happy to do either, open to sharing the updates, but wanted to check what the general shape of things is before I dove in.

**Comment by abo-abo** [comment]
You're right, you need to plug into `lispy--eval` and into `lispy-goto-symbol`.

Currently, `lispy--eval` works like this: 

1. Dispatch on the mode, ensure that the corresponding file (like `le-clojure` or `le-python`) is loaded. This ensures that the user doesn't pay any overhead for REPLs that he's not using. And there aren't any restrictions on `require` in e.g. `le-clojure`: anything can be required there, even if it takes a long time to load.
2. Forward to the appropriate eval function, e.g. `lispy--eval-scheme`.

Once you implement e.g. `lispy--eval-julia`, things like `lispy-eval`, `lispy-eval-and-insert`, `lispy-eval-and-comment`, `lispy-eval-and-replace` will work automatically.

Same goes for `lispy-goto-symbol`.

Then there are also custom handlers for `lispy-debug-step-in`, if you're into that.  I think that command is great. Currently, there's a version for Elisp, Clojure and Python. Unfortunately, not all LISPs are self-reflective enough to make an implementation of this command possible.

> I guess my question is more about the future - are there any plans for a plugin-style interface, or should I just duct-tape the support in through advices and eval-after-load and whatnot? I'm happy to do either, open to sharing the updates, but wanted to check what the general shape of things is before I dove in.

I prefer to duct-tape things while I can get away with it. Once a pattern is repeated enough times or the functions take up more than a screen it's time to refactor:)

> keep adding the mode-specific stuff to lispy.el, as is currently being done

This is the way to go I think. There's so many ways things could break, it's best to keep them in one place and preferably test everything with ERT.

**Comment by benswift** [comment]
Ok, great. I'm happy for you to close this for the moment, and I'll try
putting something together for my obscure hobby lisp when I get a chance
and if it turns out to be useful I'll let you know :)

**Comment by liuxueyang** [comment]
@abo-abo Why the `xf` command is not working when I use it in common lisp code. It is not supported for common lisp? When I run `xf`, there is 

>   "  special-lispy-x: lisp-mode isn't currently supported"

in the status line.

Thank you. :)

**Comment by abo-abo** [comment]
@liuxueyang It's not possible to implement <kbd>xf</kbd> for Common Lisp because it doesn't feature the required level of introspection in the spec.

Elisp example:

```elisp
(defun square (x)
  (* x x))
;; => square


(symbol-function 'square)
;; =>
;; (lambda (x) (* x x))
```

Unless there's some cool library that implements a `symbol-function` equivalent for Common Lisp, I can't make a version of <kbd>xf</kbd>.  Last time I checked, SLIME didn't have this functionality as well.

**Comment by liuxueyang** [comment]
@abo-abo Got it. Thank you :+1:
