### ISSUE TITLE
[error] void-function ivy-set-occur

### ISSUE THREAD

**Issue by rprimus** [abo-abo/lispy#205]
Sun Feb 21 17:50:49 GMT 2016

Info:
```
ProductName: Mac OS X
ProductVersion: 10.11.4
BuildVersion: 15E39d
emacs: GNU Emacs 24.5.1 (x86_64-apple-darwin15.4.0, NS apple-appkit-1404.41) of 2016-01-16
lispy ver: lispy-20160218.232
```
Recently, when attempting to start lispy ```(lispy-mode 1)```,  the following trace is produced:

```elisp
Debugger entered--Lisp error: (void-function ivy-set-occur)
  (ivy-set-occur (quote swiper) (quote swiper-occur))
  #<subr require>(swiper nil nil)
  ad-Advice-require(#<subr require> swiper)
  apply(ad-Advice-require #<subr require> swiper)
  require(swiper)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\300\304!\210\300\305!\210\300\306!\210\300\307!\210\300\310!\210\300\311!\210\300\312!\210\300\313!\210\300\314!\210\300\315!\210\300\316!\210\300\\315!\210\300\316!\210\300\317!\210\300\320!\210\300\321!\210\322\323\324\325\326\327\330\331&^G\207" [require lispy-tags help-fns edebug ediff ediff-util eldoc etags outline semantic semantic/db semantic/bovine/el avy newcomment lispy-inline iedit delsel swiper custom-declare-group  lispy nil "List navigation and editing for the Lisp family." :group bindings :prefix "lispy-"] 8)
  (lispy-mode 1)
  eval((lispy-mode 1) nil)
  eval-defun(nil)
  #<subr call-interactively>(eval-defun nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> eval-defun nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (eval-defun nil nil))
  call-interactively(eval-defun nil nil)
  command-execute(eval-defun)
```

```swiper-20160219.951``` is installed and I can see the ```define ivy-set-occur``` at line 2634 in ```ivy.el```

```(require 'ivy)``` is set on line 41 of ```swiper.el``` and 
the call to ```ivy-set-occur``` is on line 343 of  ```swiper.el```.

Is there something I'm missing?

**Comment by rprimus** [comment]
Sun Feb 21 18:57:11 GMT 2016

**UPDATE**

I also had ```ivy-20150410.927``` installed (which also provided ```ivy```).
Upon removing this package,  all appears well again.

1.  Is this package still required for anything,  or has it been deprecated?

**Comment by abo-abo** [comment]
> Is this package still required for anything or has it been deprecated?

Lispy depends on `swiper 0.7.0`, or higher version (like any MELPA version). It appears that you had a small glitch - these may happen sometimes with package dependencies. Updating all packages and restarting Emacs usually fixes it.

**Comment by rprimus** [comment]
Sun Feb 21 19:46:57 GMT 2016

I update daily.   It appears that the package system does not remove deprecated dependencies (like 
```ivy-20150410.927```.

Thanks for quick response!
