### ISSUE TITLE
Let lispy-special-x bindings be more discoverable

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#218]
It's helpful how bindings under `C-4` are shown with describe-bindings (for `which-key` or `guide-key`). But the `lispy-special-x` equivalents aren't visible, and only show `x-` in the minibuffer. It'd be nice to have them show potential keys in the same way.

**Comment by abo-abo** [comment]
<kbd>x C-h</kbd> or <kbd>C-4 C-h</kbd> work.

**Comment by sooheon** [comment]
For some reason, using `which-key` package, the bindings under `C-4` are shown automatically, while the bindings under `x` are only shown after manually pressing C-h. @justbur, do you know why this is? relevant code is around here and below https://github.com/abo-abo/lispy/blob/master/lispy.el#L4629

**Comment by justbur** [comment]
There are a couple of exceptions but which-key waits for an incomplete key sequence and then shows all of the possible keys that follow it. Commands that "manually" look up the next command using a read function don't fit this category. That's what lispy-x does which is why there is no popup. I don't know enough about the design of lispy but if lispy-x were a prefix command it would work with which-key

**Comment by justbur** [comment]
@abo-abo try this

```elisp
(defvar lispy-mode-map-x
  (let ((map (make-sparse-keymap)))
    (define-key map "xa" nil)
    (define-key map "xb" 'lispy-bind-variable)
    (define-key map "xc" 'lispy-to-cond)
    (define-key map "xd" 'lispy-to-defun)
    (define-key map "xe" 'lispy-edebug)
    (define-key map "xf" 'lispy-flatten)
    (define-key map "xg" nil)
    (define-key map "xh" 'lispy-describe)
    (define-key map "xi" 'lispy-to-ifs)
    (define-key map "xj" 'lispy-debug-step-in)
    (define-key map "xk" 'lispy-extract-block)
    (define-key map "xl" 'lispy-to-lambda)
    (define-key map "xm" 'lispy-cursor-ace)
    (define-key map "xn" nil)
    (define-key map "xo" nil)
    (define-key map "xp" nil)
    (define-key map "xq" nil)
    (define-key map "xr" 'lispy-eval-and-replace)
    (define-key map "xs" 'save-buffer)
    (define-key map "xt" nil)
    (define-key map "xu" 'lispy-unbind-variable)
    (define-key map "xv" 'lispy-view-test)
    (define-key map "xw" nil)
    (define-key map "xx" nil)
    (define-key map "xy" nil)
    (define-key map "xz" nil)
    (define-key map "xB" 'lispy-store-region-and-buffer)
    (define-key map "xR" 'lispy-reverse)
    (define-key map (concat "x" (char-to-string help-char))
      'lispy-describe-bindings-C-4)
    map))

(defun lispy-x ()
  "Forward to `lispy-mode-map-x'."
  (interactive)
  (set-transient-map lispy-mode-map-x)
  (setq unread-command-events (list (cons t ?x))))
```

**Comment by abo-abo** [comment]
Thanks.

**Comment by sooheon** [comment]
@justbur @abo-abo I think this caused a regression: `x` gives a which-key popup as desired, but `C-4` does not present subbindings directly. I'm required to press `C-4 x` then foo to access commands previously directly under `C-4`.

**Comment by abo-abo** [comment]
@sooheon You're right, should be fixed now.

**Comment by sooheon** [comment]
Thanks!
