### ISSUE TITLE
lispy no longer plays well with cider--debug-mode

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#247]
previously, entering cider-debug with lispy would still allow all the debugging keys to work, but on latest release of both, cider keys are not working.

To replicate, jack-in to a clojure buffer with only vanilla lispy-mode and cider-mode enabled.

**Comment by abo-abo** [comment]
Sorry, but I can't be chasing the constantly changing CIDER trunk. You can use the stable version from either MELPA stable or Git, until the new release comes out.

Hopefully by that time either the error fixes itself or I'll fix it.

**Comment by sooheon** [comment]
Yep, this issue was user error.

**Comment by abo-abo** [comment]
Ah OK :)
