### ISSUE TITLE
Lispy and electric-quote-mode conflict

### ISSUE THREAD

**Issue by drot** [abo-abo/lispy#248]
`GNU Emacs 25.0.92.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.18.9) of 2016-03-27`

After enabling the new `electric-quote-mode` in `emacs-25` requoting (replacing \` with ‘) won't work anymore in comments where `lispy-mode` is enabled.

**Comment by abo-abo** [comment]
This is a generic Emacs minor mode conflict, where the latter enabled mode has priority for the conflicted binding.  Just toggle `lispy-mode` and it will take priority again.

**Comment by drot** [comment]
Guess I can always disable the `lispy-backtick` keybinding. Thanks for the pointer.
