### ISSUE TITLE
Issue using lispy--eval-hy sometimes locks up emacs

### ISSUE THREAD

**Issue by jkitchin** [abo-abo/lispy#256]
Using this code I want to setup an eldoc function for hy code. 

Sometimes it works, but often emacs hangs with this message Blocking call to accept-process-output with quit inhibited!! in the minibuffer.  I can usually C-g to stop it, and sometimes the message comes back and sometimes it works as expected. After that I still get that message in the minibuffer for each time the function is called and it is replaced by the eldoc message intended. Any idea what is causing that?

E.g in a hy file containing

(defn )
        ^    cursor here should show u'test: defn' in the minibuffer.
```
;; load version of lispy with hy support.
(add-to-list 'load-path (expand-file-name "lispy" starter-kit-dir))
(require 'lispy)

(defun hy-eldoc-function ()
  "`eldoc-documentation-function' for hy."
  (lispy--eval-hy (format "\"test: %s\""
			  (lispy--current-function))))

(defun hy-setup ()
  "Setup hy-mode."
  (lispy-mode 1)
  (set (make-local-variable
	'eldoc-documentation-function)
       'hy-eldoc-function))

;; * Use lispy and turn on my eldoc function
(add-hook 'hy-mode-hook 'hy-setup)
```

**Comment by abo-abo** [comment]
> Any idea what is causing that?

No clue, especially since I can't reproduce it. After a minute going through a buffer of ~20 expressions, everything still works.

I would suggest that you look into `*hy*` buffer to see what's wrong and if you can still eval stuff.  Then edebug `lispy--eval-hy`.

Finally, it could be a version issue. I'm using Emacs 25.0.90.1 on GNU/Linux and Hy 0.11.1.

**Comment by jkitchin** [comment]
Ok, thanks for confirming it works for you. It might be an emacs issue. the *hy* buffer is still functional, although it isn't always at => which may be the issue. I will try a few things out. It sounds like an issue on my end though, so I will close this.

**Comment by abo-abo** [comment]
> although it isn't always at => which may be the issue.

Very likely this is the reason. Let me know if you can reliably reproduce this situation.

**Comment by jkitchin** [comment]
This code:

```(progn
  (lispy--hy-proc)
  (lispy--eval-hy "\"1 test\"")
  (lispy--eval-hy "(import hy)")
  (lispy--eval-hy "\"2 test\"") 
  (message "done with hy repl")
  (switch-to-buffer-other-window "*hy*"))
```

Leads to this in*hy*

```
=> => u'2 test'
=> => 
```

Pressing enter gets me to
```
=>
```

The problem seems to come from lines that import or require things.  I can't tell if this is what is causing the issue but it isn't what I expected.

**Comment by abo-abo** [comment]
Here is the state of `*hy*` after your sequence. It's still OK:

    hy 0.11.1 using CPython(default) 2.7.6 on Linux
    =>
