### ISSUE TITLE
common lisp: some strange happend when use `e` command to evaluate form

### ISSUE THREAD

**Issue by liuxueyang** [abo-abo/lispy#257]
It's hard to explain that by code. Please refer to this video on [Youtube](https://youtu.be/6_30xwEn9co).

Besides, there is a [code paste](http://paste.lisp.org/display/313474)

Thank your for your plugin. It's excellent.

**Comment by abo-abo** [comment]
Thanks, the output should be `11` now, instead of `1`.

**Comment by liuxueyang** [comment]
Can I update lispy through elpa? I find that version on elpa is not the same as on github.

**Comment by abo-abo** [comment]
Lispy is on MELPA. And the versions are current up to half a day (the update is slow, since MELPA has thousands of packages to handle).

You can see which packages are being updated in MELPA at https://twitter.com/melpa_emacs. Today's update should land there in a few hours.

**Comment by liuxueyang** [comment]
Got it. 
Thank you very much!
