### ISSUE TITLE
Add a option to disable auto convert ' to (quote ...)

### ISSUE THREAD

**Issue by DogLooksGood** [abo-abo/lispy#258]
It's not a common behavior maybe?

**Comment by abo-abo** [comment]
`'` and `(quote)` should be separate. If there's any conversion happening, it's a bug that should be reported.

**Comment by DogLooksGood** [comment]
Sorry,
After some work to find the shortest expression that can reproduce the problem, 
I find the problem will happen only when I try to indent some code that contains:
```clojure
'[a .
  b]
```
A quoted vector that contains a dot and be written in multiple lines.

Not a common usage.

**Comment by abo-abo** [comment]
If you want, you can submit another patch to `lispy--read` for this. The expression you mention isn't valid Elisp, I don't even know which LISP dialect you're using.

**Comment by DogLooksGood** [comment]
```clojure
(d/q '[:find ?e .
         :where [?e :some/attr]]
  (d/db conn))
```
In this situation, the query expression for datomic.
Not a common usage.
