### ISSUE TITLE
lispy-mode does not work with edebug's SPC binding

### ISSUE THREAD

**Issue by Wilfred** [abo-abo/lispy#260]
Normally, SPC in edebug calls `edebug-step-mode`, a really useful edebug command. If edebug is active in that buffer, Emacs attempts to call `lispy-space`. However, since the buffer is read-only, nothing happens.

I'd expect edebug commands when edebugging.

To reproduce, create an elisp buffer with lispy-mode enabled. Enter the following code:

```lisp
(defun foo (x)
  (+ x 1))

(foo 2)
```

Then `C-u M-x edebug-eval-defun` on the definition of foo. Put point after `(foo 2)` and run `M-x eval-last-sexp`.

This drops you into edebug in `foo`. Observe that SPC does not work, but other commands, like `c`, do.

**Comment by abo-abo** [comment]
<kbd>SPC</kbd> works fine for me in `edebug`. See the definition of `lispy-space`:

    ((bound-and-true-p edebug-active)
             (edebug-step-mode))

**Comment by Wilfred** [comment]
You're absolutely right, sorry for the noise. I was on lispy-20160330.132 which did not have those lines.
