### ISSUE TITLE
Keybinding conflict with macrostep

### ISSUE THREAD

**Issue by Wilfred** [abo-abo/lispy#261]
`macrostep-expand` enters macrostep-mode. `q` will normally exit macrostep-mode, but if lispy-mode is enabled then `q` is intercepted and users cannot easily leave macrostep-mode.

**Comment by abo-abo** [comment]
See if using `lispy-compat` variable fixes it.

**Comment by drot** [comment]
Works fine here with latest lispy (blank init file, added MELPA and installed lispy and macroexpand, enabled lispy mode, `macrostep-expand` works normally.)

**Comment by Wilfred** [comment]
Agreed, I've upgraded lispy and I'm no longer seeing this. Sorry for the noise.

**Comment by Wilfred** [comment]
I'm sometimes, but not always, seeing this. Setting `lispy-compat` seems to have fixed it reliably.
