### ISSUE TITLE
let lispy--action-jump call reposition-buffer or recenter 

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#265]
It's debatable whether it should reposition-buffer or recenter it, but as it is, jumping to location with lispy-goto or `M-.` too often puts the function definition at the very bottom, with most of it cut off. For example, try calling lispy-goto, `C-o` and toggle calling on, then `jjjjjjj`.

**Comment by abo-abo** [comment]
> lispy-goto or M-.

Let's try to not aggregate different issues into a single ticket. `lispy-goto` and `lispy-goto-symbol` use different code. So issues with them should be reported separately.

If we're talking about `lispy-goto-symbol`, it already has `recenter` built-in via `find-function`, `find-variable` etc, but only for Elisp. If you need it for other dialects, open a separate issue.

I'm adding a `(recenter find-function-recenter-line)` to `lispy--action-jump`. Let's see how it goes.
