### ISSUE TITLE
lispy-describe-inline should first attempt to show both point and overlay

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#266]
For example, when the function call is on the second line of the window, C-1 shows the overlay and pushes down text. However, if the function call is on the very first line, or out of screen, it makes no attempt to recenter to bring overlay into view. What I think should happen is this:

1. When point and function call are too far apart to show on screen at the same time, it should bring up the Help window, as it does when docstrings are too long. 

2. In the other case where point is close to the function call but the latter just happens to be offscreen, it should try to scroll enough to bring both into view.

**Comment by abo-abo** [comment]
Thanks, I've fixed the most common issue. Feel free to PR with a fix for the other stuff.
