### ISSUE TITLE
lispy-move-up within square brackets and braces

### ISSUE THREAD

**Issue by drorbemet** [abo-abo/lispy#267]
Are the following cases reproducable in clojure files?
I could reproduce it taking a bare prelude preconfig and lispy-mode.

Applying lispy-move-up and sometimes lispy-move-up on a region of one or more symbols or an sexp breaks the balance of parens by deleting parens instead of stopping at the end of the form.
After that call lispy-undo is broken too.
It doesn't seem to matter at which side of the region or form the point | is.
I marked one or two Symbols. I didn't mark sexps.
It doesn't seem to matter if one or more symbols ar part of the region.
I moved the outer left symbol to the left. The other symbols are just there for readability.

```
(|() some symbol)
(|() some symbol)
```

```
{~region| symbol}
|region} some}
```

```
{() some symbol}
|(){ some symbol}
```

```
[~region| symbol]
|region] symbol]
```

```
[|() some symbol]
|()]  some symbol]
```

Maybe there are more simmilar cases.

**Comment by abo-abo** [comment]
Could you please edit your examples according to lispy's testing convention? Because it's hard to see where the region is.

The convection is: `|` is the point, `~` is the mark.

**Comment by drorbemet** [comment]
I am unsure about how to use ~ to signal the region, but the region didn't seem to be relevant in my tests untill now. I should write tests ... hm.

**Comment by abo-abo** [comment]
I'm getting the correct behavior for the first test:

```elisp
(should (string=
         (lispy-with-clojure "{~region| symbol}" "s")
         "{symbol ~region|}"))
;; => t
```

**Comment by abo-abo** [comment]
Ah, you meant <kbd>w</kbd>? Yes, I can reproduce that bug. I'll try to fix it when I get some time.

**Comment by abo-abo** [comment]
Thanks for the report. Let me know if there's still something to be fixed.

**Comment by drorbemet** [comment]
Thank you. Yes I will let you know.
