### ISSUE TITLE
SPC does not expand an abbrev when lispy-mode is enabled

### ISSUE THREAD

**Issue by sewkokot** [abo-abo/lispy#280]
For some time now I see a strange behaviour that when lispy-mode is enabled, pressing SPC key does not make the expansion of an abbrev. The expansion happens when I press additionally RET after SPC. Naturally switching-off lispy-mode removes this issue and an abbrev expands after hitting SPC bar. Any idea why this happens?

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by sewkokot** [comment]
Tested, it works! Thank you for the quick reply and fix!
