### ISSUE TITLE
lispy-backward-delete from line below a comment should not delete comment immediately

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#281]
Given:

```
(foo
 ;; comment
 |)
```

lispy-backward-delete should first join line with cursor to above line.

**Comment by abo-abo** [comment]
I don't think that would be the right behavior: it would break the paren structure.

The following is already covered and is probably enough:

    (foo
     ;; comment
     |
     )
     
The test case that you mention works correctly: from that point, the comment is an atom. And atoms are deleted with <kbd>DEL</kbd>, e.g. `((foo) (bar)|)`.

**Comment by sooheon** [comment]
Ah that makes sense; I didn't think through that the paren would be commented out too. Thanks!
