### ISSUE TITLE
Loading lispy breaks imenu

### ISSUE THREAD

**Issue by Wilfred** [abo-abo/lispy#283]
I've noticed that loading lispy breaks imenu in both elisp buffers and in some other languages too (e.g. Python).

After loading lispy, elisp and python buffers have `imenu-create-index-function` set to `'semantic-create-imenu-index`. If the user doesn't have semantic mode enabled, then `M-x imenu` offers no options.

The problem is this line:

```lisp
(require 'semantic/bovine/el)
```

Which contains the following line:

```lisp
(defvar-mode-local emacs-lisp-mode imenu-create-index-function
  'semantic-create-imenu-index)
```

As a result, opening any elisp or python file cannot use imenu unless I manually set `imenu-create-index-function`.

What do you think? It's a rather nasty gotcha, but I'm not sure whether it's even lispy's fault.

**Comment by abo-abo** [comment]
> (require 'semantic/bovine/el)

This line was move from the top level to `lispy--fetch-tags` some time ago, to fix the exact issue that you mention.

I don't remember right now, but I'm pretty sure that that require is essential to parts of `lispy-goto` functionality. On the other hand, if you only `(require 'lispy)` and never use `lispy-goto`, `(require 'semantic/bovine/el)` will never be called and won't mess up imenu.

> What do you think? It's a rather nasty gotcha, but I'm not sure whether it's even lispy's fault.

It's not lispy's fault. It's a bug in semantic. I suggest to report it with M-x report-emacs-bug.

**Comment by Wilfred** [comment]
Thanks, that's really helpful. I have a tentative workaround:

```lisp
(remove-hook 'python-mode-hook #'wisent-python-default-setup)

(defun wh/elisp-imenu-reset ()
  (setq imenu-create-index-function #'imenu-default-create-index-function))

(add-hook 'emacs-lisp-mode-hook #'wh/elisp-imenu-reset)
```

I'm using lispy-20160428.650 so even if I don't use lispy-goto I hit this. You fix bugs too fast! :)

I'll upgrade lispy and follow up upstream.
