### ISSUE TITLE
lispy-eval not compatible with Python3

### ISSUE THREAD

**Issue by jkitchin** [abo-abo/lispy#285]
If I put my cursor on the # in the heading below and press e I get an error

```
#* heading:
y = 5 + 6
# =>   File "<stdin>", line 1
#        y = 5 + 6; print repr(y)
#                            ^
#    SyntaxError: invalid syntax
```

This needs to be: print(repr(y)) to be compatible with Python3

In line 106 of le-python.el.

**Comment by abo-abo** [comment]
I'm not super-experienced with Python. How could this be solved portably, so that both Python2 and Python3 could be used?

**Comment by jkitchin** [comment]
That should work for Python 2.7 and 3 portably I think. print() works all the way back to 2.5 on my Mac. 
There might be some subtle differences in what gets printed out on older versions:

jkitchin@Johns-MacBook-Air { ~/tests/scimax }$ python2.5
Python 2.5.6 (r256:Unversioned directory, Mar  9 2014, 22:15:03) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> print(5)
5
>>> print(5,)
(5,)
>>> ^D
jkitchin@Johns-MacBook-Air { ~/tests/scimax }$ python
Python 3.5.1 |Anaconda 4.0.0 (x86_64)| (default, Dec  7 2015, 11:24:55) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> print(5)
5
>>> print(5,)
5
>>> 

See: http://python3porting.com/noconv.html#supporting-the-print-function

**Comment by abo-abo** [comment]
print(x) seems to work fine, thanks for the suggestion.
