### ISSUE TITLE
What's the equivalent to the following 4 functions in  paredit? 

### ISSUE THREAD

**Issue by zilongshanren** [abo-abo/lispy#290]
I have read the lispy docs, but I can't figure it out, any help could be appreciated, thanks.

```lisp
paredit-splice-sexp-killing-backward)
paredit-wrap-round)
paredit-wrap-square)
paredit-wrap-curly)
```

**Comment by abo-abo** [comment]
> paredit-wrap-round
> paredit-wrap-square
> paredit-wrap-curly

To wrap, simply add a prefix arg before an insertion function, e.g. `2(`, `2{`, `2[`.

> paredit-splice-sexp-killing-backward

It's <kbd>R</kbd>. You can also mark with a region and press <kbd>r</kbd> - a bit slower, but more flexible.

**Comment by zilongshanren** [comment]
@abo-abo

Thanks very much ❤️
