### ISSUE TITLE
lispy-parens-preceding-syntax-alist doesn't respect clojurec-mode

### ISSUE THREAD

**Issue by zilongshanren** [abo-abo/lispy#292]
When reuse code in both clj & cljs, I will define the .cljc file which uses the cljurec-mode.

When I press `#` and `(`, it will insert a space between the `#` and `(` which is very annoying.

How could I get ride of this behavior? Thanks.

**Comment by zilongshanren** [comment]
I have figured it out by adding the following sexp to my .init file.

```
  (push '(clojurec-mode . ("[`'~@]+" "#" "#\\?@?")) lispy-parens-preceding-syntax-alist)
```

Hope it will be fixed in the upstream, thanks.

**Comment by abo-abo** [comment]
Thanks, please test.
