### ISSUE TITLE
how to delete one single parentheiss

### ISSUE THREAD

**Issue by seudut** [abo-abo/lispy#293]
lispy mode is very convenient, but I encounter a problem to delete one single parenthesis. For example, sometimes I copy some lisp code into my emacs init file, but I find the parenthesis are mismatching,  such as 

    (defun foo () (xxxxx))))

there are two redundant `)` in the end. how I can delete these parenthesis, since `C-d` and `DEL`, which  are bound to `lispy-delete` and `lispy-delete-backward` don't work in this case.

**Comment by abo-abo** [comment]
Mark the parens that you want to delete with a region and either <kbd>C-w</kbd> or <kbd>DEL</kbd> or <kbd>C-d</kbd>.  All of those commands ignore the parens when the region is active.

**Comment by seudut** [comment]
Thanks abo-abo for you quick response.
I just now though about another solution, to unset the `C-d` after the lispy mode is loaded, make it use the default global binding `delete-char`

     (eval-after-load "lispy"
        `(progn
           (define-key lispy-mode-map (kbd "C-d") nil)))

but it does't work. after load, it still maps to `lispy-delete`, do you know why?

**Comment by abo-abo** [comment]
You can use:

    (define-key lispy-mode-map-lispy (kbd "C-d") nil)

But I recommend against it. You'd be giving up the major factor of keeping the parens balanced, just have a bit more convenience for when they're not balanced, which they shouldn't be anyway.

**Comment by seudut** [comment]
Thanks abo-abo
