### ISSUE TITLE
Inserting pairs just before strings in clojure indents code unneccesarily

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#301]
Type the following in a clojure file:

`(def alphabet |"abcdefghijklmnopqrstuvwxyz")`

With point at |, the following commands will indent the whole sexp by two spaces: lispy-wrap-round, lispy-parens, lispy-open-square, lispy-open-curly.

The lispy-wrap-foo commands will cause the weird indentation even if called at the end of the string. It doesn't happen when wrapping just a symbol though.

**Comment by abo-abo** [comment]
This is a bug in `clojure-mode`. Apparently, the indentation is broken in a recent version. 

You can reproduce this by pressing <kbd>TAB</kbd> even with `lispy-mode` off. I suggest you report the bug to `clojure-mode` and close this one when it's fixed.

**Comment by sooheon** [comment]
Reported at clojure-mode here: https://github.com/clojure-emacs/clojure-mode/issues/405

**Comment by carlosgeos** [comment]
A PR has been merged into clojure-mode and I think this issue can be closed.

**Comment by abo-abo** [comment]
@carlosgeos Thanks, closing.
