### ISSUE TITLE
lispy-newline-and-indent doesn't work in cider-repl-mode

### ISSUE THREAD

**Issue by dpetranek** [abo-abo/lispy#315]
When I invoke lispy-newline-and-indent in the cider repl, it sends the current line for evaluation instead of moving to a newline and indenting.

I think this is a case like the one mentioned here: http://oremacs.com/2014/12/31/keymap-arms-race/

Lispy mode should yield to cider-repl-mode on this keybinding.

**Comment by abo-abo** [comment]
There's already code for that:

> ((eq major-mode 'cider-clojure-interaction-mode)
>          (setq this-command 'cider-eval-print-last-sexp)
>          (cider-eval-print-last-sexp))

**Comment by dpetranek** [comment]
Can we tweak it so it does the right thing out of the box? I imagine the intersection of lispy users and cider users is pretty large.

**Comment by abo-abo** [comment]
It's already supposed to work out of the box. There was an update in CIDER, I guess, and now it doesn't work. Just tell me the command name in `cider-repl-mode`, I can add it.

**Comment by dpetranek** [comment]
The command is cider-repl-newline-and-indent.

Thanks for listening and making great software.

**Comment by abo-abo** [comment]
Thanks.
