### ISSUE TITLE
Let lispy-left regex account for quoted delimiters

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#319]
For example, if I'm passing a quoted char as an argument:
```
(case foo
  \a :bar
  \(|)
```

Pressing space will append spaces, because lispy-left matches the quoted `\(` as  start of a list. So what we want is to update the regex to something like `[^\][[({]`, but I'm not sure how to implement this (for some reason the above regex hangs `make test` compilation in the lispy repo). Any pointers? Thanks.

**Comment by abo-abo** [comment]
Thanks, please test.
