### ISSUE TITLE
lispy-kill question

### ISSUE THREAD

**Issue by carlcotner** [abo-abo/lispy#320]
I am a long time Emacs user but have little experience with using Lisp modes and am finally trying to learn lispy. I have a question about the definition of lispy-kill.

When I killed a one-line (define-key ...) form inside a multi-line (if ...), the form was deleted as I was expecting, and then I moved down a few lines and killed a multi-line (defun ...) form, and I was surprised that much of the rest of my file was gone.

So I looked at the lispy-kill documentation and saw that everything was working as intended. I am wondering, though, why there is no case between case 6 and case 7 like this:

> **case 6.5: before the opening parenthesis of a multi-line list**
> 
> Delete the multi-line list (and fix up whitespace).

Why does lispy-kill go from deleting one list to deleting to the end of the enclosing list just because the list spans multiple lines? What is the standard idiom for deleting a multi-line list in this situation?

**Comment by abo-abo** [comment]
> Why does lispy-kill go from deleting one list to deleting to the end of the enclosing list just because the list spans multiple lines?

<kbd>C-k</kbd> by default kills from the current point until the end of the line. `lispy-kill` tries to do that and then clean up to balance the parens.
Since you kill the opening paren of the `defun`, there's nothing left to do but to delete the whole `defun` body.

**Comment by carlcotner** [comment]
Okay, that's what I expected, but that's not what actually happens! In the following circumstance (bar represents cursor), `lispy-kill` does what you mention:
```
(when t
| (form1 blah blah)
  (form2 blah blah))
```
But in this situation:
```
(when t
| (form1 blah
         blah)
  (form2 blah blah))
```
`lispy-kill` kills `(form2 ...)` as well. It seems `lispy-kill` needs a **case 6.5** as I mentioned in my first message.

**Comment by abo-abo** [comment]
Thanks.
