### ISSUE TITLE
Vector slurp retains whitespace

### ISSUE THREAD

**Issue by ccann** [abo-abo/lispy#321]
Slurping on a vector retains whitespace whereas slurping on a paren does not:

`[] :a :b`

slurp twice

`[ :a :b]`

I often find myself slurping into a vector and then using `d` to go back to the beginning of the vector, delete the whitespace, `d` again to continue from where I was. 

Is there a better pattern here? I could kill the line or region, insert `[]`, then yank, but for some reason that's less intuitive to me.

(thanks for this awesome package!)

**Comment by abo-abo** [comment]
Thanks, fixed. Note that you can also fix whitespace with <kbd>i</kbd>.
