### ISSUE TITLE
more lispy-kill issues

### ISSUE THREAD

**Issue by carlcotner** [abo-abo/lispy#322]
Thanks for your help on my previous report.

These two reports are similar. I'll use the following function definition as an example, using "|" to represent the cursor.
```
(defun test ()
  "documentation"
  (interactive)
| ;;  Comment
  ;; (old-code)
  (new-code))
```
In the following case, `lispy-kill` gives the (to me) expected result:
```
(defun test ()                    (defun test ()
  "documentation"                   "documentation"
  (interactive)                     (interactive)
  |;  Comment      -lispy-kill->    |
  ;; (old-code)                     ;; (old-code)
  (new-code))                       (new-code))
```
This similar case works differently:
```
(defun test ()                    (defun test ()
  "documentation"                   "documentation"
  (interactive)                     (interactive)
| ;;  Comment      -lispy-kill->  | )
  ;; (old-code)
  (new-code))
```
Here is a similar discrepancy. This acts like I expected:
```
(defun test ()                    (defun test ()
  |documentation"  -lispy-kill->    |
  (interactive)                     (interactive)
  ;;  Comment                       ;;  Comment
  ;; (old-code)                     ;; (old-code)
  (new-code))                       (new-code))
```
With one small change, it acts quite differently ("_" represents trailing space after the documentation string):
```
(defun test ()                     (defun test ()
  |documentation"_  -lispy-kill->    |
  (interactive)                      ;;  Comment
  ;;  Comment                        ;; (old-code)
  ;; (old-code)                      (new-code))
  (new-code))
```
(I did my best to get the formatting exactly correct.)

**Comment by abo-abo** [comment]
Thanks, I can reproduce the first example.

I don't see the opening quote in the second example.

**Comment by carlcotner** [comment]
Sorry, should have explained the notation. The quotation mark is supposed to be there but is not visible because it is "under" the cursor. (It's not possible to both display all the characters in the buffer and show the cursor in the exactly correct position when it is on a non-space.) Perhaps this is clearer, though not quite correct:
```
(defun test ()                     (defun test ()
 |"documentation"_  -lispy-kill->    |
  (interactive)                      ;;  Comment
  ;;  Comment                        ;; (old-code)
  ;; (old-code)                      (new-code))
  (new-code))
```
Does this make sense now?

**Comment by abo-abo** [comment]
Thanks, I see the issue now. You know, it's pretty easy to just write an ERT test for this.

Press <kbd>S</kbd> on the whole expression to get:

    "(defun test ()
      |\"documentation\" 
      (interactive)
      ;;  Comment
      (new-code))"

Wrap it like this, and add <kbd>C-k</kbd>:

    (lispy-with
     "(defun test ()
      |\"documentation\"
      (interactive)
      ;;  Comment
      (new-code))"
     "\C-k")

Eval with <kbd>E</kbd> and finalize an ERT test:

    (should (equal (lispy-with
                    "(defun test ()
      |\"documentation\" 
      (interactive)
      ;;  Comment
      (new-code))"
                    "\C-k")
                   "(defun test ()
      |
      ;;  Comment
      (new-code))"))

I usually make multi-line strings into one-line with <kbd>M-o</kbd>, since they don't line up nicely anyway:

    (should (equal (lispy-with
                    "(defun test ()\n  |\"documentation\" \n  (interactive)\n  ;;  Comment\n  (new-code))"
                    "\C-k")
                   "(defun test ()\n  |\n  ;;  Comment\n  (new-code))"))

The test can be viewed better by pressing <kbd>xv</kbd> on the `should` statement.

**Comment by abo-abo** [comment]
Both should work now, please test.

**Comment by carlcotner** [comment]
Oh, that's cool - I didn't know about ERT tests before. Would you like me to submit an ERT test when I find what looks to me to be a bug?

**Comment by abo-abo** [comment]
Yes, please. If you have the time. Look at `lispy-test.el`, plenty of examples there.

**Comment by carlcotner** [comment]
Supposing I didn't introduce typos, both of the following tests are supposed to pass, but only the first one will. (I'm not able to actually run the tests yet to check them.)

```
(should (equal (lispy-with
                "(defun test ()\n  \"documentation\"\n  (interactive)\n  |;;  Comment\n  (new-code))"
                "\C-k")
               "(defun test ()\n  \"documentation\"\n  (interactive)\n  |\n  (new-code))"))
```

```
(should (equal (lispy-with
                "(defun test ()\n   \"documentation\"\n  (interactive)\n|  ;;  Comment\n  (new-code))"
                "\C-k")
               "(defun test ()\n   \"documentation\"\n  (interactive)\n|  \n  (new-code))"))
```

**Comment by abo-abo** [comment]
Here are two lines, the first one is yours from the second test, the second one I get by pressing <kbd>E</kbd> on the `lispy-with` statement:

    "(defun test ()\n   \"documentation\"\n  (interactive)\n|  \n  (new-code))"
    "(defun test ()\n   \"documentation\"\n  (interactive)\n|\n  (new-code))"

As you can see, the difference is the two spaces after cursor. But the second line is the correct behavior.

**Comment by carlcotner** [comment]
Oh, sorry, that was unfortunately a typo. But I don't actually get the behavior in `lispy` that pressing `E` gives you. I think I might know why, but I should have mentioned this first: pressing `E` doesn't evaluate the `lispy-with` statement for me. Instead, I get the error "Symbol’s function definition is void: lispy-with".

When I looked into this yesterday, I found that the macro `lispy-with` is defined in `lispy-test.el` and isn't available in `lispy` by default. Do you always load all of `lispy-test.el` when testing? Would it be reasonable to make the testing apparatus available in `lispy` itself by default, or should I just load it when writing tests?

**Comment by abo-abo** [comment]
> Do you always load all of lispy-test.el when testing?

Yes, I do that.

> Would it be reasonable to make the testing apparatus available in lispy itself by default, or should I just load it when writing tests?

It's best to avoid loading the testing module unless you really need it. In all user cases, loading `lispy-test` is not necessary.
