### ISSUE TITLE
Conflict/interaction with edebug

### ISSUE THREAD

**Issue by bpstahlman** [abo-abo/lispy#323]
I've been playing around with lispy in edebug mode, and though I've mostly been able to make the two packages play nicely together, I've noticed a few idiosyncrasies...

For one thing, `i` seems to invoke `edebug-step-in`, but it's not clear to me how. `C-h k i` in edebug mode reports `special-lispy-tab`, but when I execute it from special mode, edebug execution enters the callee function, so clearly some magic is happening here. While perusing lispy.el, I noticed what appeared to be some sort of edebug command pass-through mechanism - is that the explanation?

Also, I've noticed that both `f (lispy-flow)` and `d (lispy-different)` seem to be overridden by edebug's `f (edebug-forward-sexp)` and `d (edebug-backtrace)`. Is that by design? If so, is there a workaround? Is there any sort of wiki or other documentation that gives tips for using lispy in debug/edebug modes?

Thanks,
Brett S.

**Comment by abo-abo** [comment]
> I noticed what appeared to be some sort of edebug command pass-through mechanism - is that the explanation?

See `lispy-compat` variable. By default, `edebug` is included there. If so, when `edebug` mode is active, the `special-lispy-...` function will call the corresponding `edebug` function.

> Also, I've noticed that both f (lispy-flow) and d (lispy-different) seem to be overridden by edebug's f (edebug-forward-sexp) and d (edebug-backtrace). Is that by design? If so, is there a workaround? Is there any sort of wiki or other documentation that gives tips for using lispy in debug/edebug modes?

The design is to yield to `edebug` if it's on. It's as if `lispy-mode` turns itself off for the duration of `edebug`. I think you could rebind/unbind e.g. <kbd>f</kbd> key in `edebug`, then it would be used for `lispy-flow`, even with `edebug` on.

Myself, while I often use `edebug`, I very rarely use `edebug-mode`. I simply instrument a function with <kbd>xe</kbd> and once `edebug` triggers I exit it with <kbd>Z</kbd>. The current function arguments get saved in the global workspace, so I can continue the execution with <kbd>p</kbd>.

**Comment by bpstahlman** [comment]
Ok. That makes sense. I'll try it out. Much of the edebug functionality I use for stepping has C-c alternatives to the short (single-letter) commands. I wonder whether there would be an advantage to having an option to retain most lispy functionality at the expense of having to use longer edebug mappings. Just a thought... I'm still fairly new with both lispy and emacs, so I may find better ways of doing things as I gain experience. I appreciate the tip regarding `xe`; I'd noticed that command, but wasn't quite sure what the use case was. After reading your response, I looked in the detailed function reference and it became clear.
Thanks.

**Comment by abo-abo** [comment]
You're welcome. Don't hesitate to ask if anything else isn't clear.
