### ISSUE TITLE
lispy-delete-backward issue

### ISSUE THREAD

**Issue by carlcotner** [abo-abo/lispy#326]
I'm able to evaluate `lispy-with` using `E` now, and I'm starting to get the hang of how `lispy` works. As it says in one of the tutorials, the key choices for `lispy` are very well designed. Thanks, they are a pleasure to use.

The following seems like a bug in `lispy-delete-backward` to me. This tests for the behavior I expected (but it returns `nil`):
```
(equal (lispy-with "(defun test ()\n  \"documentation\" |\n  (code))" (kbd "DEL"))
                   "(defun test ()\n  \"documentation\"|\n  (code))")
```
while this tests for the behavior I got (and it returns `t`):
```
(equal (lispy-with "(defun test ()\n  \"documentation\" |\n  (code))" (kbd "DEL"))
                   "(defun test ()\n  |\n  (code))")
```
This is inconsistent with similar cases like this (which returns `t`):
```
(equal (lispy-with "(defun test ()\n  \"documentation\"\n  (some-code) |\n  (more-code))" (kbd "DEL"))
                   "(defun test ()\n  \"documentation\"\n  (some-code)|\n  (more-code))")
```
(I've aligned the before/after strings to make it easier to see the changes even though this isn't consistent with the actual structure of the code.)

-----

It can be a bit difficult to read the tests, so I played around with different formatting possibilities for fun. Just in case you hadn't thought of it, I wanted to mention: if there were a macro that combined `lispy-with` and `equal` (perhaps `lispy-equal-with`), then the strings would naturally align like so:
```
(lispy-equal-with "(defun test ()\n  \"documentation\"\n  (code) |\n  (code))" (kbd "DEL")
                  "(defun test ()\n  \"documentation\"\n  (code)|\n  (code))")
```
One has to deal with the possibility of more than one `lispy` editing function in the middle, but that is doable (or the functions could just be put at the end of the argument list).

Finally, I wanted to share another, more radical possibility just because I find it interesting. I suppose it's a bad idea since its conventions are so non-standard, which also makes editing it an adventure, but the macro is short (leveraging `lispy-with`), and I've been experimenting with it because the resulting layout is easy to read once one understands it:
```
(lispy-equal-with* "(defun test ()"         (kbd "DEL")  "(defun test ()"
                   "  \"documentation\" |"               "  \"documentation\"|"
                   "  (code))"                           "  (code))")
```
Perhaps automatic conversion/formatting functions could help make something like this usable.

**Comment by carlcotner** [comment]
Here is some more `lispy-kill` behavior that seems anomalous to me. The examples each start from this form:
```
(progn
  "docs"   ;;  0
  (one)    ;;  1
  (two))   ;;  2
```
The first of each of the following pairs is what I expected to happen, the second is what actually happens. Expected (cursor at the beginning of the documentation line):
```
(equal (lispy-with "(progn\n|  \"docs\"   ;;  0\n  (one)    ;;  1\n  (two))   ;;  2\n" (lispy-kill))
                   "(progn\n|\n  (one)    ;;  1\n  (two))   ;;  2\n")
```
Actual:
```
(equal (lispy-with "(progn\n|  \"docs\"   ;;  0\n  (one)    ;;  1\n  (two))   ;;  2\n" (lispy-kill))
                   "(progn\n|;;  1\n  (two))   ;;  2\n")
```
Expected (cursor at the beginning of the documentation string):
```
(equal (lispy-with "(progn\n  |\"docs\"   ;;  0\n  (one)    ;;  1\n  (two))   ;;  2\n" (lispy-kill))
                   "(progn\n  |\n  (one)    ;;  1\n  (two))   ;;  2\n")
```
Actual:
```
(equal (lispy-with "(progn\n  |\"docs\"   ;;  0\n  (one)    ;;  1\n  (two))   ;;  2\n" (lispy-kill))
                   "(progn\n  |;;  1\n  (two))   ;;  2\n")
```
Expected (cursor at the beginning of the first function line):
```
(equal (lispy-with "(progn\n  \"docs\"   ;;  0\n|  (one)    ;;  1\n  (two))   ;;  2\n" (lispy-kill))
                   "(progn\n  \"docs\"   ;;  0\n|\n  (two))   ;;  2\n")
```
Actual:
```
(equal (lispy-with "(progn\n  \"docs\"   ;;  0\n|  (one)    ;;  1\n  (two))   ;;  2\n" (lispy-kill))
                   "(progn\n  \"docs\"   ;;  0\n|)   ;;  2\n")
```
This works as expected (cursor at the beginning of the first function):
```
(equal (lispy-with "(progn\n  \"docs\"   ;;  0\n  |(one)    ;;  1\n  (two))   ;;  2\n" (lispy-kill))
                   "(progn\n  \"docs\"   ;;  0\n  |\n  (two))   ;;  2\n")
```
I think the last example (below) is interesting because the expected behavior may not be the same for everyone, depending on how one thinks killing lines should work with respect to end-of-line comments when line killing crosses line boundaries. I think it should happen as in the first example below because if I'm killing all the lines, I want to get rid of the comments for all the lines, too (this returns `nil`):
```
(equal (lispy-with "|(progn\n  \"docs\"   ;;  0\n  (one)    ;;  1\n  (two))   ;;  2\n" (lispy-kill))
                   "|\n")
```
On the other hand, if one supposes that killing lines should be as conservative as possible while maintaining syntactic correctness, then this way makes sense (this returns `t`):
```
(equal (lispy-with "|(progn\n  \"docs\"   ;;  0\n  (one)    ;;  1\n  (two))   ;;  2\n" (lispy-kill))
                   "|   ;;  2\n")
```
Comments decorate code, however, so in my opinion it makes sense to consider a comment to be part of the code it decorates for the purpose of `lispy-kill`. So when all the code on a line is deleted by killing the line, I would say that it's reasonable to kill its end-of-line comment, too.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by abo-abo** [comment]
> lispy-equal-with

This is interesting for the cases when both strings compared are very short and the change happens near the end so that they align. But I'm happy enough with the current setup, especially since each test can be visualized with <kbd>xv</kbd>.

**Comment by abo-abo** [comment]
Additionally, it's possible to unquote an example string in `*scratch*` by marking it and pressing <kbd>'</kbd>. Then move to `|` position manually and execute the command to see what it does.

**Comment by abo-abo** [comment]
> Comments decorate code, however, so in my opinion it makes sense to consider a comment to be part of the code it decorates for the purpose of lispy-kill. So when all the code on a line is deleted by killing the line, I would say that it's reasonable to kill its end-of-line comment, too.

I like the current behavior: it tries to kill the current line, and then kills as much text as is necessary to balance the parens, thus leaving the comment. The comment can be deleted with an additional <kbd>C-k</kbd>.

**Comment by carlcotner** [comment]
Everything in the second comment works for me. Thanks!

I'm not sure what the intended behavior is supposed to be, but the example in the first comment still works as before.
