### ISSUE TITLE
Uncomment when commenting comment

### ISSUE THREAD

**Issue by louwers** [abo-abo/lispy#329]
I think it would make sense to uncomment a comment when pressing `;` or calling `lispy-comment`.

To be clear the context would be the first character of a commented line (not inline comment).

```
<cursor>;; some comment
```
call `lispy-comment`, results in:
```
some comment
<cursor>
```
or alternatively

```
<cursor>some comment
```

I personally think the latter would make most sense, because the reason for uncommenting something is usually that it's lisp code that you want to work on again.

What do you think?

**Comment by abo-abo** [comment]
I think <kbd>C-u ;</kbd> already serves the purpose of uncommenting well enough. And the advantage is that it works from anywhere in the comment, even when not in special.

**Comment by sooheon** [comment]
Agreed, though I think lispy could be smarter about backspacing comments when one is accidentally started. If you can add a bunch of spaces with one press of `;`, you should be able to revert it immediately with backspace.

**Comment by abo-abo** [comment]
@sooheon Sounds good, please PR.
