### ISSUE TITLE
Feature request: Easy way to get into special when looking at whitespace preceding lispy-left

### ISSUE THREAD

**Issue by bpstahlman** [abo-abo/lispy#330]
Not a complaint or bug report, but having used lispy a bit, I find myself wanting something like `[` for getting into special, but moving forward, not backward: e.g., with point represented by caret...

`(foo a
    ^   (b c))`

...I want to be able to hit something that puts me in special at `(b c)`: i.e., moves me forward to the next open paren, skipping over whitespace (and possibly even non-list sexp's). Does this make sense? I realize that in this particular case, I could do `[ f` to get the same result, but somehow that doesn't feel quite as intuitive, and it just seems like a common enough use-case that it might warrant its own command.

Incidentally, it's also occurred to me that it might be nice to have a way to move the region in and out of lists, with motions analogous to those of `lispy-forward` and `lispy-backward`: i.e., move region to the next or previous sexp, without regard to whether it's a list, string, or symbol, and even if it means crossing list boundaries. Perhaps the functionality is there, and I just missed it. (I still find myself discovering stuff I overlooked in earlier perusals of the documentation...)

Thanks,
Brett S.

**Comment by abo-abo** [comment]
> Perhaps the functionality is there, and I just missed it.

It's not there, I use `[ f`. Would be nice to have, but there are good global shortcuts left.

**Comment by bpstahlman** [comment]
That wouldn't work at top-level, but I guess `] h` would work there. Incidentally, I assume you mean there _aren't_ any good global shorcuts left. If so, that's fine. I can get used to `[ f` and `] h` now that I know there's not a more direct way.

**Comment by abo-abo** [comment]
Another key binding is <kbd>C-M-f d</kbd>, using the built-in `forward-sexp`.

**Comment by bpstahlman** [comment]
Ah. Yes. Lispyville doesn't put you in special after `C-M-f`, but it does provide `L` and `H` for `forward-sexp` and `backward-sexp`, respectively. I still haven't decided for certain whether I even need Lispyville. I'm firmly convinced that evil provides the most efficient paradigm for editing arbitrary *text*, but the more I work with and learn about lispy, the less need I feel to treat lisp as text...

**Comment by noctuid** [comment]
Maybe it wouldn't be a good idea, but it seems this functionality could be added to `lispy-space` as inserting another space here doesn't make sense.

> I still haven't decided for certain whether I even need Lispyville...

Lispy is a much better way of editing lisp than with vanilla evil (even with safe operators). Although I want to have lispyville provide more intelligent lisp editing functionality in normal state, it will all be optional. For me, the best way to use lispyville is to make it easier to use lispy as much as possible instead of evil. I have a lot of non-editing commands (e.g. for file/window/workgroup navigation) bound in normal state, so I always use normal state for something, but in lisp modes, I want to use lispy primarily for editing. Another goal of lispyville is to accomodate this sort of workflow (e.g. by providing ways to quickly get out of normal state into special).

**Comment by bpstahlman** [comment]
> this functionality could be added to lispy-space as inserting another space here doesn't make sense.
That sounds like an excellent idea; I can't think of a good reason to insert a space before a sexp, and if you really needed to, there's always C-q.

> I have a lot of non-editing commands (e.g. for file/window/workgroup navigation) bound in normal state, so I always use normal state for something, but in lisp modes, I want to use lispy primarily for editing.

Yes! That's my situation exactly. Occasionally, in the interest of reducing "incidental complexity", I consider switching to plain (non-evil) emacs, perhaps sweetened a bit with packages like god-mode and composable. But invariably, I conclude that that the economy of keystrokes permitted by modal editing, coupled with the flexibility/power of orthogonal operators/motions is too much to give up... Also, when you're accustomed to Vim's wincmd's, `C-x o` feels very constraining... At least for lisp editing, `lispy-back` has taken care of one of my other big gripes with plain emacs: no jump list. (Would be nice if there were a corresponding command to move in the other direction, like Vim's `C-i`, but just having `lispy-back` is huge.)

I'm still getting used to Lispyville, but am very impressed with what I've seen so far. I especially like the v, V and C-v operators for marking. Also, was excited to see the various operators provided for change/delete, etc... Was a bit concerned at first when I noticed that some of them used keybindings already used by Lispy (e.g., `C lispy-convolute` and `D pop-tag-mark`). Is the idea that you should always drop back to evil-normal-state before using these commands? I suppose that makes sense, given that you'd use them only in normal state in Vim itself.

**Comment by noctuid** [comment]
I like evil for editing non-lisp languages/text, but I also really like it just as a keybinding/modal system and use it everywhere else too (e.g. mail client).

> Also, when you're accustomed to Vim's wincmd's, C-x o feels very constraining...

You may also want to try [ace-window](https://github.com/abo-abo/ace-window) if you haven't already (if you use a lot of windows, it is very nice).

> Is the idea that you should always drop back to evil-normal-state before using these commands?

Yes, none of the provided commands are meant to be used in special. Feel free to make issues in the lispyville repo if you have any more questions or suggestions.

**Comment by bpstahlman** [comment]
> Feel free to make issues in the lispyville repo if you have any more questions or suggestions.

Will do. I appreciate the suggestions.
