### ISSUE TITLE
Is it possible to uncomment lines selectively within a block?

### ISSUE THREAD

**Issue by bpstahlman** [abo-abo/lispy#331]
I had the following comment block, and wanted to uncomment just the `global-set-key` calls.
```
;; TODO: Decide on this...
;; (global-set-key (kbd "<escape>") 'god-local-mode)
;; (global-set-key (kbd "<escape>") 'god-mode-all)
```
I tried `C-u ;` but that uncommented the TODO also. I tried various approaches to deleting just the semicolons on a single line, but the only way I found to accomplish what I wanted was to uncomment the block (which jumped me down a bit in the file to the next comment block), then jump back up to the TODO line (with the handy `b` command) and re-comment it with `;`. Is there a way (without temporarily disabling lispy) to uncomment only specific lines within a block? No big deal if not, as the block operation seems generally pretty intuitive/handy - I just wanted to be sure there wasn't an "override" of some sort for these sorts of corner cases...

**Comment by abo-abo** [comment]
> Is there a way (without temporarily disabling lispy) to uncomment only specific lines within a block?

If you mark a comment with a region, <kbd>;</kbd> will uncomment them.

**Comment by bpstahlman** [comment]
Perfect. Thanks. I'd tried marking, but I guess I'd been doing all my marking with lispy/lispyville commands, which grab the entire comment block. Must not have tried C-SPC...

**Comment by abo-abo** [comment]
You're welcome.
