### ISSUE TITLE
Bug: Deleting empty {} deletes parent list.

### ISSUE THREAD

**Issue by bpstahlman** [abo-abo/lispy#333]
**To Reproduce...**
`(foo bar {})`
...Hit `DEL` with cursor inside the empty pair of curly braces.
**Result:** The entire form is deleted.

**Explanation:**  Within `lispy-delete-backward`, the `(lispy-looking-back lispy-left)` test (see below) succeeds because `{` is considered to be "lispy left", so `lispy--out-forward` tries to move past the terminating `}` in preparation for the delete. The problem is that `lispy--out-forward` uses `up-list` to accomplish the move, and since `{` and `}` are apparently not considered parenthetical delimiters by the governing syntax table, `up-list` ends up moving _past_ the `)` terminating the parent list, with the result that `(lispy-delete-backward 1)` clobbers the parent form, rather than the empty braces.

**Problematic Code:**
```
((and (lispy-looking-back lispy-left)
     (not (lispy-looking-back "[\\?].")))
(lispy--out-forward 1)
(lispy-delete-backward 1))
```

**Comment by abo-abo** [comment]
It think it's fine more or less, since the bug happens when you have `{}` in e.g. Elisp, for which this isn't a type of a list in the major-mode syntax.  For languages that support it, like Clojure, it works fine.

**Comment by bpstahlman** [comment]
Ah. Sorry about that. It should have occurred to me that the syntax table would differ according to major mode. (I was playing around in `*scratch*`, so the major-mode syntax in effect would indeed have been elisp.)
