### ISSUE TITLE
Can you change lispy--eval-nrepl-clojure to use cider-eval-last-sexp

### ISSUE THREAD

**Issue by abcdw** [abo-abo/lispy#338]
Thank you for the great plugin and fast fixes.

Can you change implementation of lispy--eval-nrepl-clojure to use cider-eval-last-sexp.
cider-eval-last-sexp shows the result of evaluating not only in status bar, but also near the sexp, it is very handy.

**Comment by abo-abo** [comment]
There was an effort from @sooheon to do it, I think. Is that right?

**Comment by sooheon** [comment]
Hm yeah I didn't get anywhere with that yet. FWIW, I think @abcdw can get what you want just with `(set lispy-eval-display-style 'overlay)`, no?

**Comment by abcdw** [comment]
Yep. Absolutely, it's very good solution. Also cider-eval-last-sexp shows stacktrace in case of error, but lack of this feature is not a problem for me. 

Thanks a lot for fast reaction and good solution.

**Comment by abo-abo** [comment]
Thanks, closing.

**Comment by abcdw** [comment]
`(set lispy-eval-display-style 'overlay)` works good, but it combines stdout and the result of evaluation and also shows it in minibuffer. Redirecting to stdout seems ok for, but duplication in minibuffer isn't useful. 

* How to disable output to minibuffer?
* How to stop redirecting stdout? (not important)

![screenshot from 2017-02-23 23-27-55](https://cloud.githubusercontent.com/assets/1218615/23277661/c30de376-fa1f-11e6-88dd-05b77ca89ac3.png)
