### ISSUE TITLE
lispy-mode interferes with git-timemachine

### ISSUE THREAD

**Issue by ccann** [abo-abo/lispy#340]
I'm not sure if this is a git-timemachine issue or a lispy issue. When you invoke git-timemachine on a buffer that has lispy-mode enabled then the keybindings for git-timemachine clash with lispy's. Is there a way to turn off lispy-mode when git-timemachine is invoked on a buffer? I'm not an experienced emacs-lisp user so apologies if this is a totally mundane issue.

**Comment by abo-abo** [comment]
Try this:

```elisp
(define-advice git-timemachine-mode (:after (&optional arg))
  (if (bound-and-true-p git-timemachine-mode)
      (lispy-mode -1)
    (lispy-mode 1)))
```

**Comment by ccann** [comment]
Thanks!
