### ISSUE TITLE
How to see all lispy keys?

### ISSUE THREAD

**Issue by yatesco** [abo-abo/lispy#345]
Hi, relative emacs newbie here - I have which-key and hydra installed to great effect. However, as a newbie I can't figure out how I can see all the configured keys. 

The readme page is great, but I couldn't, for example, figure out how to navigate _into_ an sexp. 

Ideally, I should be able to press something and either which-key or a persistent hydra appear which lets me know what I can do next - is this possible/already configured?

(and thanks - loving emacs + the abo-abo magic :-)).

**Comment by abo-abo** [comment]
When in doubt, check the source code. For instance, look at the definition of `lispy-mode-map-special`.

Additionally, there's a pretty comprehensive [reference](http://abo-abo.github.io/lispy/).

As to your question:

- you can step into a list with <kbd>f</kbd>.
- you can step into the symbols of a list with <kbd>mi</kbd>.
- you can step into parts of a single symbol with <kbd>-</kbd>.

**Comment by yatesco** [comment]
Perfect - thanks @abo-abo. That reference is exactly what I was looking for.

**Comment by yatesco** [comment]
https://github.com/abo-abo/lispy/blob/master/lispytutor/lispytutor.el seems relevant as well.

**Comment by abo-abo** [comment]
Right! Sometimes I forget what's in Lispy. There are also nice tutorials labeled as `Demos` in `README.md`.
