### ISSUE TITLE
RET doesn't evaluate input in ielm when lispy-mode is on

### ISSUE THREAD

**Issue by dsedivec** [abo-abo/lispy#347]
I'm actually not sure if this is expected behavior or not, but it seems counterintuitive that return doesn't evaluate your input in an ielm buffer when lispy-mode is active.  Steps to reproduce:

1. Start `emacs -Q`
2. Install lispy by evaluating
    ```
    (require 'package)
    (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
    (package-initialize)
    ```
    and then `M-x package-install RET lispy RET`
3. `M-x ielm RET`
4. Activate lispy-mode in the ielm buffer via `M-x lispy-mode RET`
4. Type `t RET`

Expected result: `t` is evaluated in ielm
Observed result: newline inserted, no evaluation occurs

Versions:
Mac OS 10.11.6
GNU Emacs 25.2.1 (x86_64-apple-darwin15.6.0, NS appkit-1404.47 Version 10.11.6 (Build 15G1421)) of 2017-04-24
lispy-20170510.925 from MELPA

Other notes: It appears that `lispy-newline-and-indent` special-cases ielm, but `RET` is bound to `lispy-newline-and-indent-plain`, which does not special-case ielm.

Thanks for all your great packages!

**Comment by abo-abo** [comment]
Thanks.
