### ISSUE TITLE
do not bind globally iedit mode with C-;

### ISSUE THREAD

**Issue by habamax** [abo-abo/lispy#350]
Looks like lispy loads iedit mode which binds C-; globally.

Is there a way to turn this off?

**Comment by abo-abo** [comment]
I set this before loading `iedit` in my config:

    (setq iedit-toggle-key-default nil)

Maybe I should also do this by default.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by habamax** [comment]
Thx!
