### ISSUE TITLE
Allow lispy--normalize-1 to respect clojure-align-forms-automatically

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#352]
clojure-align-forms-automatically is a variable which lets clojure-mode align forms like the following:

    {:some-key 10
     :key2     20}

It would be nice if `i` in lispy respected this variable.

**Comment by abo-abo** [comment]
PR welcome, although I think it's ultimately better to have just a single space always.

**Comment by sooheon** [comment]
Just curious, why do you prefer that? I've noticed this setting often makes things easier to read.

**Comment by abo-abo** [comment]
- I'm just used to it
- Produces less whitespace diffs
- I saw the same recommendation in Google's style guide

**Comment by sooheon** [comment]
After trying it for a while, I'm coming to just a space around as well ;)
