### ISSUE TITLE
lispytutor

### ISSUE THREAD

**Issue by ninrod** [abo-abo/lispy#354]
Hi @abo-abo, thank you so much for this package. 

I just found a file called lispy tutor. Is it functional? I love the idea.

just reading at the comments is tremendously helpful.

**Comment by abo-abo** [comment]
Yes it's functional and interactive: you are meant to go through the instructions and actually modify the file. The inspiration is `vimtutor`.

**Comment by ninrod** [comment]
Nice! I think evil-mode is eating some keybindings though. Maybe I'm suppose to use emacs state throughout the tutorial.

**Comment by abo-abo** [comment]
Yes, that's what @noctuid also recommends, or is it just evil's insert state?

**Comment by noctuid** [comment]
@ninrod It shouldn't affect anything when you're in special, but evil insert state adds keybindings by default that will override other emacs keybindings (lispy's global keybindings here I assume), so it would make sense to use emacs state for the tutorial. For usage in the long run, evil makes it easy to prevent any keybindings from being created in insert state if you'd prefer.

**Comment by ninrod** [comment]
@noctuid and @abo-abo, emacs state work like a charm and everything is wonderful. 

Thank you both!
