### ISSUE TITLE
Support namespaced-map syntax in Clojure

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#356]
https://dev.clojure.org/jira/browse/CLJ-1910

This adds support for namespacing keywords in maps like the following: `#::{:foo :bar}`

However, lispy keeps separating it out to `#:: {:foo :bar}`, when I type it out (lispy-braces) or clean use special-lispy-tab.

**Comment by sooheon** [comment]
Wait, before you close, any idea on how to make `lispy-tab` also respect this syntax?

**Comment by abo-abo** [comment]
Open a new issue for that.
