### ISSUE TITLE
Support Clojure namespaced-map syntax in lispy-tab

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#359]
Refer: #356 

Lispy-tab should preserve the following in Clojure code: `#::{:foo "bar}`.

Currently, it will result in: `#:: {:foo "bar"}`

**Comment by abo-abo** [comment]
Thanks.

**Comment by abo-abo** [comment]
Feel free to look at the commit: it shows how easy it is to add new Clojure syntax. I'm not up to date with Clojure these days, maybe you could add new syntax stuff as it comes up.
