### ISSUE TITLE
Is there an easier way to append to a list?

### ISSUE THREAD

**Issue by bcarrell** [abo-abo/lispy#36]
I'm in this situation all the time:

`|(foo bar)`

My goal is to turn it into `(foo bar baz)` with the fewest keystrokes.  To accomplish this, I would basically do `d -> C-b -> SPC -> baz`.  Is there a faster way?  When I'm doing this sort of operation all the time, three keystrokes tends to feel less optimal.

**Comment by abo-abo** [comment]
There is a faster way: <kbd>do</kbd>, <kbd>SPC</kbd>, `baz`.

**Comment by bcarrell** [comment]
Perfect, that's better.  Thanks!

**Comment by abo-abo** [comment]
With the new way, you need just <kbd>3</kbd> <kbd>SPC</kbd>.
Also, there's <kbd>2</kbd> <kbd>SPC</kbd>. Thanks for bringing this up.

**Comment by bcarrell** [comment]
You're a machine.  Thanks!
