### ISSUE TITLE
lispy-delete-backward and lispy-backward-delete put cursor before repl prompts

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#366]
Call either function from these locations

```
ELISP>  (|)

cider-prompt> ()|
```

And many others involving deleting a pair of parens, and cursor will end up before the prompt.

This then prevents one from typing an open parens ever again unless you do something like `,clear<RET>` in the cider buffer.

**Comment by abo-abo** [comment]
Thanks, please test.
