### ISSUE TITLE
lispy-like editing mode based on nxml-mode

### ISSUE THREAD

**Issue by eipplusone** [abo-abo/lispy#370]
Firstly thank you for lispy! Truly a pleasure using it.

I tend to do a fair amount of xml editing(html and others), so I'd like to try my hand at writing lispy-like mode for editing xml. nxml-mode already provides functions like `nxml-forward-node` and `nxml-down-node`. XML naturally also have lisp-like tree with tag surrounds. Have you looked into anything similar?

It seems a fair amount of functions could be reused. One could go about it with refactoring lispy to allow arbitrary structures be special(like xml tags) or making it a brand new mode based on lispy. I see former being implemented as either a cursor within range is special or just hide the cursor from the user and highlight the tags and allow tag-only moves.

Any thoughts?

Another interesting possibility, albeit much harder and not pertaining the issue title, would be to write lispy-like mode for Javascript. I see from https://github.com/abo-abo/lispy/issues/344 that you mention lpy as a lispy solution for python, which is great. Javascript is interesting because js2-mode actually includes an AST parser written in elisp, which could allow for some more intelligent "special" parsing not based on regex. That's just an idea though; however, it would bring Emacs on an entirely different level as a JS editor.

**Comment by abo-abo** [comment]
> Firstly thank you for lispy! Truly a pleasure using it.

You're welcome, I'm glad you like it.

> I tend to do a fair amount of xml editing(html and others), so I'd like to try my hand at writing lispy-like mode for editing xml. nxml-mode already provides functions like nxml-forward-node and nxml-down-node. XML naturally also have lisp-like tree with tag surrounds. Have you looked into anything similar?

I haven't. I don't deal with XML too much; and when I do, it's usually painful for several reasons:

- in industry, XML files can be megabytes in size
- often, the whole file is on one line; Emacs isn't designed to work with really long lines
- `nxml` is very slow for large files - I tend to switch to `fundamental-mode`, which is faster.

> It seems a fair amount of functions could be reused. One could go about it with refactoring lispy to allow arbitrary structures be special(like xml tags) or making it a brand new mode based on lispy. I see former being implemented as either a cursor within range is special or just hide the cursor from the user and highlight the tags and allow tag-only moves.
>
> Any thoughts?

`lispy` relies on `forward-list` and `up-list`, with those functions hard-coded.  It could be possible to extract them and allow to customize them, e.g. substitute `nxml-forward-element` and `nxml-up-element`. But that's a lot of work. Not just coding it up, but also testing everything and considering an impact on performance.

> Another interesting possibility, albeit much harder and not pertaining the issue title, would be to write lispy-like mode for Javascript. I see from #344 that you mention lpy as a lispy solution for python, which is great. Javascript is interesting because js2-mode actually includes an AST parser written in elisp, which could allow for some more intelligent "special" parsing not based on regex. That's just an idea though; however, it would bring Emacs on an entirely different level as a JS editor.

Might be interesting. But I tend to implement stuff for things that I use (like Elisp, Python, Clojure, C++; to a lesser extent SML, J, Java, MATLAB, Julia, Racket). I have no experience with JavaScript.

But I can say that making a version of `lispy` for C++ is much harder than one for Python.  I'm guessing the structure of JavaScript is closer in complexity to C++ than to Python.

**Comment by eipplusone** [comment]
I believe it's the least amount of work for me to refactor lispy a bit to allow it to integrate with nxml-mode. If it's worthy of submission I'll let you know. Thank you for your response!

**Comment by abo-abo** [comment]
> Speaking of C++ - do you have anything like lpy written for it?

Nothing worthy of publishing so far.
