### ISSUE TITLE
void-variable hydra-lispy-x on load

### ISSUE THREAD

**Issue by jgkamat** [abo-abo/lispy#372]
Hi,

When I `(require 'lispy)`, I get

```
Debugger entered--Lisp error: (void-variable hydra-lispy-x)
  byte-code("\306\307\310\311\312\313\314%\315\316	\317\"\320\n\321\"\322\323\"\324\f\325\"\326
\327\"\3308\331\"\3329\333\"\334:\335\"\336;\337\"\340<\341\"\342=\343\"\344>\345\"\346?\347\"\350@\351\"\352A\353\"\354B!\355C\356\"\357D\360\"\361E\362\"\363F\364\"\365G\307\312#\366G\367\307\312$&\207" [hydra-lispy-x lispy-bind-variable lispy-to-cond lispy-to-defun lispy-extract-defun lispy-edebug defhydra :exit t :hint nil :columns 3 "x" "b" "bind variable" "c" "to cond" "d" "to defun" "D" "extract defun" "e" "edebug" "f" "flatten" "F" "let-flatten" "h" "describe" "i" "to ifs" "j" "debug step in" "k" "extract block" "l" "to lambda" "m" "multi cursor" "p" "process" "r" "eval and replace" "s" "u" "unbind let-var" "v" "view test" "B" ...] 30)
  require(lispy)
  eval((require (quote lispy)) nil)
  eval-expression((require (quote lispy)) nil)
  funcall-interactively(eval-expression (require (quote lispy)) nil)
  #<subr call-interactively>(eval-expression nil nil)
  apply(#<subr call-interactively> eval-expression (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> eval-expression nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (eval-expression nil nil))
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

I installed lispy from melpa unstable and stable, both seem to be broken for me. This is from an `emacs -Q`. Does anyone have any ideas on how to solve this.

**Comment by abo-abo** [comment]
Try cloning this repo and doing:

    make update
    make test

**Comment by jgkamat** [comment]
Both commands seem to work fine for me (all tests pass). 

The cask elpa folder and my personal elpa folder seem to have the same version of hydra, though. Do you have any idea what package could be causing this?

**Comment by abo-abo** [comment]
> The cask elpa folder and my personal elpa folder seem to have the same version of hydra, though. Do you have any idea what package could be causing this?

No idea. My point was to check that if you have the same versions of packages in your `~/.emacs.d/elpa` as in `~/.cask/elpa` everything works.
Now it's up to you to bisect your config; I've never encountered this issue, so I've got no pointers for you.

**Comment by jgkamat** [comment]
It seems that this is related to me mixing melpa and melpa stable (and it's not hydra, it's another package). lispy seems to have a ton of depedencies, so it's a little hard (and time consuming) to figure out which one is breaking it, so I'll just close this.

If you run into this, remove ~/.emacs.d/elpa and switch to pure melpa unstable.
