### ISSUE TITLE
Weird behavior with Paredit key theme in comments

### ISSUE THREAD

**Issue by drot** [abo-abo/lispy#375]
![2017-10-02-091745_464x57_scrot](https://user-images.githubusercontent.com/85483/31067348-b3e0bd70-a752-11e7-8d78-96517475617a.png)

After trying to delete the parens with Backspace (`DEL`) multiple times:

![2017-10-02-091811_450x56_scrot](https://user-images.githubusercontent.com/85483/31067366-d1560cf2-a752-11e7-8577-ae7005b8c9a3.png)

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by drot** [comment]
Works fine now, thanks.
