### ISSUE TITLE
`lispy-delete-backward` confused by \?

### ISSUE THREAD

**Issue by adamdavislee** [abo-abo/lispy#376]
Backspace after a sexp such as `(partial filter neg?)` will leave the sexp as `(partial filter neg?`.
Could this be the cause?
![a](https://user-images.githubusercontent.com/8780347/31295958-7589f17c-aa95-11e7-87b5-85fa924220c0.jpg)
*BTW, lispy has been one of the most important tools in my life for a long time.  Thank you for your work!*

**Comment by abo-abo** [comment]
> Could this be the cause?

It seems you're using Clojure. The piece of code in question is for Elisp, since it quotes single characters like this: `?a`, `?}`, `?\)`.
I've made the code apply to Elisp only now, thanks for the report.

> Thank you for your work!

I'm glad you like it. It's still a pretty obscure package, but it's my favorite one.

**Comment by adamdavislee** [comment]
Thanks for the update, but now the same problem exists regardless of the question mark.
I don't really understand the code, but for now I have modified my local copy by simply raising `(lispy-right-p)` one level.

**Comment by abo-abo** [comment]
OK, now that I got some sleep, I see that I messed up the logic last time.

Should be fixed now, I added a new test for that.

**Comment by adamdavislee** [comment]
Awesome! It works great now (that issue has been bugging me as a Clojure
programmer for a long time (in Clojure there is a strong convention of
suffixing boolean functions with a question mark)).  Again, I really
appreciate the work you put into Lispy!

**Comment by abo-abo** [comment]
> Awesome! It works great now (that issue has been bugging me as a Clojure programmer for a long time

Don't be shy to report issues like this. The reason this repository exists is that I want to make an awesome tool that's a pleasure to use for many people.

The reason for Clojure bugs is that I don't use Clojure actively. So I can't catch these bugs in my own use. But I'd still like to have those bugs fixed (if it's not too difficult).

**Comment by adamdavislee** [comment]
Will do, thanks!
