### ISSUE TITLE
lispy-delete-backwards broken in Common Lisp?

### ISSUE THREAD

**Issue by NSchweers** [abo-abo/lispy#378]
For a few days or so ```lispy-delete-backwards``` is broken for me in Common Lisp.  It unconditionally deletes one character to the left.  Still works fine in lisp-interaction-mode (i.e. the *scratch* buffer) though.

The built-in(?) function ```backward-kill-sexp``` works fine.

Any ideas what could cause this?

**Comment by abo-abo** [comment]
Caused by the last commit 7de90475f922ea1ec757c16bc96d704b2d876198. A branch was causing problems for clojure-mode, so I restricted it to only `lispy-elisp-modes`. Should I add `lisp-mode` to that list as well?

**Comment by NSchweers** [comment]
If it still works, sure.

**Comment by abo-abo** [comment]
For the most part you can, since the syntax of Common Lisp is similar to that of Emacs Lisp. But that variable is also tied to docstring lookup.

**Comment by NSchweers** [comment]
Thanks for the tip: ```(add-to-list 'lispy-elisp-modes 'lisp-mode)``` does the trick.  Should I beware that this will break future releases?

Also: thanks a lot for creating and releasing lispy and the quick reaction!

**Comment by abo-abo** [comment]
I'll make a proper fix a bit later, so you won't have to edit `lispy-elisp-modes`.

**Comment by abo-abo** [comment]
> Also: thanks a lot for creating and releasing lispy and the quick reaction!

You're welcome.

**Comment by noctuid** [comment]
Wouldn't it be better to have something like `lispy-character-escape-alist` for different major modes? Also, the check for Elisp should look for whitespace/opening delimiters. before the `?` (since `var?`, while not idiomatic, is still valid).

**Comment by abo-abo** [comment]
> Wouldn't it be better to have something like lispy-character-escape-alist for different major modes?

Of course. See my comment on #373: it would be nice to have something sane, customizable and extendable. But it's a lot of work to get it right. I hope we'll get there eventually.
