### ISSUE TITLE
Documentation suggestion: mention `lispy-define-key' in the customization section

### ISSUE THREAD

**Issue by brabalan** [abo-abo/lispy#38]
I use a non-qwerty keyboard layout, and I'm used to using the ijkl inverted triangle to move around (which correspond to the dtsr keys here).

I thus tweaked lispy's configuration to satisfy this, but I had to look at the code to figure out how to introduce a new special binding. It may be useful to mention it in the documentation.

Here is what I did:

``` emacs-lisp
(eval-after-load "lispy"
  `(progn
     ;; motion
     (lispy-define-key lispy-mode-map "s" 'lispy-down)
     (lispy-define-key lispy-mode-map "d" 'lispy-up)
     (lispy-define-key lispy-mode-map "t" 'lispy-left)
     (lispy-define-key lispy-mode-map "r" 'lispy-right)))
```

**Comment by abo-abo** [comment]
Fixed, thanks.
