### ISSUE TITLE
How to prevent lispy from adding a space before a `:`

### ISSUE THREAD

**Issue by diegovdc** [abo-abo/lispy#380]
I am using Clojure's Overtone library and it has many functions like this: `sin-osc:kr`.  With `lispy-mode` activated it becomes very difficult to type these functions, because it automatically adds a space after the `:` has been typed, like this `sin-osc :kr`. 

Is there a way to disable this feature?

Thanks

**Comment by sooheon** [comment]
Try `C-h k :`. This shows you that the key is bound to `lispy-colon`. If you don't like the behavior of lispy-colon, you can remove the binding in `lispy-mode-map`.

**Comment by abo-abo** [comment]
You can also customize `lispy-colon-no-space-regex` to your liking. It's already pre-customized for Common Lisp.

The default behavior is supposed to work nicely for Clojure when entering keywords, e.g. `(list :foo :bar)`.

**Comment by abo-abo** [comment]
@diegovdc Here's a setting specific to your request:

```elisp
(setq lispy-colon-no-space-regex
      '((clojure-mode . "sin-osc")))
```

Additionally, you can always type <kbd>C-q :</kbd>. <kbd>C-q</kbd> works for any key and in any package, `lispy` included.

**Comment by ahungry** [comment]
What's the best way to use the pre-customizations set up for Common Lisp in the Slime REPL?  (I'm enabling lispy in my slime-repl-mode-hook) - something as simple as `(ql:quickload :something)` is suspect to a similar issue (it becomes `(ql :quickload` and requires the manual deletion of the space there).

**Comment by vindarel** [comment]
> It's already pre-customized for Common Lisp.

I wanted to type ` sb-sys:foo`, no paren but a space before, and space is inserted before the colon. But it happens with many symbols, it is often I type a library name like this.

We can use Slime's completion to get the colon (`C-tab`). It is not always the most convenient.

Wouldn't it be easier to add a predicate to use this feature or not ?
