### ISSUE TITLE
lispy--read inconsistencies with clojure

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#381]
Indenting clojure code with `lispy-tab` runs the selected sexp through `lispy--normalize-1`, which calls `lispy--read`. This sometimes mangles clojure code.

ex) Characters

    (def whitespace {:space \space
                     :tab \tab
                     :newline \n})

`lispy-tab` leads to

    (def whitespace {:space space
                     :tab tab
                     :newline \n})

ex) ly-raw strings

    (repeatedly 10 (fn [] (java.time.Instant/now)))
    ;; =>
    ;; (#object[java.time.Instant 0x5c48ec8f (ly-raw string "\"2017-11-13T04:34:59.020Z\"")]
    ;;  #object[java.time.Instant 0x14ef8ecc (ly-raw string "\"2017-11-13T04:34:59.020Z\"")]
    ;;  #object[java.time.Instant 0x6d8fe98c (ly-raw string "\"2017-11-13T04:34:59.020Z\"")]
    ;;  #object[java.time.Instant 0x3e721c40 (ly-raw string "\"2017-11-13T04:34:59.020Z\"")]
    ;;  #object[java.time.Instant 0x2545a395 (ly-raw string "\"2017-11-13T04:34:59.020Z\"")]
    ;;  #object[java.time.Instant 0x4d34d01f (ly-raw string "\"2017-11-13T04:34:59.020Z\"")]
    ;;  #object[java.time.Instant 0x5f6583bc (ly-raw string "\"2017-11-13T04:34:59.020Z\"")]
    ;;  #object[java.time.Instant 0x715b040c (ly-raw string "\"2017-11-13T04:34:59.020Z\"")]
    ;;  #object[java.time.Instant 0x790a48b9 (ly-raw string "\"2017-11-13T04:34:59.020Z\"")]
    ;;  #object[java.time.Instant 0x12d5cbaf (ly-raw string "\"2017-11-13T04:34:59.021Z\"")])

**Comment by abo-abo** [comment]
Thanks, please test.
