### ISSUE TITLE
Unexpected behaviour of lispy-describe-inline

### ISSUE THREAD

**Issue by franburstall** [abo-abo/lispy#383]
I have two windows visible, one in lispy-mode and the other a help buffer.  In the lispy-mode window I hit C-1 to invoke `lispy-describe-inline`.

What I expected: to see an overlay with the doc-string of the current function.

What I actually get: the help window is deleted but no overlay appears. 

Looking at the code, it appears that some of this behaviour is intentional (the deletion of the help window) but that I should expect the overlay to appear and my window configuration be restored afterwards?

Also, why is it desirable to zap the help window?

**Comment by abo-abo** [comment]
> Also, why is it desirable to zap the help window?

When the docstring is too large (e.g. try it on `defcustom`), `lispy` can't display it inline anymore: it doesn't fit on a page, and there's no support for scrolling. So <kbd>C-1</kbd> will reuse a `*Help*` buffer instead. And as with the inline version, pressing <kbd>C-1</kbd> the second time will close the `*Help*` buffer.

What you reproduced is a flaw in `lispy-describe-inline` logic: it thinks that it produced the `*Help*` window, so now it should close it.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by franburstall** [comment]
Tested: issue completely fixed.

Many thanks.
