### ISSUE TITLE
(lispy--clojure-middleware-load) for cider-connect use case

### ISSUE THREAD

**Issue by FongHou** [abo-abo/lispy#384]
This commit [le-clojure.el (lispy--eval-clojure): Load middleware automatically](https://github.com/abo-abo/lispy/commit/148e51f078fd46061367a3bfbbe62fb398e3f4ff) removed 
(lispy--clojure-middleware-load) in a few places, seems only called for cider-jack-in. I normally run an external nrepl server, then cider-connect from emacs. (lispy--clojure-middleware-load) should be invoked for that use case also. Ctrl-1 and Ctrl-2 stop working after that commit.

Thanks!

**Comment by FongHou** [comment]
Here is one way.

(add-hook 'cider-connected-hook #'lispy--clojure-middleware-load)

**Comment by abo-abo** [comment]
Thanks.
