### ISSUE TITLE
Support for SPIRAL (clojure)

### ISSUE THREAD

**Issue by ccann** [abo-abo/lispy#385]
It would be awesome to have support for https://github.com/Unrepl/spiral in addition to CIDER for Clojure. It's based on the UNREPL protocol and it's a project that's getting quite a bit of attention.

**Comment by abo-abo** [comment]
Already available via:

```elisp
(setq lispy-clojure-eval-method 'spiral)
```

**Comment by ccann** [comment]
amazing!
