### ISSUE TITLE
error in process filter: lispy--clojure-middleware-load

### ISSUE THREAD

**Issue by ftravers** [abo-abo/lispy#389]
error in process filter: lispy--clojure-middleware-load

I think this is a lispy bug?  Not sure.

Seems like a whole bunch of dependencies are now required

                             [org.slf4j/slf4j-simple "1.6.2"]
                             [me.raynes/fs "1.4.6"]

Starting nREPL server via /bin/lein update-in :dependencies conj \[org.clojure/tools.nrepl\ \"0.2.13\"\ \:exclusions\ \[org.clojure/clojure\]\] -- update-in :plugins conj \[com.billpiel/sayid\ \"0.0.15\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.17.0-SNAPSHOT\"\] -- repl :headless :host ::...
nREPL server started on 36065
[nREPL] Establishing direct connection to localhost:36065 ...
[nREPL] Direct connection to localhost:36065 established
error in process filter: lispy--clojure-middleware-load: CompilerException java.io.FileNotFoundException: Could not locate cemerick/pomegranate__init.class or cemerick/pomegranate.clj on classpath., compiling:(/home/fenton/.emacs.d/elpa/lispy-20180119.1126/lispy-clojure.clj:1:1) 

error in process filter: CompilerException java.io.FileNotFoundException: Could not locate cemerick/pomegranate__init.class or cemerick/pomegranate.clj on classpath., compiling:(/home/fenton/.emacs.d/elpa/lispy-20180119.1126/lispy-clojure.clj:1:1)

**Comment by sp3ctum** [comment]
I think my issue https://github.com/abo-abo/lispy/issues/388 is related to this. Yesterday @abo-abo applied some patch, and now I actually avoid that issue and get a different one instead:

`CompilerException java.io.FileNotFoundException: Could not locate me/raynes/fs__init.class or me/raynes/fs.clj on classpath., compiling:(/home/mvilpas/.emacs.d/elpa/lispy-20180122.1022/lispy-clojure.clj:43:1) `

This happens when I do `cider-jack-in-clojurescript`. It happens regardless of whether my file is a .clj or .cljs file.

**Comment by sp3ctum** [comment]
As a workaround I can set this in /home/mvilpas/.emacs.d/elpa/lispy-20180122.1022/le-clojure.el

```lisp
(defvar lispy--clojure-middleware-loaded-p t ; was nil
  "Nil if the Clojure middleware in \"lispy-clojure.clj\" wasn't loaded yet.")
```

**Comment by abo-abo** [comment]
@ftravers Here's my `~/.lein/profiles.clj`:

```clojure
{:user {:dependencies [[org.slf4j/slf4j-simple "1.6.2"]
                       [org.tcrawley/dynapath "0.2.5"]
                       [com.cemerick/pomegranate "0.4.0"]]}
 :repl {:plugins [[cider/cider-nrepl "0.16.0"]]}}
```

`lispy-clojure.clj` doesn't have its own `project.clj` to declare dependencies; instead it relies on `pomegranate` to download and load the dependencies at runtime.

Let me know if adding the above dependencies fixes it for you.

@sp3ctum Thanks for the feedback, I'll have to try it one more time with a cljs file. Could you open a new issue with a sample repo and a couple steps?

**Comment by julienfantin** [comment]
IMO the dependency on `slf4j` is unfortunate. I just spent hours configuring a logging stack with log4j, logback, slf4j and clojure.tools.logging. That required carefully figuring out the right dependencies, versions, exclusions and inclusion order. It'd be a shame if a lispy dependency messed that up somehow.

Also the mechanism that cider uses to inject dependencies when jacking-in is extensible, and would save the user from having to tweak their profile:

```emacs-lisp
(defvar cider-jack-in-dependencies nil
  "List of dependencies where elements are lists of artifact name and version.")
```

**Comment by abo-abo** [comment]
@julienfantin Thanks for the pointer. Lispy now does this:

```elisp
(cider-add-to-alist 'cider-jack-in-dependencies
                    "org.tcrawley/dynapath" "0.2.5")
(cider-add-to-alist 'cider-jack-in-dependencies
                    "com.cemerick/pomegranate" "0.4.0")
```

My `~/.lein/profiles.clj` is now just:

```clojure
{:user {:plugins [[cider/cider-nrepl "0.16.0"]]}}
```

> IMO the dependency on slf4j is unfortunate.

There's no dependency actually. I just added it to my `profiles.clj` at some point because it was fixing some weird startup warning. It looks like it's no longer necessary.

**Comment by sp3ctum** [comment]
@abo-abo maybe we can keep using https://github.com/abo-abo/lispy/issues/388 ? I'll add a message there with some ideas later today.

**Comment by sp3ctum** [comment]
Oh, sorry! I hadn't refreshed this page and didn't see your most recent messages.
I'll try and see what happens with your latest changes.

**Comment by jtomazin** [comment]
I'm still having a very similar problem although with a different error in lispy-20180315.1216. When I open a Clojure file and try to evaluate the ns declaration with "e", I get the following error:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("\\`\"error: \\([^]+\\)\"\\'" nil)
  lispy--clojure-pretty-string(nil)
  lispy--eval-clojure-1("(load-file \"/Users/jtomazin/.emacs.d/elpa/lispy-20180315.1216/lispy-clojure.clj\")" nil)
  lispy--eval-clojure("(load-file \"/Users/jtomazin/.emacs.d/elpa/lispy-20180315.1216/lispy-clojure.clj\")")
  lispy--clojure-middleware-load()
  run-hooks(cider-connected-hook)
  cider--connected-handler()
  run-hooks(nrepl-connected-hook)
  nrepl-start-client-process(nil 61597 #<process nrepl-server>)
  nrepl-server-filter(#<process nrepl-server> "nREPL server started on port 61597 on host :: - nrepl://:::61597\n")
```

This seems to be the offending exchange in my \*nrepl-messages\* buffer:

```
(-->
  id         "9"
  op         "eval"
  session    "1c0fecec-c566-41f9-a66d-cfbc78f7e8da"
  time-stamp "2018-03-16 20:52:33.283739000"
  code       "(do (load-file "/Users/jtomazin/.emacs.d/elpa/lispy-20180315..."
  ns         "ddc9681b-7572-422e-bbed-24f93db11386"
)
(<--
  id         "9"
  session    "1c0fecec-c566-41f9-a66d-cfbc78f7e8da"
  time-stamp "2018-03-16 20:52:35.698973000"
  status     ("namespace-not-found" "done" "error")
)
(<--
  id         "9"
  session    "1c0fecec-c566-41f9-a66d-cfbc78f7e8da"
  time-stamp "2018-03-16 20:52:35.699670000"
  status     ("done")
```
If I modify my project.clj to have `:dependencies [[org.clojure/clojure "1.8.0"] [org.tcrawley/dynapath "0.2.5"] [com.cemerick/pomegranate "0.4.0"]]`
and then try to evaluate the `load-file` command in a `lein repl`, it loads correctly (albeit with some complaints about slf4j), so presumably this a dependency issue. Surprisingly, my `cider-jack-in-dependencies` are `(("com.cemerick/pomegranate" "0.4.0")
 ("org.tcrawley/dynapath" "0.2.5")
 ("org.clojure/tools.nrepl" "0.2.13"))`, so perhaps it's not -- I couldn't figure out how to dig any deeper.

I tried using the workaround in #388 to no success. I also tried using the `.lein/profiles.clj` above. 

I get the error in both GNU Emacs 25.3.1 (x86_64-apple-darwin16.7.0, Carbon Version 157 AppKit 1504.83) of 2018-03-12 and GNU Emacs 25.2.1 (x86_64-apple-darwin16.6.0, Carbon Version 157 AppKit 1504.83) of 2017-07-19.

Thanks for all the work you do on lispy!

**Comment by abo-abo** [comment]
@jtomazin Can you try running `make clojure` from a clone of this repository? It's a quick test to see if there's a problem on Clojure side.

By the way, here's my current `~/.lein/profiles.clj`:

```clojure
{:user {:plugins [[cider/cider-nrepl "0.16.0"]]}}
```

This code is already included in lispy to load the needed dependencies:

```elisp
(eval-after-load 'cider
  '(progn
    (cider-add-to-alist 'cider-jack-in-dependencies
     "org.tcrawley/dynapath" "0.2.5")
    (cider-add-to-alist 'cider-jack-in-dependencies
     "com.cemerick/pomegranate" "0.4.0")))
```

**Comment by jtomazin** [comment]
This version of lispy works! Thanks so much!

**Comment by NightMachinary** [comment]
@abo-abo @jtomazin I have the issue with newest versions of lispy and cider installed:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("\\`\"error: \\([^\0]+\\)\"\\'" nil)
  lispy--clojure-pretty-string(nil)
  lispy--eval-clojure-1("(lispy-clojure/complete \"pr\")" nil)
  lispy--eval-clojure("(lispy-clojure/complete \"pr\")")
  lispy-clojure-complete-at-point()
  completion--capf-wrapper(lispy-clojure-complete-at-point all)
  run-hook-wrapped(completion--capf-wrapper lispy-clojure-complete-at-point all)
  completion-at-point()
  indent-for-tab-command(nil)
  funcall-interactively(indent-for-tab-command nil)
  call-interactively(indent-for-tab-command nil nil)
  command-execute(indent-for-tab-command)
```

**Comment by abo-abo** [comment]
@NightMachinary Please open a new issue with versions and reproduction steps.

**Comment by NightMachinary** [comment]
@abo-abo Problem was solved with new MELPA update!
