### ISSUE TITLE
Eval isn't supported in `cider-scratch` buffers

### ISSUE THREAD

**Issue by bcarrell** [abo-abo/lispy#39]
Cider uses `cider-eval-print-last-sexp` (<kbd>C-j</kbd> by default) in `cider-scratch` buffers.

`lispy-eval` doesn't work here -- it throws `cider-clojure-interaction-mode is not supported currently`.

Is it possible to make `lispy-eval` work here as well?

**Comment by abo-abo** [comment]
I tend to like <kbd>E</kbd> in favor of <kbd>C-j</kbd>. What's your opinion?

**Comment by bcarrell** [comment]
I favor bare keys over chords in every situation where it makes sense.  <kbd>E</kbd> is definitely better.
