### ISSUE TITLE
A few ways to break a buffer

### ISSUE THREAD

**Issue by bcarrell** [abo-abo/lispy#40]
Here's an interesting situation I just ran into:

`(foo |"string )" "bar")`

`kill-word` does this:

`(foo )" "bar")` -- which, of course, leaves the buffer broken.

`kill-sentence` is also similar, which will do:

`(foo `

Do we need Lispy versions of `M-d` and `M-k`?

**Comment by abo-abo** [comment]
Yes, I see now that it's needed. Paredit provides a <kbd>M-d</kbd> binding, but not <kbd>M-k</kbd>.

I can add both, it's just that I'm not used to using these bindings.

**Comment by bcarrell** [comment]
Cool, no worries.  They're not common operations for me, which is why I only noticed now.  :smiley:

**Comment by abo-abo** [comment]
<kbd>M-k</kbd> killing until the end of string or list is really cool.
I'll try to use this now, instead of multiple <kbd>C-k</kbd>.

**Comment by bcarrell** [comment]
Sweet, that's an improvement.  Cool!  Thanks!
