### ISSUE TITLE
Recipe on MELPA excludes `lispy-clojure-test.clj`

### ISSUE THREAD

**Issue by blak3mill3r** [abo-abo/lispy#401]
I am using `straight.el`, which copies the files in the recipe into a `build/lispy` directory. Since only `lispy-clojure.clj`, and not `lispy-clojure-test.clj`, is in the recipe, it does not exist in the `build/lispy` directory, which causes this to fail:

https://github.com/abo-abo/lispy/blob/master/lispy-clojure.clj#L588-L591

I imagine this would also happen for other users of `straight.el` with this recipe, but I have not tested it with `package.el` or any other package manager.

This change fixes it for me
https://github.com/blak3mill3r/melpa/commit/90eb180b84fc4c5647b6aacaba06443130f41944

Without that, I don't get the `lispy` + `cider` features.

If this makes sense to you, I will make a PR out of that ^

**Comment by raxod502** [comment]
The file `lispy-clojure-test.clj` is not included in the MELPA package, either.

**Comment by abo-abo** [comment]
The idea is not to include test files in MELPA, that's why MELPA doesn't bundle files that end in `-test` by default.

I've added a file existence check. Please let me know if it fixes your problem.

**Comment by blak3mill3r** [comment]
Yes, that fixes it, thank you. I was mistakenly thinking that the file was required functionality in spite of the name `-test`, since `lispy-clojure.clj` was throwing without it.
