### ISSUE TITLE
lispy-tab mangles #: in Scheme

### ISSUE THREAD

**Issue by Ambrevar** [abo-abo/lispy#404]
Recipe in `scheme-mode`:
```
(define-module (gnu packages hello)
  #:use-module (guix packages))
```
Now press `i` on the first parenthesis: the `#:` disappears while it should not.  (Unless I'm missing something.)

**Comment by abo-abo** [comment]
Can you point me to a place in the Scheme spec where `#:use-module`'s syntax is described? I can't find it anywhere. It looks a bit like Elisp or Clojure keyword syntax, but it's not self-evaluating.

**Comment by abo-abo** [comment]
Thanks, should be fixed now.

**Comment by Ambrevar** [comment]
Sure, see the Guile manual: https://www.gnu.org/software/guile/manual/html_node/Using-Guile-Modules.html.
