### ISSUE TITLE
lispy-ace-symbol* operations working incorrectly

### ISSUE THREAD

**Issue by bcarrell** [abo-abo/lispy#41]
<kbd>a</kbd> and <kbd>H</kbd> can't target the first element or symbol of some structures:  square brackets (vectors), curly braces (maps), maybe more?

It targets the entire vector instead of the first symbol.  Every element after the first works correctly.

`|(let [x 1] x)` --> <kbd>a</kbd> --> `a(let b[x c1] dx)`

<kbd>b</kbd> will select the entire vector instead of the `x`.  </kbd>acd</kbd> will correctly select the symbol.

Quoted lists give you an extra target for the quote, which then selects the entire list.  Not sure if that's necessarily a problem, but since the operation is advertised as symbols, it should probably be impossible to get an entire list region activated from `lispy-ace-symbol`.

**Comment by abo-abo** [comment]
You're right, it's a bug. Braces, brackets, and quoted lists aren't working properly.
I'll try to fix this soon.

**Comment by bcarrell** [comment]
Its easy enough to workaround it for now by pressing <kbd>i</kbd> after selecting the list.

**Comment by bcarrell** [comment]
Another one is symbols like `~sym`.  `lispy-ace-symbol*` doesn't target this.
