### ISSUE TITLE
Unwrap?

### ISSUE THREAD

**Issue by mfiano** [abo-abo/lispy#412]
How do I do the equivalent of smartparens' sp-unwrap-sexp? Also wrapping. With evil-lisp-state/smartparens I only needed to type `w` for wrap and `W` for unwrap...2 things I use constantly that I can't figure out how to do in lispy.

**Comment by noctuid** [comment]
I think you are looking for `lispy-splice` (`/`). You can use `(` with a prefix argument to wrap or `lispy-wrap-round`, for example.

**Comment by mfiano** [comment]
Hmm, I sort of really miss just being able to type `w` to wrap `(_first second)` into `((first) second)`. Also the opposite operation mnemonically bound and a single keypress for each. Maybe I'll need to get used to this, but I don't see it as a benefit just yet...

**Comment by noctuid** [comment]
With evil lisp state, you don't just type `w` to wrap something, you have to get into or be in evil lisp state first. Just bind the same key sequence you would have used to `lispy-wrap-round` instead if you want to keep this behavior. Alternatively (e.g. you're not on the symbol you want to wrap), you could mark whatever symbol you want to wrap with `lispy-ace-symbol` (`a`) and then press `(`.
