### ISSUE TITLE
Clojure hashes inside macros add a space

### ISSUE THREAD

**Issue by bcarrell** [abo-abo/lispy#42]
Here's a fun one for you for a rainy day.  It's a sufficiently rare scenario so as not to be an immediate concern, but symbols like `foo#` are valid (syntactical sugar) symbols (they're gensyms) within Clojure macros.

But you can't actually type in `foo#`, since Lispy will automatically insert a space after `foo`.  So you have to <kbd>C-b</kbd><kbd>DEL</kbd> to bump the hash over.

This is probably fairly challenging to fix without breaking other functionality, but you be the judge.

**Comment by abo-abo** [comment]
See if this is sufficient: typing <kbd>##</kbd> will do a gensym literal.
I think the old behavior for lambda and set literals should stay.

**Comment by bcarrell** [comment]
Same behavior with things like `~'symbol`, also present in macros.

**Comment by bcarrell** [comment]
This looks to be working properly; feel free to close whenever.
