### ISSUE TITLE
Lots of 'require statements

### ISSUE THREAD

**Issue by mookid** [abo-abo/lispy#421]
It seems that the bunch of `require` statements on top of lispy.el slows down the startup of emacs (on my machine, with and without lispy: 3.2s / 2.5s)

Putting all `require`s inside the `eval-when-compile` makes all this time go away (but it may be incorrect). Is that possible to improve on that?

**Comment by jojojames** [comment]
+1, Lispy adds about .3 seconds to startup time given all the require statements.

**Comment by alphapapa** [comment]
I guess this was fixed in https://github.com/abo-abo/lispy/pull/428
