### ISSUE TITLE
Using lispy with geiser

### ISSUE THREAD

**Issue by dieggsy** [abo-abo/lispy#423]
Is using lispy in the geiser repl supported? I've been trying it out, but find that after a while (still not sure what triggers it) I can't actually type parentheses anymore, and typing `(` just makes my cursor jump to the beginning of the line, _before_ the repl prompt.

**Comment by noctuid** [comment]
See #413 and #371. You can manually alter `lispy--indent-for-tab` to fix this issue if you want.

**Comment by dieggsy** [comment]
Cool, thanks.

**Comment by NightMachinary** [comment]
Has this been solved?

**Comment by abo-abo** [comment]
Seems so. I can enter parens in the REPL fine.
