### ISSUE TITLE
FileNotFoundException when connecting to remote

### ISSUE THREAD

**Issue by jcf** [abo-abo/lispy#429]
I'm connecting to a running REPL via an SSH connection using `cider-connect`. The following error shows up in Emacs when I connect:

```
if: FileNotFoundException /home/jcf/.emacs.d/.local/packages/elpa/lispy-20180504.956/lispy-clojure.clj (No such file or directory)  java.io.FileInputStream.open0 (FileInputStream.java:-2)
```

It looks like Lispy is injecting something into my Clojure environment, and is trying to load files from inside my `emacs.d`, which isn't on the server I'm connecting to.

**Comment by abo-abo** [comment]
The file being injected is in the directory `lispy-site-directory`. Which is related to the `load-file-name` of your `lispy.el`. So if your `lispy.el` is local, `lispy-clojure.clj` should be local as well.

What's your value of `lispy-site-directory`?

**Comment by jcf** [comment]
`lispy-site-directory` is `"/home/jcf/.emacs.d/.local/packages/elpa/lispy-20180511.1259/"`. That's on my host, and not available inside the guest where the REPL is running.

**Comment by abo-abo** [comment]
Let's try to re-use CIDER to load a local file into a remote process:

```elisp
(defun lispy--clojure-middleware-load ()
  "Load the custom Clojure code in \"lispy-clojure.clj\"."
  (unless lispy--clojure-middleware-loaded-p
    (setq lispy--clojure-ns "user")
    (cider-load-file (expand-file-name "lispy-clojure.clj" lispy-site-directory))
    (setq lispy--clojure-middleware-loaded-p t)
    (add-hook 'nrepl-disconnected-hook #'lispy--clojure-middleware-unload)
    (let ((sources-expr
           (format
            "(do \n  %s)"
            (mapconcat
             (lambda (p) (format "(cemerick.pomegranate/add-classpath %S)" p))
             cider-jdk-src-paths
             "\n  "))))
      (lispy--eval-clojure sources-expr))))
```

Does the above version of `lispy--clojure-middleware-load` work for you?

**Comment by jcf** [comment]
Evaluated that snippet and no more error! Completion works as expected etc.

**Comment by abo-abo** [comment]
You're welcome. Thanks for reporting and verifying.
