### ISSUE TITLE
Please stop automatically doing a cider-jack-in

### ISSUE THREAD

**Issue by danieroux** [abo-abo/lispy#431]
When I open a clojure file / project `completion-at-point-functions` gets `lispy-clojure-complete-at-point` added to it.

Which then calls `lispy--eval-clojure` - and this does a magical cider-jack-in.

Which means that I quickly have 10 or so Java processes running, all desperately trying to do a cider-jack-in.

What about my setup causes this? How can I stop it from doing it? I would only want completion via cider, if I explicitly started cider myself.

**Comment by abo-abo** [comment]
Thanks for the report.

> What about my setup causes this?

Might be `company-mode` which uses `completion-at-point-functions` as a source.

> How can I stop it from doing it?

It's fixed now: `lispy-clojure-complete-at-point` will only use CIDER if it's already loaded.
