### ISSUE TITLE
Use `counsel-imenu` as a fallback in `G`

### ISSUE THREAD

**Issue by Andre0991** [abo-abo/lispy#432]
Using `G` in a Clojure file won't work unless the user has Semantic enabled (or something like that).

I think using `counsel-imenu` as a fallback mechanism would be a good default.

**Comment by Andre0991** [comment]
Similarly, `V` could use `projectile-find-file` if it exists.

**Comment by mpereira** [comment]
Until a fallback is added to lispy, this could be useful:
```elisp
(with-eval-after-load "counsel"
  (with-eval-after-load "lispy"
    ;; `lispy-goto-local' doesn't work in org babel indirect src block buffers.
    (defun mpereira/lispy-goto-local (&optional args)
      "lispy-goto-local with fallback to counsel-imenu."
      (interactive)
      (if (lispy--file-list)
          (funcall 'lispy-goto-local args)
        (funcall 'counsel-imenu)))))
```

**Comment by abo-abo** [comment]
Thanks, `counsel-imenu` is used as a fall-back now.

> Similarly, V could use projectile-find-file if it exists.

This is already the case. See `lispy-visit-method`.

**Comment by mpereira** [comment]
Thanks @abo-abo!
