### ISSUE TITLE
`lispy-bind-variable` in Clojure

### ISSUE THREAD

**Issue by Andre0991** [abo-abo/lispy#433]
Seems that `lispy-bind-variable` works only for Emacs Lisp.

The implementation doesn't look complicated, but I haven't been able to modify it to correctly handle Clojure code.

I just replaced

``` emacs-lisp
(insert (format "(let [  %s]\n)" str))
```

by

``` emacs-lisp
(if (eq major-mode 'clojure-mode)
  (insert (format "(let [  %s]\n)" str))
  (insert (format "(let (( %s))\n)" str)))
```

but the result was a bit off:

``` emacs-lisp
(let [ foo (active agreement)]
             foo)
```

Perhaps I can create a PR with some guidance.

**Comment by Andre0991** [comment]
Oh, actually, `lispy` could use some `[clj-refactor](https://github.com/clojure-emacs/clj-refactor.el/wiki)` function for that.
I'll have a look at this later.

**Comment by abo-abo** [comment]
> I'll have a look at this later.

Thanks in advance.

**Comment by Andre0991** [comment]
Well, I decided to actually bind the `clj-refactor` prefix to a key in `lispy-mode-map` so I can easily call its commands.

To be more precise, I bound `,`, which displays the commands for the current major mode in Spacemacs.

For reference, here's the code:

```
(defun display-clj-mode-which-key ()
    (interactive)
    (evil-normal-state)
    (forward-char)
    (setq unread-command-events
          (listify-key-sequence (kbd ","))))

(eval-after-load "lispy"
  `(progn (lispy-define-key lispy-mode-map "," 'display-clj-mode-which-key)))
```

**Comment by abo-abo** [comment]
Thanks, `lispy-bind-variable` now also works for Clojure.
