### ISSUE TITLE
Clojure akward insertion of auto-gensym.

### ISSUE THREAD

**Issue by WebsterWing** [abo-abo/lispy#434]
When using let inside of a macro, placing a # a the end of a word to create an auto-gensym inserts a space. This is undesired behavior.

## before pressing \#
(`|` denotes point)
```clojure
(defmacro new-or
  ([] false)
  ([x] x)
  ([x & xs]
   `(let (new-or|))))
```

## after pressing \#
```clojure
(defmacro new-or
  ([] false)
  ([x] x)
  ([x & xs]
   `(let (new-or #|))))
```
## desired behavior
```clojure
(defmacro new-or
  ([] false)
  ([x] x)
  ([x & xs]
   `(let (new-or#|))))
```
This creates an auto-gensym, which is a feature of clojure's macro system. I think that adding spaces before inserting characters such as \# is just asking to run into edge cases like this one.

**Comment by abo-abo** [comment]
The purpose of the extra space is that you more likely want to insert `#(...)` or `#{...}` intead.

The gensym edge case is already covered: by pressing <kbd>#</kbd> the second time you get your desired behavior.
