### ISSUE TITLE
lispy-undo and undo-tree

### ISSUE THREAD

**Issue by jojojames** [abo-abo/lispy#436]
When using lispy and evil/undo-tree together, using lispy-undo seems to ~sometimes~ corrupt undo state.

Haven't nailed down a repro but I thought I'd post an issue up in case others are seeing it too.

I've been redeclaring lispy-undo as a hack to use undo-tree.

```
(defun lispy-undo ()
    "Deactivate region and `undo'."
    (interactive)
    (when (region-active-p)
      (deactivate-mark t))
    (undo-tree-undo))
```

which seems to fix the issue for me.

**Comment by yuhan0** [comment]
For what it's worth, I encountered the same issue when trying to undo in the middle of a `lispy-bind-variable` command, and used this fix:

```elisp
(with-eval-after-load 'undo-tree
  ;; attempting to undo in middle of a lispy overlay operation
  ;; irreversibly corrupts the undo tree state
  (defadvice undo-tree-undo (around disable-lispy-overlay activate)
    (lispy-map-delete-overlay)
    ad-do-it))

```
