### ISSUE TITLE
CIDER changed its connection API

### ISSUE THREAD

**Issue by bandresen** [abo-abo/lispy#439]
https://github.com/clojure-emacs/cider/commit/5cb98a74bad81a2cd15f8db86c469020ed030156

Currently getting both lispy and cider from MELPA is not compatible.

For example the `cider-default-connection` was dropped which le-clojure.el uses.

**Comment by bandresen** [comment]
@abo-abo Thanks! I can confirm it works with the latest available CIDER from Melpa (20180628.628)

**Comment by eipplusone** [comment]
`lispy-goto` need to be reviewed too:

Call it to go to a function in the core, it will go to the right source file but since that new buffer hasn't been sesman linked, it breaks(for example you can't go to `defn` definiton.)

**Comment by eipplusone** [comment]
On a second thought, I'm not sure there's a good way to do this:

Simple approach:

```(defun lispy-goto-symbol-clojure (symbol)
  "Goto SYMBOL."
  (lispy--clojure-detect-ns)
  (let* ((r (read (lispy-eval-clojure
                   (format "(lispy-clojure/location '%s)" symbol))))
         (url (car r))
         (line (cadr r))
         archive)
    (cond
      ((file-exists-p url)
       (find-file url)
       (lispy-goto-line line))
      ((and (string-match "\\`file:\\([^!]+\\)!/\\(.*\\)\\'" url)
            (file-exists-p (setq archive (match-string 1 url))))
       (let ((path (match-string 2 url)))
         (lispy-find-archive archive path)
         (lispy-goto-line line)
++    (link-new-buffer-with-sessman)))
      (t
       (warn "unexpected: %S" symbol)
       (cider-find-var symbol)))))
```

link-new-buffer-with-sessman could be either:

- (call-interactively 'sesman-link-with-buffer), which I dislike because it prompts
- Borrow some logic from sesman--link-session-interactively:
```(defmacro sesman--link-session-interactively (cxt-type)
  (declare (indent 1)
           (debug (symbolp &rest)))
  (let ((cxt-name (symbol-name cxt-type)))
    `(let ((system (sesman--system)))
       (if (member ',cxt-type (sesman-context-types system))
           (let ((session (sesman-ask-for-session
                           system
                           (format "Link with %s %s: "
                                   ,cxt-name (sesman--abbrev-path-maybe
                                              (sesman-context ',cxt-type)))
                           (sesman--all-system-sessions system)
                           'ask-new)))
             (sesman--link-session system session ',cxt-type))
         (error (format "%s association not allowed for this system (%s)"
                        ,(capitalize (symbol-name cxt-type))
                        system))))))
```

Which imo non-ideal because borrowing unstable logic from a lib is what got lispy this problem in the first place.

Thoughts @abo-abo?

**Comment by abo-abo** [comment]
@bandresen Thanks for testing, I'm closing this issue.
@eipplusone `lispy-goto` works fine for me to go to the definition of `defn`, as of CIDER commit 24db03d135475c9f451ad1b7bbe16d3ec8ddfe3a. If that's not the case for you, please open a new issue with all versions and repro steps etc.

**Comment by abo-abo** [comment]
@eipplusone I meant `lispy-follow`, not `lispy-goto`.
