### ISSUE TITLE
lispy-splice-sexp-killing-backward forwarding to lispy-raise

### ISSUE THREAD

**Issue by jojojames** [abo-abo/lispy#440]
Given:

```
(progn
  (1)
  |(2)
  (3))
```

Expected:
```
|(2)
(3)
```

Result:
```
|(2)
```

I think lispy-raise-some has a combo functionality between lispy-splice-sexp-filling-forward and backward but it would be awesome to have the two functionalities in two distinct functions too.

Thanks!

**Comment by abo-abo** [comment]
Thanks. If you notice any more Paredit emulation inconsistencies, let me know.
