### ISSUE TITLE
Conflict with magit-blame mode "funcall-interactively: Buffer is read-only"

### ISSUE THREAD

**Issue by dangirsh** [abo-abo/lispy#443]
When running `magit-blame` in buffers with `lispy-mode` enabled, I'm unable to use any of the `magit-blame` nagivation commands. When I try, I get a "funcall-interactively: Buffer is read-only:" error. 

Not sure what changed in magit or lispy, or if this was always there.

A quick fix:

```emacs-lisp
(add-hook 'magit-blame-mode-hook #'(lambda () (lispy-mode -1)))
```

IIRC Multiple-cursors has a mechanism to disable conflicting minor modes, which seems relevant here.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d9eecb760)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: emacs
- Completion: helm
- System configuration features: XPM JPEG GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS

**Comment by abo-abo** [comment]
See `lispy-compat` variable, customizing it should fix your issue.

**Comment by dangirsh** [comment]
Works, thanks!

For reference, I now have:

```emacs-lisp
(setq lispy-compat '(edebug magit-blame-mode))
```

**Comment by abo-abo** [comment]
OK, closing.
