### ISSUE TITLE
lispy-mode-map-paredit / cp M-<down> forwards to lispy-splice-sexp-killing-backward

### ISSUE THREAD

**Issue by jojojames** [abo-abo/lispy#445]
I think paredit, there is the 'killing-forward' version instead of backwards.

I think it's equivalent to lispy-raise-some if point is after the paren.

((a)
 (b)|
 (c))

(a)
(b)|

**Comment by abo-abo** [comment]
Sorry, it's not clear what you mean by `cp M-<down>`.

**Comment by jojojames** [comment]
Sorry, it's the two keymaps (paredit and evil-cp).

(define-key map (kbd "M-<down>") 'lispy-splice-sexp-killing-backward)
lispy-mode-map-paredit & lispy-mode-map-evilcp

**Comment by abo-abo** [comment]
OK, as far a I see here, `lispy-splice-sexp-killing-backward` is equivalent to `paredit-splice-sexp-killing-forward`, at least for the example given in paredit's docstring:

    (a (b c| d e) f)
      ->
    (a b c| f)

And they're bound to the same key - `M-<down>`. So what's the discrepancy?

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by jojojames** [comment]
Thanks @abo-abo. Works for me.
