### ISSUE TITLE
Could not locate cemerick/pomegranate__init.class or cemerick/pomegranate.clj on classpath.

### ISSUE THREAD

**Issue by NightMachinary** [abo-abo/lispy#446]
```
CompilerException java.io.FileNotFoundException: Could not locate cemerick/pomegranate__init.class or cemerick/pomegranate.clj on classpath., compiling:(/Users/evar/.emacs.d/elpa/27.0/develop/lispy-20180806.909/lispy-clojure.clj:1:1) 
```
I am using the latest packages from MELPA.

**Comment by NightMachinary** [comment]
I took a look at https://github.com/abo-abo/lispy/issues/389, and it seems there is a regression; My `cider-jack-in-dependencies` didn't have Lispy dependencies. I am adding them manually in my dotfile now.

**Comment by gypsydave5** [comment]
I'm still getting this as of today (not been developing on Clojure for a while).

**Comment by abo-abo** [comment]
`cider-jack-in-dependencies` are now set up automatically. Thanks for the report, closing.
