### ISSUE TITLE
`lispy-kill-word` jumps out when killing last word

### ISSUE THREAD

**Issue by bcarrell** [abo-abo/lispy#45]
`(foo "|bar")`

Here's what `lispy-kill-word` does:

`(foo "")|`

Here's what I wish `lispy-kill-word` did:

`(foo "|")`

Because in most cases I want to replace the word with another.  Even if I didn't, I probably don't want an empty string left in there.

I can probably fix this and send a PR if you want to do other things.

**Comment by abo-abo** [comment]
Fixed, thanks.
