### ISSUE TITLE
cider-interaction.el was renamed to cider-eval.el 

### ISSUE THREAD

**Issue by tarsius** [abo-abo/lispy#450]
See https://github.com/clojure-emacs/cider/commit/ac9cb611f422f1133a9520efa469687c0cd3af18
and https://github.com/clojure-emacs/cider/issues/2203.

**Comment by abo-abo** [comment]
Thanks, the eval seems to work now with cider@67af6586659106accb25fc20b7853a3aa5a9e13b.

**Comment by tarsius** [comment]
Thanks!
