### ISSUE TITLE
Were can I get mash-python

### ISSUE THREAD

**Issue by tarsius** [abo-abo/lispy#451]
Still looking into unsatisfied dependencies of packages mirrored on the Emacsmirror...

Where can I get `mash-python`?

**Comment by abo-abo** [comment]
It's not released yet. It's used as `(require 'mash-python nil t)`, so it's a soft optional dependency.

**Comment by tarsius** [comment]
Ups, just noticed I asked about this before: https://github.com/abo-abo/lispy/issues/377.

In my defense, clicking on `[[https://github.com/abo-abo/lispy/issues/377][#377]]` took me to https://github.com/emacsmirror/epkg-reports/issues/377, which doesn't exist, thanks to `bug-reference-mode` (which I now have to teach not to linkify already linkified text, oh boy).
