### ISSUE TITLE
Eval in clojure file: No such namespace: p

### ISSUE THREAD

**Issue by sp3ctum** [abo-abo/lispy#453]
Hello, I'm getting back to clojure after a while. I am using spacemacs and updated to the current stable cider. However, when I open up a clojure file and do `special-lispy-eval`, I get this error:

```
[nREPL] Starting server via /home/mvilpas/bin/lein update-in :dependencies conj \[com.cemerick/pomegranate\ \"0.4.0\"\] -- update-in :dependencies conj \[org.tcrawley/dynapath\ \"0.2.5\"\] -- update-in :dependencies conj \[org.clojure/tools.nrepl\ \"0.2.13\"\ \:exclusions\ \[org.clojure/clojure\]\] -- update-in :plugins conj \[refactor-nrepl\ \"2.4.0\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.18.0\"\] -- repl :headless :host ::...
=> Starting CIDER...
[nREPL] server started on 40485
[nREPL] Establishing direct connection to localhost:40485 ...
[nREPL] Direct connection to localhost:40485 established
=> nil
CompilerException java.lang.RuntimeException: No such namespace: p, compiling:(/tmp/form-init2567082953579246522.clj:1:5) 
```

I see there is some additional things for clojure in lispy that I'm not familiar with. If you have any idea on what could be done about this, that would be great.

**Comment by sp3ctum** [comment]
Here are some of my used versions:
- lispy-20180909.1729
- Spacemacs v.0.200.11
- GNU Emacs 25.2.1 (x86_64-redhat-linux-gnu, GTK+ Version 3.20.10) of 2017-05-02

My ~/.lein/profiles
```
{:user
 {:plugins [[cider/cider-nrepl "0.18.0"]
            [refactor-nrepl "2.4.0"]]
  :dependencies []}}
```

**Comment by sp3ctum** [comment]
Hmm, it looks like the error went away. I will keep trying for a while and report if it comes back.

**Comment by abo-abo** [comment]
Thanks.

**Comment by sp3ctum** [comment]
I see refactor-nrepl mentioned there. Maybe there is some sort of incompatibility?

**Comment by abo-abo** [comment]
I can't reproduce the issue with the latest CIDER `master` (clojure-emacs/cider@7008a33).

It looks like "com.cemerick/pomegranate" isn't on your path, although lispy does load it with:

```elisp
(eval-after-load 'cider
  '(progn
    (cider-add-to-alist 'cider-jack-in-dependencies
     "org.tcrawley/dynapath" "0.2.5")
    (cider-add-to-alist 'cider-jack-in-dependencies
     "com.cemerick/pomegranate" "0.4.0")))
```

Can you try to restart with this config:

```elisp
(setq cider-default-repl-command "lein")
```

**Comment by sooheon** [comment]
I came across this as well, I `cider-jack-in-dependencies` does not seem to work properly when `cider-jack-in-default` is `clojure-cli`.

I just added pomegranate to global deps.edn for now

**Comment by abo-abo** [comment]
@sooheon Could you please add a description of this global deps.edn modification?
I could at least add a warning to lispy about it.

**Comment by sooheon** [comment]
Clarification: if I start by `e`valing a form and let lispy do the jack-in for me, pom gets added correctly. If I forget and jack in with C-c M-j, then nothing extra gets added so I need pom in `~/.clojure/deps.edn` like so:

```
{:dependencies {com.cemerick/pomegranate {:mvn/version "RELEASE"}
 [...]}
```

This is not ideal, because you never know when global deps will mess with something, so it's probably better to put it in an alias and have cider use that alias by default.

**Comment by abo-abo** [comment]
@sooheon Thanks, I've made it better for your use case. You no longer need to modify `~/.clojure/deps.edn`. Please test.

**Comment by sooheon** [comment]
Thanks, this resolves the issue afaict

**Comment by abo-abo** [comment]
Thanks, closing. If any issues pop up, please let me know.
