### ISSUE TITLE
 Could not locate compliment/core__init.class or compliment/core.clj on classpath.

### ISSUE THREAD

**Issue by danielcnorris** [abo-abo/lispy#454]
I'm new to Clojure and am trying to use lispy with CIDER. 

Whenever I try to evaluate a sexp with CIDER (`e`), I get:

```
  Show: Project-Only All 
  Hide: Clojure Java REPL Tooling Duplicates  (16 frames hidden)

2. Unhandled clojure.lang.Compiler$CompilerException
   Error compiling /Users/daniel/.emacs.d/elpa/lispy-20180914.1838/lispy-clojure.clj at (40:1)

             Compiler.java: 7391  clojure.lang.Compiler/load
                      REPL:    1  user/eval5349
                      REPL:    1  user/eval5349
             Compiler.java: 6927  clojure.lang.Compiler/eval
             Compiler.java: 6890  clojure.lang.Compiler/eval
                  core.clj: 3105  clojure.core/eval
                  core.clj: 3101  clojure.core/eval
                  main.clj:  240  clojure.main/repl/read-eval-print/fn
                  main.clj:  240  clojure.main/repl/read-eval-print
                  main.clj:  258  clojure.main/repl/fn
                  main.clj:  258  clojure.main/repl
                  main.clj:  174  clojure.main/repl
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   87  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
                  AFn.java:  152  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
                  core.clj:  646  clojure.core/apply
                  core.clj: 1881  clojure.core/with-bindings*
                  core.clj: 1881  clojure.core/with-bindings*
               RestFn.java:  425  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   85  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   55  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  222  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
    interruptible_eval.clj:  190  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                  AFn.java:   22  clojure.lang.AFn/run
   ThreadPoolExecutor.java: 1135  java.util.concurrent.ThreadPoolExecutor/runWorker
   ThreadPoolExecutor.java:  635  java.util.concurrent.ThreadPoolExecutor$Worker/run
               Thread.java:  844  java.lang.Thread/run

1. Caused by java.io.FileNotFoundException
   Could not locate compliment/core__init.class or compliment/core.clj
   on classpath.
```

Caused by these lines in `lispy-clojure.clj`. I understand that pomegranate is being used to pull extra dependencies, but it looks like this is not happening. 

```
(use-package 'compliment "0.3.5")
(require '[compliment.core :as compliment])
```

I'm running macos 10.13.4, emacs 26.1, Java 10.0.2, Clojure 1.9.0, and Leiningen 2.8.1.

Here's a minimal `init.el` I'm using to test:

```
;;; package --- summary:
;;; Commentary:
;;; Code:
(setq custom-file "~/.emacs.d/custom.el")

(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(require 'use-package)

(use-package exec-path-from-shell
  :if (memq window-system '(mac ns x))
  :ensure t
  :config
  (exec-path-from-shell-initialize))

(use-package clojure-mode
  :ensure t)

(use-package cider
  :ensure t)

(use-package lispy
  :ensure t
  :after (cider)
  :hook ((emacs-lisp-mode . lispy-mode)
         (clojure-mode . lispy-mode))
  :init
  (setq lispy-compat '(edebug cider)))

(provide 'init)
;;; init.el ends here
```

I was expecting it to work out of the box -- are there additional steps required? It looks like other issues have reported something that may be related. 

Thanks for your amazing work!

**Comment by danielcnorris** [comment]
Same issue on arch Linux. Pomegranate downloads the jars but isn't able to load them for some reason.

**Comment by abo-abo** [comment]
Could you try customizing `(setq cider-default-repl-command "lein")` and restarting?

**Comment by MC-Escherichia** [comment]
I'm having the same issue on arch linux and setting cide-default-repl-command did not help.

**Comment by abo-abo** [comment]
@danielcnorris Thanks for the full init file. Here's what I ran:

    emacs -Q -l init.el

Versions:

- GNU Emacs 26.1
- CIDER 0.18.1snapshot (package: 20180917.1746)
- nREPL 0.2.12
- Clojure 1.8.0, Java 1.8.0_181

I opened a Clojure file in a project.clj repo. `lispy-mode` was already on. Normally, I would just start the REPL with <kbd>e</kbd>, but this time I did `cider-jack-in`. Everything works.

Here's my `~/.lein/profiles.clj`:

```clojure
{:user {:dependencies [[org.slf4j/slf4j-simple "1.6.2"]]
        :resource-paths []}
 :repl {:plugins [[cider/cider-nrepl "0.18.0"]
                  [refactor-nrepl "2.4.0"]]}}
```

Let me know if you can reproduce the issue with similar versions. Or just provide the versions for which you can reproduce it.

**Comment by danielcnorris** [comment]
I removed clojure, leiningen, and `~/.emacs.d/elpa/`; did a fresh `brew install clojure` and `brew install leiningen`; ran `emacs -Q -l ~/.emacs.d/init.el` (using the init file above); and have now the following versions:

- MacOS 10.13.4
- GNU Emacs 26.1
- CIDER 0.18.1snapshot (package: 20180923.1759)
- Clojure 1.8.0 in my test project; I also have 1.9.0 installed on my machine
- nREPL 0.2.12
-  java 10.0.2 2018-07-17 (`java --version`)

I created a test lein project `lein new test`, found `./test/src/test/core.clj` and ran `cider-jack-in`. The REPL starts, but when I hit `e` on a sexp, it gives the above error. 

If I disable Lispy Mode and then use the default CIDER bindings (on the same REPL), I'm able to evaluate the forms no problem.

It sounds like CIDER doesn't require modifying `~/.lein/profiles.clj` for the default use case. I currently don't have a version of that file. Maybe using Lispy requires some extra configuration.

I added your `~/.lein/profiles.clj` and got the same issue. (Well, first it complained about not finding pomegranate. Then I restarted Emacs and got the original compliment error.)

Let me know if I can provide better information or change my Java installation for a better comparison / repro. Thanks!

**Comment by abo-abo** [comment]
@danielcnorris 
Tried with `lein new test`, still can't reproduce. What is your version of `lein`, btw?

Could you give me the startup message that `cider-jack-in` gives you? Here's mine:

```
[nREPL] Starting server via /usr/local/bin/lein update-in :dependencies conj \[com.cemerick/pomegranate\ \"0.4.0\"\] -- update-in :dependencies conj \[org.tcrawley/dynapath\ \"0.2.5\"\] -- update-in :dependencies conj \[nrepl\ \"0.4.5\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.18.0\"\] -- repl :headless :host ::...
[nREPL] server started on 45111
[nREPL] Establishing direct connection to localhost:45111 ...
[nREPL] Direct connection to localhost:45111 established
```

Note how `[com.cemerick/pomegranate "0.4.0"]` is already injected automatically, even if it's not in my `~/.lein/profiles.clj`.
This is because `lispy` modifies `cider-jack-in-dependencies` on load. Could you also post the value of this variable?

**Comment by danielcnorris** [comment]
OK I've confirmed that this is a Java issue. Lispy works fine with Java 8, but gets the above error when using Java 10. I have a Dockerfile I can share if that would be useful. I'm very new to the JVM, but will see if I can figure out how to make it work on Java 10. Otherwise, it would be helpful to document that only Java 8 (or 9, I didn't check) is supported.

The `cider-jack-in-dependencies` variable is being set as expected. In one of my past attempts, all of the packages Lispy wanted were in `~/.m2/repository` but they weren't getting loaded properly when the REPL was starting.

**Comment by abo-abo** [comment]
Thanks for confirming. Please share the Dockerfile.

**Comment by danielcnorris** [comment]
Here you go. This uses Emacs 25.2.2 but reproduces the issue. You can change which version of Java is being used by changing the `FROM` statement in the Dockerfile. Let me know how it goes.

https://github.com/danielcnorris/lispy-test

**Comment by abo-abo** [comment]
I've been setting up Clojure for a project recently and used `openjdk-11` instead of `openjdk-8` I was using before. Indeed, this causes problems when lispy is loaded. So I've made a few changes and now lispy loads fine for JDK11. Please test if your issue is still reproducible.

**Comment by danielcnorris** [comment]
Works like a charm. Thanks Oleh!
