### ISSUE TITLE
No keybinding for lispy-ert

### ISSUE THREAD

**Issue by Wilfred** [abo-abo/lispy#458]
http://oremacs.com/lispy/#lispy-ert says that `T` is bound to `lispy-ert`. As far as I can see, this command doesn't have any bindings.

**Comment by abo-abo** [comment]
Thanks. The binding and the documentation has been updated to use <kbd>xT</kbd>.

I think <kbd>T</kbd> can be saved for later commands, since it's an easier binding (e.g. it can be held for repeatable commands, while `ert` never needs to be repeatable like that).
