### ISSUE TITLE
lispy-shifttab stopped working with newer org

### ISSUE THREAD

**Issue by ardpp** [abo-abo/lispy#460]
Hi Oleh,

I'm not sure when, but at some point `lispy-shifttab` stopped working for me. Perssing `i` on something like 

`;;* Locals: outline`  

does work as expected. Pressing `I` seems to recenter the line without folding all headlines as it used to do. 

I think it has to do with some changes in the newer `org-mode` packages. (If I understand correctly lispy-shifttab does require org.) 

The issue is present with emacs 27.0.50 and Org mode version 9.1.14. 

The issue is not present with the same emacs version and its built in Org mode version 9.1.9. 

Let me know if I can provide more useful information. 

Andrej

**Comment by yunhao94** [comment]
I also faced this issue recently and found that it's because of the change of `org-overview`.
Here's my workaround:
```elisp
(define-advice lispy-shifttab (:around (orig-func &rest args) fix)
  ;; restore the `org-overview' behaviour back to 9.1.9
  (let ((org-outline-regexp-bol (concat "^" outline-regexp)))
    (apply orig-func args)))
```

**Comment by ardpp** [comment]
Thanks, that works!

**Comment by abo-abo** [comment]
Thanks. Sorry for the delay.
