### ISSUE TITLE
lispy-convolute with multiple child sexps does not behave as expected

### ISSUE THREAD

**Issue by yuhan0** [abo-abo/lispy#466]
The algorithm that `lispy-convolute` uses is different from the traditional one used in paredit and smartparens -  
Lispy version only splices the current sexp that the cursor is on, whereas paredit/smartparens splice all neighboring sexps forward of the current sexp.  

```elisp
;; before (cursor at |)
(parent
  (sibling1)
  (head
    (child1)
    |(child2)
    (child3))
  (sibling2))

;; after (lispy-convolute-sexp / lispy-convolute)
(head
  (child1)
  (parent
    (sibling1)
    (child2)
    (sibling2))
  (child3))

;; after (sp-convolute-sexp / paredit-convolute)
(head
  (child1)
  (parent
    (sibling1)
    (child2)
    (child3)
    (sibling2)))
```

Is this an intentional difference? The documentation only shows the scenario with one child node, where both methods are equivalent.  The only advantage I can see here with the lispy version is that it is always reversible - pressing "CC" gets you back where you started.

But a more practical example shows how using `lispy-convolute` to switch the precedence of parent forms results in sexps being "pushed out" of a let binding, resulting in incorrect code:  

```elisp
;; cursor at |
(let ((beg x)
      (end y))
  (with-current-buffer buf
    |(insert " ")
    (delete-region beg end)
    (point)))

;; expected result (smartparens / paredit)
(with-current-buffer buf
  (let ((beg x)
        (end y))
    |(insert " ")
    (delete-region beg end)
    (point)))

;; actual (lispy)
(with-current-buffer buf
  (let ((beg x)
         (end y))
     |(insert " "))
  (delete-region beg end)        <---- unbound variables!
  (point))
```

**Comment by abo-abo** [comment]
I don't think the difference was intentional. As long as we can keep <kbd>CC</kbd> reversible, I don't mind modifying the behavior.

However, there's already a way of working with the current behavior: mark as many sexps as you want to keep with a region.

**Comment by abo-abo** [comment]
OK, looking at the code, the difference is intentional. Here's how to make it work like Paredit:

```elisp
(defun lispy-convolute (arg)
  "Replace (...(,,,|( with (,,,(...|( where ... and ,,, is arbitrary code.
When ARG is more than 1, pull ARGth expression to enclose current sexp."
  (interactive "p")
  (let ((deactivate-mark nil))
    (if (and (save-excursion
               (lispy--out-forward (1+ arg)))
             (save-excursion
               (lispy--out-backward (1+ arg))))
        (let (beg end)
          (lispy-from-left
           (setq beg (point))
           (setq end (lispy--out-backward arg))
           (lispy--out-backward 1)
           (lispy--swap-regions (cons beg end)
                                (cons (point) (point)))
           (lispy--reindent arg))
          ;; (lispy-from-left
          ;;  (lispy-different)
          ;;  (setq beg (point))
          ;;  (setq end (lispy--out-forward arg))
          ;;  (lispy--out-forward 1)
          ;;  (lispy--swap-regions (cons beg end)
          ;;                       (cons (point) (point)))
          ;;  (ignore-errors
          ;;    (lispy-different))
          ;;  (lispy--reindent (1+ arg)))
          )
      (error "Not enough depth to convolute"))))
```

**Comment by abo-abo** [comment]
The change was introduced in 9ace1f5. There's a test added to check this behavior, but I don't know why I thought it was useful at the time.

**Comment by abo-abo** [comment]
OK, looking at the test, I see the value in this behavior. We go from:

```elisp
(takes-two
 (takes-three
  |(takes-four 1 2 3 4)
  second
  third)
 other-second)
```

to:

```elisp
(takes-three
 (takes-two
  |(takes-four 1 2 3 4)
  other-second)
 second
 third)
```

After `lispy-convolute`, each function still takes the correct number of args. This is not true for `paredit-convolute-sexp`.
