### ISSUE TITLE
Outdated CIDER dependencies

### ISSUE THREAD

**Issue by NightMachinary** [abo-abo/lispy#470]
```
> ag --literal -a 'cider-interaction' .
lispy/lispy.el
1907:(declare-function cider-eval-print-last-sexp "ext:cider-interaction")

lispy/le-clojure.el
28:(require 'cider-interaction nil t)
```

This cider-interaction was removed; See https://github.com/clojure-emacs/cider/issues/2203.

**Comment by zilti** [comment]
Also, it looks up `cider-connections` which is defined in `cider-connection.el` but not `require`d by lispy.

**Comment by zilti** [comment]
@NightMachinary I think this should resolve that issue?

**Comment by abo-abo** [comment]
Yes, I think this is fixed now. Thanks, all.
