### ISSUE TITLE
a new stable tag

### ISSUE THREAD

**Issue by brettgilio** [abo-abo/lispy#479]
I'm sorry if this has been asked recently, I didn't seem to find another issue related. Have you considered making a new stable tag? The last one was in 2015, and master has over 800 commits since that time. There are definitely some good changes that could be popped into melpa-stable for people like me who use it through Guix.

**Comment by phikal** [comment]
I'm not sure if this is known, but I'm using melpa stable, and currently can't even install lispy, because of a conflict with iedit requiring `0.97`, while the available version is `0.9.9.9` -- which I guess is just a mistake?

**Comment by abo-abo** [comment]
@phikal I just checked that an install from MELPA-stable is still possible, you can test it as well by cloning this repo and running `MELPA_STABLE=1 make update`.

@brettgilio I'll try to make a new release in the next weeks.

**Comment by abo-abo** [comment]
Thanks, 0.27.0 is now released :)
