### ISSUE TITLE
`lispy-teleport` not quitting

### ISSUE THREAD

**Issue by bcarrell** [abo-abo/lispy#48]
Somewhat of an obscure one:

If you issue <kbd>t</kbd> for `lispy-teleport`, then change your mind and press <kbd>C-g</kbd>, then <kbd>q</kbd> for `lispy-ace-paren`, the teleport command will actually stick around, so when you select the paren after <kbd>q</kbd>, the teleport will still happen.

**Comment by abo-abo** [comment]
Wow, that it is obscure. Good catch! I'll try to see why this happens.
