### ISSUE TITLE
lispy-tab transforms `#p"..."` to nil

### ISSUE THREAD

**Issue by Ambrevar** [abo-abo/lispy#481]
Recipe:

```lisp
(merge-pathnames #p"foo")
```
With the point on the first paren, call `M-x lispy-tab`.  It results in

```lisp
nil
```

**Comment by abo-abo** [comment]
Please describe the language and syntax of `#p"foo"`.

**Comment by Ambrevar** [comment]
Can't believe I forgot to specify this: It's Common Lisp.
`#p` is the syntax for pathnames.  `#p` precedes a strings (double quote included).

**Comment by abo-abo** [comment]
Thanks, please test.
