### ISSUE TITLE
README.md, "How to get into list-editing mode (special)", "}"

### ISSUE THREAD

**Issue by whxvd** [abo-abo/lispy#482]
The above mentioned section in the `README.md` contains a table that says `}` is bound to `lispy-right-nostring`. But `{` and `}` are bound to `lispy-braces` and `lispy-brackets`, respectively.

**Comment by abo-abo** [comment]
`README.md` says that `lispy-right-nostring` is bound to <kbd>)</kbd>, not <kbd>}</kbd>, which it is. Closing.
