### ISSUE TITLE
RET doesn't work in minibuffer for eval-expression on first run

### ISSUE THREAD

**Issue by noctuid** [abo-abo/lispy#484]
The first time the minibuffer is opened, its mode is `fundamental-mode` not `minibuffer-inactive-mode`, so pressing `RET` after using `M-:` for the first time will just insert newlines. I tried this with `emacs -Q` on emacs 27, but this has been an issue for as long as I can remember.

I'm not sure if this is expected or an Emacs bug (seems more likely), but checking `minibufferp` instead seems to work fine.

**Comment by abo-abo** [comment]
Thanks.
