### ISSUE TITLE
lispy-looking-back in comint-mode

### ISSUE THREAD

**Issue by haqle314** [abo-abo/lispy#487]
Apparently, comint and derived modes (when `comint-use-prompt-regexp` is nil) setup the prompt so that `line-beginning-position` returns the position after the prompt, not the true position of the line's beginning. Since `lispy-looking-back` uses `line-beginning-position` as limit, it always return nil, regardless of REGEXP. The result is that there's an extra space when I open a new list right after the prompt

````
;; Example in inferior-emacs-lisp-mode
ELISP> |
;; Current behavior
ELISP>  (|)
;; Expected behavior
ELISP> (|)
````

**Comment by abo-abo** [comment]
Can't reproduce on Emacs-26.1. I do:

```
make elisp
M-x ielm
M-x lispy-mode
(
```

**Comment by haqle314** [comment]
Ah, I was using an older version from melpa-stable. Installing the newest version fixed it.
