### ISSUE TITLE
Killing backwards reverses kill ring on yank

### ISSUE THREAD

**Issue by mzuther** [abo-abo/lispy#489]
Hi!

At first let me thank you for Lispy. It has completely changed the way I code in Lisp / Clojure!

There is one thing which trips me up regularly. In Emacs, I often use `backward-kill-word` (and thus `lispy-backward-kill-word`) followed by `yank` to move / copy things. For whatever reason, Lispy yanks the contents of the kill ring in reverse:

    (defn front-middle-back [var]|)

Hitting `M-Del` five times in succession yields:

    (| [])

Then, yanking with `C-y` yields:

    (backvarmiddle-front-defn | [])

This breaks my editing habits. I would expect this instead:

    (defn front-middle-back var | [])

But even if the above behaviour was desired, it is still inconsistent because only parts of the kill ring are reversed. This would be consistent:

    (varbackmiddle-front-defn | [])

Mind you that this is a contrived example to demonstrate the inconsistency of killing and yanking. I usually only move / copy a variable name.

Thanks for listening!

Martin

**Comment by abo-abo** [comment]
Thanks. It's better now, but still could use more improvements and tests.

**Comment by mzuther** [comment]
Damn, your fast. Thanks! :)

I've just done a bit of testing and it seems to work fine. I'll report back if something weird comes up...

**Comment by abo-abo** [comment]
Thanks, please open a new issue if you find something.
