### ISSUE TITLE
How to terminate a forever evaluation triggered by special-lispy-eval?

### ISSUE THREAD

**Issue by shizhz** [abo-abo/lispy#49]
If I got stuck with a running expression on Slime REPL, I can type C-c C-c to terminate it, but how could do the same thing if the evaluation is triggered by special-lispy-eval?

Thanks :)

**Comment by abo-abo** [comment]
<kbd>C-g</kbd> (`keyboard-quit`) works for me when trying to evaluate `(loop for i upto 100000000000000 collect i)` in Common Lisp.

**Comment by shizhz** [comment]
Yeap it works, big thanks abo-abo :)
