### ISSUE TITLE
How to display thread macro results in another buffer in Clojure

### ISSUE THREAD

**Issue by Andre0991** [abo-abo/lispy#490]
First, thanks so much for creating `lispy`.

In Clojure, I frequently want to display the result of an evaluation in a separate buffer, especially when the result is big and looking at the partial result in the minibuffer/overlay doesn't help much.

For example, consider this function:

```
(defn example []
  (->> (range 1 200)
       (map inc)
       (map str)))

(example)
```

When I want to see the whole result, I use this, which is bound to "X" in `lispy-mode-map`:

```
(defun andre-lispy-cider-pprint ()
    (interactive)
    (lispy-different)
    (cider-pprint-eval-last-sexp)
    (lispy-different))
```

It displays the result in a separate buffer. For me, this is more practical than evaluating it in the REPL.

Now, this works if I execute it with the point at `(` in `(example)`.

My issue is that I'd like to do the same thing within thread macros and within functions, taking advantage of the `shadows` mechanism you recently implemented (which is really neat, by the way).

For example, if the point is at `(` in `(map inc)`, I'd like to evaluate it and display the result in another buffer.

```
(defn example []
  (->> (range 1 200)
       (map inc)
       (map str)))
```

How can I do that?

**Comment by abo-abo** [comment]
Thanks. You can now set `lispy-message-limit` to a small value either permanently or temporarily. The pop-up buffer functionality was already there, maybe it didn't trigger for you because of the length.

The popup is nicer than `cider-pprint-eval-last-sexp` as well, since it's re-formatted. I tried with:

    (lispy-clojure/symbol-function 'filter)
