### ISSUE TITLE
`lispy-tab` cannot handle '{ or '\{

### ISSUE THREAD

**Issue by taku0** [abo-abo/lispy#492]
In `emacs-lisp-mode`, 
- `lispy-tab` on `(list '{)` results in `nil` 
- `lispy-tab` on `(list '\{)` results in `Scan error` 
- `lispy-tab` on `(list (list '\{) '\})` results in `(list (list '\{} '})` (note that `(list '\{)` is rewritten to `(list '\{}`)

Both `'{` and `'\{` are valid expression in elisp.

**Comment by abo-abo** [comment]
Thanks.
