### ISSUE TITLE
[le-lisp.el] [lispy-use-sly] [customize] Not found

### ISSUE THREAD

**Issue by rprimus** [abo-abo/lispy#494]
Wed Jun 26 15:25:39 BST 2019

Using `C-1` for inline documentation, would cause `slime` to be started and emacs to use 98% CPU - which ended with having to force-quit emacs.

I found #371 which mentioned setting `lispy-use-sly` to non-nil.

`lispy-use-sly` would not be found using  `customize-variable`, `customize
group` or `describe-variable`.   It is defined in `le-lisp.el`

Using `swiper` and `avy-occur` on `load-history` (narrowing to all files with my name and lispy):

```
(  1/4  ) Swiper: lispy
 ./*helpful variable: load-history*:8028: ("/Users/rprimus/dotfiles/.emacs.d/elpa/lispy-20190624.1437/lispy.elc"
 ./*helpful variable: load-history*:9375: ("/Users/rprimus/dotfiles/.emacs.d/elpa/lispy-20190624.1437/lispy-inline.elc"
 ./*helpful variable: load-history*:9947: ("/Users/rprimus/dotfiles/.emacs.d/elpa/lispy-20190624.1437/lispy-tags.elc"
 ./*helpful variable: load-history*:18844: ("/Users/rprimus/dotfiles/.emacs.d/elpa/lispy-20190624.1437/lispy-autoloads.el"
```

The above shows that `le-lisp.el` is not loaded.
After manually `(require ‘le-lisp)` it does _show up_ in all 3 commands and in `load-history`.

### Questions
1. At what point should this be loaded when `lispy` is enabled and in `lisp-mode`?
2. Is the user responsible for loading `le-lisp.el`?

### Request
1.  Please add `lispy-use-sly` (under a section about SLIME/SLY) to the docs/README.

Regards

**Comment by abo-abo** [comment]
It seems that you've hit a bug that I can't reproduce. Here's how it's supposed to work:

1. Open a LISP file in `lispy-mode`.
2. Use a `lispy` command that needs the REPL: <kbd>e</kbd> (I usually use this one to start the REPL), <kbd>C-1</kbd>, <kbd>C-2</kbd> etc.
3. If the REPL isn't already running, it's started automatically, and the command performs its action.

I can reproduce this with my config:

```elisp
(use-package slime
    :commands slime
    :init
    (require 'slime-autoloads)
    (setq slime-contribs '(slime-fancy))
    (setq inferior-lisp-program "/usr/bin/sbcl"))
```

You can also try to reproduce by cloning this repo and running `make plain`. It will run `emacs -Q`, but with `lispy` and all dependencies.

> Please add lispy-use-sly (under a section about SLIME/SLY) to the docs/README.

I don't think it's required. It's a minor config option that should not affect usability too much.
Also, `lispy-use-sly` shows up in `customize-group` `lispy`, since it's a `defcustom`.

**Comment by rprimus** [comment]
Wed Jun 26 22:16:36 BST 2019

> Here's how it's supposed to work:

Now that I’ve customized `lispy-use-sly`, it works as expected.  It appears that it did work as expected previously,  however,  as `lispy-use-sly` was unset, `slime` was being called and this hung emacs.

To reproduce:

```elisp
(use-package sly
    :commands (sly sly-mode)
    :init
    (require 'sly-autoloads)
    (setq inferior-lisp-program "/usr/bin/sbcl"))
```

> You can also try to reproduce by cloning this repo and running make plain.

This did not work for me.
1.  I had to create `~/.elpa/26.2/elpa`
2. `make plain` did not download any of the dependencies
3.  It produced: `Cannot open load file: No such file or directory, avy`
4.  my sbcl is not located at `/usr/bin/sbcl`
5.  this is setup to use `slime` and not `sly`

This `bug` is happening for `SLY` users (me) that haven’t set `lispy-use-sly`.

**Comment by abo-abo** [comment]
You need to run `make update` to install/upgrade all dependencies into `~/.elpa`. The other Makefile targets don't call `make update` because it's too lengthy.

**Comment by abo-abo** [comment]
Should work better now. Please test.

**Comment by rprimus** [comment]
Thu Jun 27 17:39:29 BST 2019

I’ve updated lispy and removed the customization for `lispy-use-sly`.
`SLIME` was started and Emacs %CPU shot to ~99.8 - making Emacs unusable.

**Comment by abo-abo** [comment]
So it's normal behavior now:

- If SLIME is installed, and `lispy-use-sly` is nil, SLIME is launched by <kbd>e</kbd> and the CPU usage is normal.
- If SLIME is not installed, `lispy-use-sly` is nil, but Sly is installed, Sly will be used.
- If SLIME and Sly are installed and `lispy-use-sly` is t, Sly is used.

If so, please close the issue.

**Comment by rprimus** [comment]
Thu Jun 27 19:06:40 BST 2019

> If SLIME is not installed, lispy-use-sly is nil, but Sly is installed, Sly will be used.

Using `make plain`, I get:
Cannot open load file: No such file or directory, slime-repl

The other 2 statements are correct.

**Comment by abo-abo** [comment]
What I meant, is that you need to:

```
make update
rm -rf ~/.elpa/26.2/slime*
make plain
```

Slime "not installed" for `make plain`, means it's not installed in `~/.elpa`.

**Comment by rprimus** [comment]
Thu Jun 27 20:15:30 BST 2019

Those are the steps I followed.

**Comment by abo-abo** [comment]
Looking at the code, I'm pretty sure the behavior is correct. First time `lispy--use-sly-p` is called:

- `lispy-use-sly` is nil, so `(require 'slime nil t)` is attempted, which returns nil
- `(require 'sly)` is run and `(setq lispy-use-sly t)` is set.
- the function returns `t`, so that `(require 'slime-repl)` is never run.

**Comment by rprimus** [comment]
Thu Jun 27 20:24:51 BST 2019

What do you experience when you perform the steps in https://github.com/abo-abo/lispy/issues/494#issuecomment-506473035

**Comment by rprimus** [comment]
Thu Jun 27 20:35:56 BST 2019

![le-lisp](https://user-images.githubusercontent.com/278414/60295276-37274d00-991b-11e9-9593-0638c41d50e3.gif)

**Comment by rprimus** [comment]
Thu Jun 27 20:42:10 BST 2019

Looking at the gif I posted,  I saw the message that le-lisp.el  was newer than the compiled file.
I removed all .elc files and the code ran as per your expectations.

Thanks for the changes you’ve made and apologies for any time you’ve wasted!

**Comment by abo-abo** [comment]
No problem. Thanks for the follow up.
