### ISSUE TITLE
Bug in lispy--insert lisp #\. character

### ISSUE THREAD

**Issue by ydl7** [abo-abo/lispy#495]
There is a bug in lispy--insert which incorrectly replaces the lisp character #\. with #. . This breaks lispy-indent, and presumably other functions, for common lisp. To reproduce, evaluate
```elisp
(with-temp-buffer
  (lispy--insert '(ly-raw lisp-char "#\\."))
  (buffer-string))
;; evaluates to the string "#."
```
This is caused by the code added in commit 6bde52212b3592739d19b7719e2fa5a679ddb440, at latest master located here https://github.com/abo-abo/lispy/blob/e59e63662d2365792db90c6b59584df8e8a88f08/lispy.el#L8106. Why is this global regex replacement actually done? I am not familiar with clojure syntax. In any case it should not be done in common lisp modes (and probably not in others either).

I have the more general question why lispy--insert is structured the way it is, taking some internal sexp, writing the raw string representation to the file, then essentially going back and reparsing the `'ly-raw`-tagged parts. Is there a reason it is not inserted in one shot by processing the original sexp subexpression-by-subexpression? This would avoid the mysterious and globally (regardless of mode) applied regex replacements at the end of  `lispy--insert`, which I suspect cause other bugs in common lisp modes (those regex's seem specialized to clojure?).

Thanks very much.

**Comment by abo-abo** [comment]
Thanks for the report. Your issue should be fixed now.

> Why is this global regex replacement actually done? I am not familiar with clojure syntax.

Elisp reader is used to read `any` LISP code flavor. This is a choice with the main advantage that we don't need to start a REPL to have `lispy-tab` work.

And here's how the Elisp reader works:

    (read "java.time.Date")
    ;; => java\.time\.Date

So `prin1` is no longer an inverse of `read`. Hence these tricks with global replacement.

> In any case it should not be done in common lisp modes (and probably not in others either).

This has to be done in any lisp dialect that supports symbol names with `.` in them.

> I have the more general question why lispy--insert is structured the way it is, taking some internal sexp, writing the raw string representation to the file, then essentially going back and reparsing the `'ly-raw`-tagged parts. Is there a reason it is not inserted in one shot by processing the original sexp subexpression-by-subexpression? This would avoid the mysterious and globally (regardless of mode) applied regex replacements at the end of `lispy--insert`, which I suspect cause other bugs in common lisp modes (those regex's seem specialized to clojure?).

The code of `lispy--insert` was incrementally hacked together to work in most cases. Would be nice to improve it.
