### ISSUE TITLE
Spacing inconsistency between `lispy-kill-word` and `lispy-backward-kill-word`

### ISSUE THREAD

**Issue by Zaeph** [abo-abo/lispy#496]
Hello.

I'll preface this by saying that this is a **minor** issue.

I usually kill the previous word by going backwards with `M-b` (`backward-word`) and then killing it with `M-d` (`kill-word`), but I occasionally use `M-<backspace>` (`backward-kill-word`).

In `lispy-mode`, those functions are remapped to other functions prepended with `lispy-`.  The docstring mentions that, on top of the default behaviour, they ‘keep[ø] parens consistent’.  However, when it comes to spaces, they do not behave the same.

In those tests, `|` represents `(point)`.
```el
# 1st test
"This is a test|"

# 2nd test
(defun test| ()
  …
)
```

When you run `(progn (backward-word) (lispy-kill-word))` at `(point)`, you get:
```el
# 1st test
"This is a|"

# 2nd test
(defun| ()
  …
)
```
Note the space.

When you run `(lispy-backward-kill-word))` at `(point)`, you get:
```el
# 1st test
"This is a |"

# 2nd test
(defun | ()
  …
)
```

I haven't had time to look at the code yet, but I suppose some checks must be run in one `lispy-kill-word` which aren't run in `lispy-backward-kill-word`.  The only difference I can see without looking at the code is that, prior to killing, depending on the command, `(point)` is one side or the other.  Knowing how positions are relevant in `lispy-mode`, that might be it.

As far as I'm concerned, if I were to choose between the two behaviours, I'd prefer is `lispy-kill-word` didn't remove the space.  Nonetheless, I wanted to ask you what the rationale was behind this behaviour, since I expect one of them to be the intended behaviour, and the other a bug.

And I'll use this occasion to thank you for `lispy-mode`.  I've been using it for a few months now, and I'm having a ton of fun with it.

HTH.

**Comment by abo-abo** [comment]
Thanks for the report, please test.

> And I'll use this occasion to thank you for lispy-mode. I've been using it for a few months now, and I'm having a ton of fun with it.

Thanks, I'm glad you like it.

**Comment by Zaeph** [comment]
Hello,

> Thanks for the report, please test.

I just did, and everything works as intended!

Thank you for the quick patch. :)
