### ISSUE TITLE
Dot method and dot field access are being incorrectly auto-formatted

### ISSUE THREAD

**Issue by aisamu** [abo-abo/lispy#498]
Just reporting a minor inconvenience involving `.method` and `.-field` access in Clojurescript and Clojure:

```clojurescript
;; Original
(do
  (.method object)
  (.-field object))

;; Pressing `i` on the top-level form
(do
  (\.method object)
  (\.-field object))

;; Pressing `i` again on the top-level form
(do
  (\. method object)
  (\. -field object))

;; Workaround
(do
  (. method object)
  (. -field object))
```

Currently running `lispy-20190717.1334` on Spacemacs (`develop - 3757ad`), emacs `26.2`, OSX

The setup also includes `lispyville`. If it's relevant, here's how both are being loaded:
```elisp
(defun lispyvilleonly/init-lispy ()
  (use-package lispy
    :defer t
    :init (progn
            (add-hook 'emacs-lisp-mode-hook #'lispy-mode)
            (add-hook 'lisp-mode-hook #'lispy-mode)
            (add-hook 'clojure-mode-hook #'lispy-mode)
            (setq lispy-compat '(cider)))
    :commands (lispy-mode)))


(defun lispyvilleonly/init-lispyville ()
  (use-package lispyville
    :defer t
    :init (progn
            (add-hook 'lispy-mode-hook #'lispyville-mode)

            (setq lispyville-motions-put-into-special t)

            (lispyville-set-key-theme
             '(operators
               c-w
               prettify
               text-objects
               atom-movement
               mark-toggle
               slurp/barf-cp
               escape
               (additional-movement normal visual motion))))
    :commands (lispyville-mode)))

```

Thanks for this **amazing** tool!

**Comment by abo-abo** [comment]
Thanks, please test.

> Thanks for this amazing tool!

You're welcome. Just one note on how I use the dot:

```clojure
(. (java.math.BigDecimal. "42") |add 1M)

(let [pt (java.awt.Point. 1 2)]
  [(. pt |-x)
   (. pt |-y)])
```

The advantage here is that you have <kbd>C-M-i</kbd> completion at points marked with `|`.  This is because lispy can detect which object we're operating on. If we use `(.-x )`, there's no good completion since we haven't typed in `pt` yet.
Just a suggestion, I know that not may people write like this.

**Comment by aisamu** [comment]
Wow, that was fast! 
Thank you, it works beautifully.

> Just one note on how I use the dot:

That looks amazing, but unfortunately (and perhaps by design) it fails on CLJS because `lispy_clojure` doesn't seem to get loaded[1] there.

```elisp
completion--some: Symbol’s function definition is void: lispy_clojure
```

[1] The `nrepl` messages show no attempt to load the lispy_clojure helper file (or the `cljc` equivalent) on a CLJS REPL - as it can be seen on a CLJ one.

**Comment by abo-abo** [comment]
> it fails on CLJS because lispy_clojure doesn't seem to get loaded[1] there

It's by design then :). I haven't used CLJS for anything yet.
