### ISSUE TITLE
Configure default verbosity of hydra-lispy-x

### ISSUE THREAD

**Issue by yyadavalli** [abo-abo/lispy#502]
Hi,

Is it possible to configure to set the default verbosity of `hydra-lispy-x` hint without having to press `?` to increase it each time. I am just exploring those features and I would like to see the full hint till I get used to it.

Sorry if it's been documented and I've missed it.

Thanks

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by yyadavalli** [comment]
Thanks a lot working as expected.
