### ISSUE TITLE
Lispy incorrect escape atoms starting with .

### ISSUE THREAD

**Issue by thiagokokada** [abo-abo/lispy#504]
In Clojure, the following atom is valid:

```clojure
:.some-atom
```

However, calling `lispyville-prettify` in this atom results in:

```clojure
:\.some-atom
```

That is not a valid atom.

Similar to issue: https://github.com/abo-abo/lispy/issues/495. Related to issue: https://github.com/noctuid/lispyville/issues/58

**Comment by noctuid** [comment]
For reference, `(lispy--normalize-1)` is used for this.

**Comment by abo-abo** [comment]
Looking at [https://clojure.org/reference/reader], I see this:

> They cannot contain '.' in the name part, or name classes.

But the eval does work. So I can fix it in Lispy.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by thiagokokada** [comment]
Yep, it is working now. Thanks @abo-abo .
