### ISSUE TITLE
Command for lispy-right interfers with CIDER

### ISSUE THREAD

**Issue by mzuther** [abo-abo/lispy#508]
Hi!

I code in Clojure and use *lispy-mode* in combination with *cider-mode*.  In the REPL, `M-n` (cider-repl-next-input) and `M-p` (cider-repl-previous-input) access the command history.  However, lispy-mode binds `M-n` to `lispy-right`

I use the REPL command history quite often and trip over this key command all the time.  I'm not aware of an easy fix on my side (commenting it out in the source code works, but only until the next update), so would it be possible to make binding of `M-n` optional in *lispy-mode*?

Thanks!

Martin

**Comment by abo-abo** [comment]
Thanks, please test.
