### ISSUE TITLE
Keywords with leading dots are being incorrectly auto-formatted

### ISSUE THREAD

**Issue by aisamu** [abo-abo/lispy#511]
Just reporting a minor inconvenience involving keywords with leading dots in Clojurescript and Clojure:

```Clojure
;; Original
[:.keyword]

;; Pressing `i` on the top-level form
[:\.keyword]

;; Pressing `i` again on the top-level form
[: \. keyword]
```

Currently running lispy-20190802.1214 on Spacemacs (develop - 39b615), emacs 26.2, OSX

The setup also still includes lispyville (If relevant, it's described in #498).

Thanks again for this amazing tool. I've yet to master a third of it - and it keeps on giving!

**Comment by abo-abo** [comment]
> lispy-20190802.1214

This version is out of date. The last commit to master was on Oct 16, and the issue seems to be fixed there. Please try updating to lispy-20191016.1250.

**Comment by aisamu** [comment]
Works beautifully on lispy-20191101.1731.
Apologies for the noise!

**Comment by abo-abo** [comment]
No problem.
