### ISSUE TITLE
Support for Clojure commas and periods

### ISSUE THREAD

**Issue by yuhan0** [abo-abo/lispy#515]
Commas are whitespace in Clojure, and it's a common idiom to use multiple commas `,,,` in place of "missing" parameters within threading macros.
https://clojure.org/guides/threading_macros

```clojure
(-> person
   (assoc ,,, :hair-color :gray)
   (update ,,, :age inc))
```

Unfortunately, lispy-tab mangles this into the following form:
```clojure
(-> person
  (assoc, (\,, ) :hair-color :gray)
  (update, (\,, ) :age inc))
```

Sequences of periods `.` are also valid symbols in Clojure, and are used as macro anaphors in the library Meander.

https://github.com/noprompt/meander/blob/epsilon/doc/operator-overview.md#zero-or-more
```clojure
(m/match [1 2 1 2 2 3]
  [1 2 ... ?x ?y]
  [?x ?y])
```
These are also mangled by lispy-tab:
```clojure
(m/match [1 2 1 2 2 3]
  [1 2 \.\.\. ?x ?y]
  [?x ?y])
```

**Comment by abo-abo** [comment]
Hi. I fixed the commas issue. Please test. Regarding the dots, the scope is not clear. `clojure-mode` does not treat the dot as a symbol constituent.
