### ISSUE TITLE
Symbols with leading question marks are being incorrectly auto-formatted

### ISSUE THREAD

**Issue by aisamu** [abo-abo/lispy#516]
Just reporting a minor inconvenience involving symbols with leading dots in Clojure/script:
```Clojure
;; Original
[?identifier]

;; Pressing `i` on the top-level form
[?i dentifier]
```
Currently running lispy-20200105.1844 on Spacemacs (develop - 763681), emacs 26.3, OSX

This is common in queries, with `?symbols` representing variables to be bound.
Datomic, and [meander](https://github.com/noprompt/meander) (shown in the two last examples on https://github.com/abo-abo/lispy/issues/515#issue-543992844) use them, for example. 

Thanks yet again for lispy :)

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by aisamu** [comment]
I tried removing the package from my `elpa` directory (to trigger the reinstall with the latest version, as I've usually done) but it reinstalled `lispy-20200108.1612`.
Is that due to some package propagation delay? Should I fetch from a different "channel"?

**Comment by abo-abo** [comment]
> Is that due to some package propagation delay?

Could be. MELPA re-builds roughly every 4 hours. These days I'm using straight.el to manage packages instead of MELPA. This method doesn't not have a delay.

**Comment by aisamu** [comment]
Finally, the update process picked it!
Works like a charm, thanks a lot!
