### ISSUE TITLE
Loading a Clojure project causes some lispy tests from lispy-clojure-test.clj to be run - shouldn't this be avoided?

### ISSUE THREAD

**Issue by ahungry** [abo-abo/lispy#517]
If i load a REPL with lispy, it triggers tests to be run in my project's REPL.

I think this is ill advised if intentional, and at the least should be controllable via a setting.

Can the loading of the clj files (in particular the -test one) be disabled by user options?

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by ahungry** [comment]
Thanks - it looks good, although without customizing, I don't seem to notice the tests run at all (even when test is set to t), which is fine for me, since I didn't want them to run, but may be bad for you/others?

**Comment by abo-abo** [comment]
The test result is still saved in `*Messages*`. So it's all good.

**Comment by ahungry** [comment]
That makes sense, thanks!

**Comment by Andre0991** [comment]
Hey @abo-abo. I also set this to `nil`, but I'm wondering why it's true as default – any reason for loading these tests?
