### ISSUE TITLE
Possible regression on namespaces tags (#name) when formatted by (M) multi-line

### ISSUE THREAD

**Issue by aisamu** [abo-abo/lispy#519]
There might be a regression involving `lispy-multiline` with namespaces tags and maps in Clojure/script:
```clojure
;; Original
[#db {:a 1 :b 2} #db {:c 3 :d 4}]

;; After M on lispy-20200108.1612: 
[#db
 {:a 1 :b 2}
 #db
 {:c 3 :d 4}]

;; After M on lispy-20200116.1401
[#(ly-raw clojure-symbol "db")
 {:a 1 :b 2}
 #(ly-raw clojure-symbol "db")
 {:c 3 :d 4}]
```
Currently running  on Spacemacs (develop - 763681), emacs 26.3, OSX

There are also two secondary inconveniences (that I'd gladly copy to separate issues if you prefer):  

1) When formatting with M, the namespace ends up on a separate line. It is usually written in the same line as the tagged map, [without spaces](https://clojure.org/reference/reader):
```Clojure
[#db{:a 1 :b 2}
 #db{:c 3 :d 4}]
```

2) Also - but it might be just a case of stale documentation - I couldn't get [lispy-multiline](http://oremacs.com/lispy/#lispy-multiline)'s example to work as advertised on either version. (even on an elisp buffer)

Thanks for Lispy!

**Comment by abo-abo** [comment]
Thanks, I've added a small fix for this.

> with namespaces tags and maps in Clojure/script

Can you explain this syntax to me? I tried to eval your code, but it doesn't work.

> When formatting with M, the namespace ends up on a separate line

There currently isn't a an extensible way of defining these rules. Please open a new issue.

> Also - but it might be just a case of stale documentation - I couldn't get lispy-multiline's example to work as advertised on either version. (even on an elisp buffer)

See `lispy-multiline-threshold`. It's 32 by default. Expressions shorter than 32 chars don't get multi-lined, since they tend to look better in one line.

**Comment by aisamu** [comment]
> I've added a small fix for this.
Thanks a lot! 

> Expressions shorter than 32 chars don't get multi-lined, since they tend to look better in one line.

Gotcha (and makes sense!). Would It be useful to leave a short note on the guide? (Or is there already a doc with other configuration vars like this one?)

> Can you explain this syntax to me? I tried to eval your code, but it doesn't work.

I forgot the `:` (e.g. `#db:`)! I'll open a second issue with more examples.

Again, thanks!
