### ISSUE TITLE
how to use lispy quick bind variable?

### ISSUE THREAD

**Issue by loyalpartner** [abo-abo/lispy#521]
i learnd this skill in http://oremacs.com/lispy/#lispy-bind-variable.
if i have two variable to bind ,  
```
(defun my-forward-line (arg)
  (let ((a (forward-line arg)))
    (message "%S %Slines" a |(backword-line arg))
```
Is there a way to get this code quickly?
```
(defun my-forward-line (arg)
  (let ((a (forward-line arg)
       (b (backward-line arg))
    (message "%S %Slines" a b)
```

**Comment by abo-abo** [comment]
Here are the steps to do it:

- <kbd>xbb</kbd> to bind the current sexp to the variable b
- <kbd>M-m C</kbd> to convolute the new let expression into place
- <kbd>qg/</kbd> to jump to the new let expression and splice it

Maybe it's a little clunky, and the existing let-binding should be auto-detected. Then it would just be `xbb[`.

But the current way is perhaps a little more flexible.

**Comment by loyalpartner** [comment]
thank you！
