### ISSUE TITLE
company-mode popup eating keys with lispy-mode and cider-mode

### ISSUE THREAD

**Issue by lisper123** [abo-abo/lispy#522]
### Steps to reproduce: 
`emacs -Q`
```
(package-initialize)
(require 'clojure-mode)
(require 'cider)
(require 'lispy)
(require 'company)
(find-file "core.clj")
(company-mode)
(cider-mode)
(lispy-mode)
(cider-jack-in nil)
```
Start typing an expression (e.g. `(req`), wait for the company suggestions to appear and press space.

### Expected behaviour:
The popup disappears and a space is inserted.
### Actual behaviour:
No space is inserted.

Tested on emacs 26.3 and the latest versions of all the packages involved on MELPA/ELPA as of 31/01/2020. Other modes (e.g. elisp) seem fine, so it might have something to do with `cider-mode`. When lispy is not enabled it works as expected. Frustratingly, company overrides `C-h` so you can't use `C-h k` to find out what's going on, but `view-lossage` shows the following, using the example above:
``` 
 r [special-lispy-raise]
 e [special-lispy-eval]
 q [special-lispy-ace-paren]
 <company-dummy-event> [company-ignore]
 SPC [lispy-space]
 SPC [lispy-space]
```
But the output is the same in elisp mode, where the space _is_ inserted...

**Comment by abo-abo** [comment]
I tried to reproduce using `make plain` with Emacs 26.3 and the latest versions of all packages. But the space works as expected.

**Comment by lisper123** [comment]
Thanks for looking into this! You're right, with `make plain` it works for me too. However, if I comment out [this line](https://github.com/abo-abo/lispy/blob/d6b19fe2c3ea9aa6447c56689f746cafba645432/elpa.el#L11) and run `make plain`, the issue reappears. Maybe a difference between the elpa package and the git repo, or the way it gets loaded? I'm in over my head at this point!

**Comment by abo-abo** [comment]
Hi. I tried to comment out the line. Still can't reproduce.

**Comment by lisper123** [comment]
Hi, I just managed to reproduce this completely from scratch in a clean VM:
```sh
vagrant init debian/buster64
vagrant up
vagrant ssh
sudo apt update
sudo apt install leiningen emacs git make
git clone https://github.com/abo-abo/lispy
cd lispy
# add lispy, company to lispy-dev-packages in target/install-deps.el
make update
lein new test
make plain
C-x C-f ~/lispy/test/src/test/core.clj
C-c C-x j j
(company-mode)
# type `(req`, wait, press space, works
# exit, comment out load-path line in elpa.el
# repeat from "make plain", no longer works.
```

**Comment by lisper123** [comment]
So, I did a bit of investigation and have a bit insight into what is going on, but it's a little bit weird.
The space gets inserted, but then removed again, in `company-post-command` -> ... -> `lispy-clojure-complete-at-point`, -> `lispy--out-forward`. The problem is that `lispy-ignore-whitespace` is set to nil, even though it was bound to `t` [here](https://github.com/abo-abo/lispy/blob/c1286a2b41fa1f21c4f2ecdd5ba191805e04e268/le-clojure.el#L493).

When I instrumented `lispy-clojure-complete-at-point` for debugging, the problem disappeared, ie. re-evaluating that function solves the problem. Is it possible that the let* doesn't work properly when compiled to byte code?

**Comment by abo-abo** [comment]
Nice catch! Does this refactor solve the problem?

**Comment by lisper123** [comment]
Unfortunately not! And now the trick of recompiling the file no longer works, which I suppose is a good thing :). It seems that the whitespace is now being deleted as a result of the `lispy--out-backward` calls inside [this save-excursion](https://github.com/abo-abo/lispy/blob/9e8e058c87cf1bc8ce7659ebe8a2868850298334/le-clojure.el#L519).

**Comment by abo-abo** [comment]
Thanks, please test again.

**Comment by lisper123** [comment]
Close! There's one more call on line 524 that needs wrapping. At least that worked for me when eval'ing the code in emacs.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by lisper123** [comment]
All working now. Thanks for taking the time to fix this, and for creating lispy, it's really a great package!
