### ISSUE TITLE
lispy-eval: nrepl-send-sync-request: Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by qleguennec** [abo-abo/lispy#524]
How to reproduce:

- Open cljs file
- Call `lispy-eval` on a sexp (`e`)
- Prompt ask to use either `lein` or `shadow-cljs`. Either trigger the error.

Repl works fine but I cannot use it through lispy because of this issue.
`eval-last-sexp` works fine.

**Comment by abo-abo** [comment]
Thanks, please test. I tested by doing `cider-jack-in-cljs` and then using `lispy-eval`.

**Comment by qleguennec** [comment]
The error remains after c1286a2

**Comment by qleguennec** [comment]
Nevermind, I had an issue with my build system, the fix works, thank you!

**Comment by abo-abo** [comment]
You're welcome.
