### ISSUE TITLE
Syntax error when using with cider connect

### ISSUE THREAD

**Issue by gmichokostas** [abo-abo/lispy#525]
I am getting the following exception when I do `cider-connect-clj`

```
Syntax error (FileNotFoundException) compiling at (~/.emacs.d/elpa/lispy-20200210.925/lispy-clojure.clj:1:1).
Could not locate cemerick/pomegranate__init.class, cemerick/pomegranate.clj or cemerick/pomegranate.cljc on classpath.
```

And in the `cider-error` buffer: `Unhandled java.lang.ClassNotFoundException`

Here is my deps.edn file 

```edn
{:paths ["src"]
 :deps
 {org.clojure/clojure {:mvn/version "1.10.1"}
  ring/ring-core      {:mvn/version "1.8.0"}
  ring/ring-jetty-adapter {:mvn/version "1.8.0"}}
 :aliases
 {:nrepl {:extra-deps {cider/cider-nrepl {:mvn/version "0.24.0"}}
          :main-opts ["-m" "nrepl.cmdline" "--middleware"
                      "[cider.nrepl/cider-middleware]"]}}}
```

I added the following into my init.el
```lisp
(eval-after-load 'cider
  '(progn
    (cider-add-to-alist 'cider-jack-in-dependencies
     "org.tcrawley/dynapath" "0.2.5")
    (cider-add-to-alist 'cider-jack-in-dependencies
     "com.cemerick/pomegranate" "0.4.0")))
```
as recommended in another issue but then I get the following error when I evaluate a form
```
Syntax error compiling at (src/core.clj:1:1).
No such var: lispy-clojure/pp
```

**Comment by abo-abo** [comment]
What happens if you type `(ns lispy-clojure)` into the REPL?

Can you confirm that using `cider-jack-in` in place of `cider-connect` works?

**Comment by gmichokostas** [comment]
> What happens if you type (ns lispy-clojure) into the REPL?

I get back `nil` and I can't evaluate anything, just getting the above errors.
<img width="1131" alt="Screenshot 2020-02-20 at 21 07 36" src="https://user-images.githubusercontent.com/7119729/74974207-191bd900-5425-11ea-9082-9f40781ad0ba.png">

> Can you confirm that using cider-jack-in in place of cider-connect works?

That works and I can evaluate code but I get some errors in the buffer

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
<img width="1680" alt="Screenshot 2020-02-20 at 21 10 36" src="https://user-images.githubusercontent.com/7119729/74974855-47e67f00-5426-11ea-9093-fcd00336d4b4.png">

**Comment by abo-abo** [comment]
OK, I've tested it with `cider-connect`. It's working for me, since I have this config file:

`~/.lein/profiles.clj`:

```clojure
{:user {:dependencies
        [[org.tcrawley/dynapath "0.2.5"]
         [com.cemerick/pomegranate "0.4.0"]]}
 :repl {:plugins
        [[cider/cider-nrepl "0.23.0"]]}}
```

Can you confirm that `cider-connect` works if you have a similar `profiles.clj` config?

**Comment by gmichokostas** [comment]
Oh sorry, I think I didn't mentioned that I don't use Leiningen but I use [Clojure CLI tools](https://clojure.org/guides/deps_and_cli)

I added the following in the `deps.edn` of my project and also in the `~/.clojure/deps.edn`
```edn
{:deps {org.tcrawley/dynapath    {:mvn/version "0.2.5"}
        com.cemerick/pomegranate {:mvn/version "0.4.0"}}}
```
`cider-jack-in` works fine, only the `cider-connect` fails. 

I think is fine for me to use only `cider-jack-in` since it works similarly to `cider-connect` 
so I will close the issue.

Thank you very much for taking the time to reply to my comments and for creating so many cool packages!
