### ISSUE TITLE
evaluating in lispy do not set cider breakpoint

### ISSUE THREAD

**Issue by Andre0991** [abo-abo/lispy#529]
Hi.

In `cider`, one can add wrap a form with `#break` and evaluate it in order to create a breakpoint.
The next time the form is run, cider steps in and displays its debugger interface (see [1]).

The issue is that when using `e` in `lispy` in order to evaluate something, `cider` does not create the breakpoint. So the next time the form is run, it won't stop.

[1]: https://docs.cider.mx/cider/debugging/debugger.html

**Comment by abo-abo** [comment]
I've examined the issue, with the latest CIDER:

1. You can still instrument functions with <kbd>xe</kbd>; evaluating an expression with <kbd>e</kbd> triggers that breakpoint
2. When <kbd>e</kbd> is used on a function with `#break`, evaluating an expression with <kbd>e</kbd> does not trigger the breakpoint
3. When `cider-eval-last-sexp` is used on a function with `#break`, evaluating an expression with <kbd>e</kbd> does trigger the breakpoint

So it remains to fix point 2, with 3 and 1 being workarounds.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by Andre0991** [comment]
I can confirm it works, thanks.
