### ISSUE TITLE
syntax table entry for { breaks cursor movements

### ISSUE THREAD

**Issue by emacs18** [abo-abo/lispy#53]
lispy-mode has this line in it:

(modify-syntax-entry ?\{ "(}")

which modifies the syntax table entry for { character so that it is treated
similar to ( as far as cursor movement is concerned.  This is problematic,
because built-in cursor movement functions no longer work as expected, e.g.,
C-M-f and C-M-b bound to forward-sexp and backward-sexp respectively.  To see
the problem evalute the following in the scratch buffer to set the syntax table
entry to the default value:

(modify-syntax-entry ?{ "_")

Now you should be able to execute C-M-f and C-M-b to move the cursor
between beginning and end of this line:

(char-syntax ?{)

So far so good.  Now evalute this which appears in lispy-mode:

(modify-syntax-entry ?\{ "(}")

Try hitting C-M-f and C-M-b as before.  C-M-f fails becase ?{ is treated same as
( for the purpose of the cursor movement.  Thus it sees two opening paired delimiters,
but only one closing delimiter.  If we add a backslash like this

(char-syntax ?\{)

then C-M-f and C-M-b works again.  So adding a backslash is a work-around.
Unfortunately backslash is not required to escape { character.  Lots of built-in
emacs lisp code use ?{ instead of ?\{ as well as add-on pacakges, so that it is
not feasible to replace all ?{ with ?\{ as a work around to
(modify-syntax-entry ?\{ "(}")
done in lispy-mode.

Would it be possible for lispy-mode not to modify the syntax entries?

**Comment by emacs18** [comment]
In my previous comment, I typed ? \ { characters (without spaces) in couple of places, but the backlash is not displayed for some reason.

**Comment by bcarrell** [comment]
Hah, that was sort of an experiment I pushed him towards.  My fault, I'm sure he'll fix it soon.  :)

**Comment by abo-abo** [comment]
> Would it be possible for lispy-mode not to modify the syntax entries?

My fault, I was trying to see if it could cause any errors, reverting.
