### ISSUE TITLE
[request] provide an option to deactivate lispy-forward/back [/] bindings in strings or comments

### ISSUE THREAD

**Issue by exp2ipi** [abo-abo/lispy#538]
With the default bindings of `[` / `]` it becomes quite annoying to type literal brackets in strings or comments, it would be nice to disable this behavior by default in string/comment context or at least provide an option to do so.

**Comment by abo-abo** [comment]
You can customize the behavior like this:

```elisp
(lispy-set-key-theme '(special paredit c-digits))
```
