### ISSUE TITLE
[Request] Macroexpansions for other langs

### ISSUE THREAD

**Issue by bcarrell** [abo-abo/lispy#54]
Specifically, Clojure.  It'd be awesome if I could do `xf` on a Clojure macro.

**Comment by abo-abo** [comment]
Nice idea, I'll see if I can make it work.

The issue is that I'm not very familiar with Clojure introspection. I saw `macroexpand` and it
works, but I also need `macrop` and `symbol-function` equivalents.

**Comment by abo-abo** [comment]
The basics should work now. Let me know if something need ironing out.

**Comment by bcarrell** [comment]
I haven't found any bugs with this yet.  Good work! I'll raise an issue if I encounter something.
