### ISSUE TITLE
geiser-repl-mode missing from lispy-goto-symbol-alist

### ISSUE THREAD

**Issue by Ambrevar** [abo-abo/lispy#542]
I can't go to symbol definition in Geiser.
Adding

```
(geiser-repl-mode lispy-goto-symbol-scheme le-scheme)
```

to `lispy-goto-symbol-alist` fixes it.

**Comment by abo-abo** [comment]
Added, thanks.

**Comment by jgarte** [comment]
@Ambrevar Hi, did `ab2122d` fix this issue for you? I still can't eval guile code with lispy.

Here is my emacs config:

https://git.sr.ht/~whereiseveryone/conf/tree/gnome/item/emacs.el

**Comment by Ambrevar** [comment]
Probably Geiser's fault.  I don't use it anymore, sorry.

**Comment by jgarte** [comment]
@Ambrevar Thanks for the reply, you don't use Geiser anymore or you don't use both Geiser and lispy?

**Comment by Ambrevar** [comment]
I don't write Scheme anymore ;)  I still use Lispy for other Lisps.
