### ISSUE TITLE
Clojure regression: invalid read-syntax #

### ISSUE THREAD

**Issue by bcarrell** [abo-abo/lispy#55]
When evaluating forms with anonymous functions, e.g. something like `(map #(inc %) (range 20))`, this happens:

`lispy--clojure-lax: Invalid read syntax: "#"`

**Comment by abo-abo** [comment]
Should work better now, although `lispy--read` isn't strictly equivalent to `read`.
But it should be good enough for `lispy--clojure-lax`, since the read expression isn't evaluated.

**Comment by bcarrell** [comment]
That fixes it, thanks!
