### ISSUE TITLE
Replace hjkl with ijkl for people who don't want to use Vim key bindings

### ISSUE THREAD

**Issue by tuhdo** [abo-abo/lispy#57]
It's hard to force into the habit of using `hjkl`. Even if I'm already accustomed to Vim editing, I rarely use `hjkl` but other movement methods. Even man Vim users said that `hjkl` is not efficient. For example, in [Habit breaking, habit making](http://vimcasts.org/blog/2013/02/habit-breaking-habit-making/), the author argued that using wordwise motions are 5x faster than h and l. I myself use text objects all the time, not `hjkl` that is the product of old keyboard, not because of "homerow ergonomics" as many people believed.

I like the idea of Lispy that Lisp mode is activated automatically, but the Vim key bindings are just annoying. Here is an easy way to help Lispy more approachable:

- Rebind `j` to `lispy-left`.
- Rebind `l` to `lispy-right`
- Rebind `k` to `lispy-down`,
- Rebind `i` to `lispy-up`.
- Rebind `TAB` to `lispy-tab` (easier to remember)
- `h` is freed after this.

**Comment by abo-abo** [comment]
A solution is forthcoming to fix both this and #51.
You'll get the `lispy` key-theme, and `paredit` key-theme, and `tuhdo` key-theme. What ever you want:)

**Comment by tuhdo** [comment]
Nice to hear that. And I hope that you can provide an alternative default to `hjkl` or at least a sample layout to quickly replace it. I like the shape of arrow keys because it requires zero learning curve.

**Comment by abo-abo** [comment]
> use text objects all the time, not hjkl

In lispy, hjkl manipulate s-expressions which are better than text objects.
They're different from vi's char-level hjkl.

**Comment by tuhdo** [comment]
I know, but the point is that even Vim users aren't fond of the positions of `hjkl`. It's not something special as people thought. Arrow keys are much faster to operate (If you play some action video game, you will feel it easier), more ergonomics (no stretching finger to reach the `h` key, even just a little) and no learning curve. `hjkl` is chosen only because of the old keyboard (the arrow keys are those positions) and the `i` key is chosen for insert. In Lispy, we have no such limitation: we can move `i` to `TAB` and suddenly people don't have to accommodate to the basic Lispy movement anymore. One less thing to worry, one more thing to learn for users.

**Comment by bcarrell** [comment]
> even Vim users aren't fond of the positions of hjkl.

Vim user here.  I'm fond of `hjkl`.

> no learning curve

Maybe if you're not used to vim.  I started using Lispy because I switched from vim and this was way more natural to me.  `ijkl` as default would take a long time for me to get used to.  I'd prefer multiple layouts with `hjkl` as default and `ijkl` as a separate option.

**Comment by abo-abo** [comment]
> I'd prefer multiple layouts with hjkl as default and ijkl as a separate option.

That's the plan.

**Comment by tuhdo** [comment]
Fine to me. But after observing [/r/vim](http://www.reddit.com/r/vim/) for almost a year, I saw people suggest to avoid `hjkl` and focus on other motions or use arrow keys if you like. Probably `hjkl` is more natural for Vim users, but `ijkl` is more natural to majority of people (including Emacs people), since it is universal across platforms, across applications and are easier and faster to press.

**Comment by abo-abo** [comment]
> ijkl is more natural to majority of people

Subjective assertion.

> since it is universal across platforms, across applications and are easier and faster to press

I haven't encountered a single application that uses <kbd>ijkl</kbd>. Not a single one.

Yet Firemacs uses <kbd>hjkl</kbd>, and so does Twitter and some other web sites.

**Comment by tuhdo** [comment]
What I meant with `ijkl` is the arrow key shape. You may not see `jikl`, but you surely will see `wasd`. Positions do not matter, but the way we use it.

**Comment by abo-abo** [comment]
> Positions do not matter, but the way we use it.

So why not just use <kbd>wasd</kbd>?

**Comment by tuhdo** [comment]
> So why not just use wasd?

Because we can have the arrow keys on homerow with minimal changes to the current layout. `wasd` or `ijkl`, does it matter? Both are just arrow keys on homerow.

**Comment by abo-abo** [comment]
@tuhdo, you can submit your own version of `lispy-mode-map-special` if you want.

Then you can have e.g.:

```el
(lispy-set-key-theme '(tuhdo-special lispy c-digits))
```

While I will have:

```el
(lispy-set-key-theme '(special lispy c-digits oleh))
```

**Comment by abo-abo** [comment]
Closing as outdated. Feel free to reopen if you want to submit a patch.
