### ISSUE TITLE
Tips on quickly get to the special points

### ISSUE THREAD

**Issue by jcguu95** [abo-abo/lispy#571]
`lispy` is great and offers magical operations while cursor is at special points. I struggled in particular by staying too long in normal points.. are there tips to go to special points quickly and deftly?

**Comment by yunhao94** [comment]
Have you ever tried `lispy-left-maybe` which is binded to <kbd>M-o</kbd> by default?

**Comment by jcguu95** [comment]
This is very useful and should be put into the doc imo.. thanks for the tip!
