### ISSUE TITLE
[Proposal] Use Semantic for accurate reformatting and trasforming sexp tree

### ISSUE THREAD

**Issue by tuhdo** [abo-abo/lispy#58]
Currently, it seems like `lispy` does not make use of Semantic to parse Emacs Lisp source file but using plain regexp. While this is ok for simple cases, it's not for complex case and if you somehow handle the complex case, your code essentially becomes a form of parser that you can avoid by using the already existing one.

For example, given this Lisp code:

```elisp
(defun test (arg1 arg2)
  (interactive)
  (let ((a 1))
    (message "%d" a)
    (if t
        "hi"
      "nope"
      "nope"
      "nope"
      "nope"
      "nope"
      "nope")))
```

Each "nope" there can be considered a mock statement. Now, using move point on the parenthesis before the `let` keyword and run `lispy-oneline`, it becomes:

```elisp
(defun test (arg1 arg2)
  (interactive)
  (let ((a 1)) (message "%d" a) (if t "hi" "nope" "nope" "nope" "nope" "nope" "nope")))
```

The format of `if` form is completely destroyed because `lispy` only tries to remove all the newlines in the `let` form. This is undesirable.

If Semantic is used, its AST can be used for a smarter formatting behaviour. Consider the below formatting function (this is just a function I wrote quickly for demonstration purpose):

```elisp
(defun lispy-format-let (let-tag format-type)
  (let* ((tag-start (semantic-tag-start let-tag))
         (tag-end (semantic-tag-end let-tag))
         (tags (semantic-parse-region tag-start tag-end nil 1))
         (first-tag-pos (semantic-tag-start (car tags)))
         (last-tag-pos (1- tag-end))
         (tmp-buf (generate-new-buffer "let-buf"))
         formatted-content
         tag-str)
    (save-excursion
      (dolist (tag tags)
        (message "tag is %s" tag)
        (cond
         ((eq format-type 'one-line)
          (setq tag-str (buffer-substring-no-properties (semantic-tag-start tag)
                                                        (semantic-tag-end tag)))
          (with-current-buffer tmp-buf
            (insert tag-str)
            (insert " ")))
         (t))
        ;; (lispy-reform-tag tag)
        )
      (kill-region first-tag-pos last-tag-pos)
      (goto-char first-tag-pos)
      (insert (with-current-buffer tmp-buf
                (buffer-substring-no-properties (point-min)
                                                (point-max))))
      (indent-region first-tag-pos last-tag-pos)
      (delete-horizontal-space)
      )))
```

Now, move point on the parenthesis before `let` keyword in the test function again, mark this sexp and `eval-expression` (<kbd>M-:</kbd>) this:

```elisp
(lispy-format-let (car (semantic-parse-region (region-beginning) (region-end) nil 0)) 'one-line)
````

You can see that the `if` sexp is preserved. Of course, we can do more format function like this and recursively walk through the inner tags and format them. The above is just a demo to show the potential of it. You can later do something like this to semantically format all tags:

```elisp
(defun lispy-reform-tag (tag)
  (let* ((tag-start (semantic-tag-start tag))
         (tag-end (semantic-tag-end tag))
         (tags (semantic-parse-region tag-start tag-end nil 1)))
    (dolist (tag tags)
      .... format the current tag and call lispy-reform-tag in its children tags...))
  )
```

Some interesting Semantic functions we can use:

- `semantic-parse-region`: The interesting parameter here is `DEPTH` (I think you know what BEG and END are for). If you mark a defun and run:

```elisp
(semantic-parse-region (region-beginning) (region-end) nil 0)
```

It returns top level tag.

Then, we increase the depth to 1:

```elisp
(semantic-parse-region (region-beginning) (region-end) nil 1)
```
You get all the first level tags just below the top level tag.

Then, increase it to 2:

```elisp
(semantic-parse-region (region-beginning) (region-end) nil 2)
```

You get all the second level tags just below the first level tag.

...and so on until the fucntion returns nil. With this, we can recursively parse a tree of a top level Semantic tag to reformat it. Once we get this done properly, we can easily make it reformat the whole file.

- `semantic-emacs-lisp-lexer`: this lexer produces lexical tokens in a region. With this function, you can reliably collects all open parenthesis. Just mark a defun and try this:

```elisp
`(semantic-emacs-lisp-lexer (region-beginning) (region-end) 2)`
```

It returns a list of tokens like this `((open-paren . (<start_pos> <end_pos>) (...)...)`.

You can see the documentation of `semantic-lex-tokens` for the default token types. Then, you can simply collect all the elements that contain `open-paren` in it using `assoc` easily.

You can actually check for keyword arguments with Semantic. Currently, `lisp-multiline` cannot correctly break keyword arguments like this once you make it one line:

```elisp
(link :tag "test "
      :button-prefix ""
      :button-suffix ""
      :button-face nil
      :format "%[%t\n%]"
      :help-echo ""
      :action nil
      nil)
```

Mark the above sexp and use `(semantic-emacs-lisp-lexer (region-beginning) (region-end) 5)` to get all token with its position. Then, you can analyze each token and see whether a token is a keyword argument and if so, check if the value is available for it and if the value is, insert a newline after that value.

Of course, you won't have to throw away old code. It is still useful for Lisp that are not supported by Semantic. If you are interested in this, I suggest you should create a separate `lispy-code-formatter` package, so people can have a choice to use the formatting feature separately and if `lispy` is installed, then the package is installed by default. I will also aid you to develop formatting for specific Lisp functions for this package, in the fashion showed in `lispy-format-let` above (for example, `lispy-format-if`, `lispy-format-while`, `lispy-format-unwind-protedct`....).

**Comment by abo-abo** [comment]
> before the let keyword and run lispy-oneline, it becomes:

That's the expected and desired behavior.

> Of course, you won't have to throw away old code. It is still useful for Lisp that are not supported by Semantic. If you are interested in this, I suggest you should create a separate lispy-code-formatter package, so people can have a choice to use the formatting feature separately and if lispy is installed, then the package is installed by default. I will also aid you to develop formatting for specific Lisp functions for this package, in the fashion showed in lispy-format-let above (for example, lispy-format-if, lispy-format-while, lispy-format-unwind-protedct....).

You haven't made a (convincing) case that "old code" is worse than semantic in any way.  Currently,
I think it's a lot better than semantic: if you look at `lispy--read` and `lispy--insert`, they
preserve the original code whitespace. No way can semantic do that.

And the case of semantic over plain regexps just doesn't make any sense for any LISP dialect.
LISP is so well structured that both methods work in the same way, except semantic adds overhead.

If you want to make a convincing case, just list test cases in an ERT format:

- starting code and point position
- (optional) command
- ending code and point position

If I see that the current code can't handle the test cases reasonably, I'll add some extra support
from semantic or whatever.

**Comment by tuhdo** [comment]
> That's the expected and desired behavior.

Then, it will only work at small scale. Currently, `lispy` cannot create multiline of this after you run `lispy-oneline`:

```elisp
(link :tag "test "
      :button-prefix ""
      :button-suffix ""
      :button-face
      :format "%[%t\n%]"
      :help-echo ""
      :action nil
      nil)
```

Currently, `lispy-multiline` does not work properly with `if`:

```elisp
(if t "hi" "nope" "nope" "nope" "nope" "nope" "nope")
```

After you execute `lispy-multiline`, the `t` is on a line of its own. And how do you handle `cond`? How do you handle `defstruct` and `defclass`? And then, how do you handle function with variable number of parameters? i.e. `propertize` where you can have a variable number of pairs.

> You haven't made a (convincing) case that "old code" is worse than semantic in any way. Currently, I think it's a lot better than semantic: if you look at lispy--read and lispy--insert, they
preserve the original code whitespace. No way can semantic do that.

With a bit of extra processing, we could do that. 

> And the case of semantic over plain regexps just doesn't make any sense for any LISP dialect.
LISP is so well structured that both methods work in the same way, except semantic adds overhead.

Lisp is already an AST, but that doesn't mean we have to use regexp to walk it manually. Semantic can already do that and give us nicely processed tags, why not reuse instead? Instead of collecting opening parentheses manually, you can simply use `semantic-emacs-lisp-lexer` on a region and collect all element with `open-paren`. There's no overhead of Semantic if you only process a defun or two. Semantic can parse a 10k lines C/C++ file okay.

**Comment by tuhdo** [comment]
Here are some examples of a more complex `if` that `lispy` cannot break into multiline after turning into oneline:

```elisp
(if add-shortcut
              (srefactor-ui--show-digit-shortcut (mapcar 'srefactor-ui--make-default-menu-element
                                                         commands))
            (mapcar 'srefactor-ui--make-default-menu-element
                    commands))
```

In this simple `if`, multiline doesnt work:

```elisp
(if beg beg (point-min))
```

Here is the demo `lispy-format-let` of mine. As you see, it walks through the sexps of the same level as the `let` keyword, not deeper and destroy everything inside:

![lispy-format-let](https://cloud.githubusercontent.com/assets/4818719/6980458/323982da-da1c-11e4-819c-d763152a3c95.gif)


But what we can do beyond this oneline and multiline is automatic code reformating (format != indentation).

**Comment by abo-abo** [comment]
> Currently, lispy cannot create multiline of this after you run lispy-oneline:

This is a bug that will be resolved at some point.

> Currently, lispy-multiline does not work properly with if:

This is also a bug that will be resolved at some point.

`oneline`/`multiline` currently are crude tools to quickly generate a transformation.  Lispy has
many tools to refine the output of `oneline`/`multiline` to make it look like you want.  `multiline`
can be made smarter, but it doesn't have a nice work-to-payoff ratio to bother with it.  It can't be
perfect, since `oneline` destroys information, and `oneline`-`multiline` can't be made into 1-to-1
mapping.

> Semantic can already do that and give us nicely processed tags, why not reuse instead?

Semantic is a hugely complex system with a lot of (undesired) dependencies.  If I'm going to depend
on a hugely complex system, it had better pay off like hell.  Which semantic does when it comes to
parsing source directories. But it doesn't when it comes to parsing a single function.

> Semantic can parse a 10k lines C/C++ file okay.

It's not OK even for LISP. When I turn off `semantic-mode` in `lispy` (6k lines), I get a
perceptible speedup in all navigation commands.

But if you want to contribute some cool functions in lispy-semantic.el, be my guest:)

**Comment by abo-abo** [comment]
> Here are some examples of a more complex if that lispy cannot break into multiline after turning into oneline:

Easily fixed with <kbd>f C-m f C-m</kbd>. This is why I don't have incentive to improve <kbd>M</kbd>
by much.  It's so easy to fix its result.

**Comment by abo-abo** [comment]
> Here is the demo lispy-format-let of mine. As you see, it walks through the sexps of the same level as the let keyword, not deeper and destroy everything inside:

<kbd>M</kbd> gives exactly the same result.

**Comment by tuhdo** [comment]
> M gives exactly the same result.

But this is about `O`. This is the result of `lispy-oneline`:

```elisp
(let ((a 1)) (message "%d" a) (if t "hi" "nope" "nope" "nope" "nope" "nope" "nope"))
```

It destroys the inner `if` form.

**Comment by abo-abo** [comment]
> It destroys the inner if form.

It's *supposed* to do that. Look at lispy-test.el: <kbd>O</kbd> is designed to bring code onto a
single line to make the tests look nicer.

It's not supposed to be "smart", it's supposed to be universal and predictable, which it is.

**Comment by tuhdo** [comment]
> It's not OK even for LISP. When I turn off semantic-mode in lispy (6k lines), I get a
perceptible speedup in all navigation commands.

For me, `helm.el` is 5k lines and I couldn't notice anything. `helm-semantic` took 1 second to display. Probably your Semantic setup has some extra things enable?

> It's not supposed to be "smart", it's supposed to be universal and predictable, which it is.

My example just to show the benefit of using an actual AST. We can have both smart (know which sexp is at which level) and predictable (only make sexp at the same level one line). With Semantic, it's possible to do 1 to 1 mapping between oneline and multiline since we operate at semantic tag level, not text level.

> But if you want to contribute some cool functions in lispy-semantic.el, be my guest:)

Sure,  I can create my own Semantic formatter and try to integrate with Lispy, i.e. replace some stock Lispy functions when user enables this module. But I want it to be a separate package, so people can still use it if they use other packages. The reason I told you to do it is because I don't want to create yet another package for manipulating parentheses and competing with others. 

Maybe I will integrate this into `srefactor`, since it transforms code in various ways and hopefully can complement `lispy` rather than compete.

**Comment by abo-abo** [comment]
> Probably your Semantic setup has some extra things enable

No it's just the idle parser generally slowing down Emacs.

> My example just to show the benefit of using an actual AST.

You can get an actual AST for Elisp with just `read`. No Semantic required.

`lispy` already has >100 commands, and all but the most universal ones don't see much use.  I think
there's more value in writing composable commands rather than situational ones.
For instance, any bad case of <kbd>M</kbd> can be quickly fixed up with <kbd>f</kbd> and <kbd>C-m</kbd>.

Also look at the implementation of <kbd>xu</kbd> and <kbd>xb</kbd>: it's a quite beautiful use of
`iedit`. I want `lispy` commands to be just as universal and unaware of the context like `iedit`.
Then they can also be re-used in a lot of great ways.

**Comment by tuhdo** [comment]
> No it's just the idle parser generally slowing down Emacs.

It only parses in idle time. When you actively type, it won't interfere and it only parses edited regions.

> You can get an actual AST for Elisp with just read. No Semantic required.

But it lacks extra information, such as tag class and position of each tag and Semantic utility APIs to process the tag. As you see in my example function, I use `semantic-tag-start` and `semantic-tag-end` instead of wrapping `car`,`caadr`, `nth`... functions. And `semantic-parser-region` returns tags at a particular rather than perform bread first search and collect your own.

Other Lispy commands are very useful and not context independent. But ones that depend on context, we could do better.

**Comment by abo-abo** [comment]
> But ones that depend on context, we could do better.

Alright, I'll wait to see what you produce. I hope it's something awesome!

**Comment by tuhdo** [comment]
With a little modification, now I can convert back and forth between `oneline` and `multiline`:

```elisp
(defun lispy-one-or-multi-lines (let-tag format-type)
  (let* ((tag-start (semantic-tag-start let-tag))
         (tag-end (semantic-tag-end let-tag))
         (tags (semantic-parse-region tag-start tag-end nil 1))
         (first-tag-pos (semantic-tag-start (car tags)))
         (last-tag-pos (1- tag-end))
         (tmp-buf (generate-new-buffer "let-buf"))
         formatted-content
         tag-str)
    (save-excursion
      (dolist (tag tags)
        (message "tag is %s" tag)
        (setq tag-str (buffer-substring-no-properties (semantic-tag-start tag)
                                                      (semantic-tag-end tag)))
        (with-current-buffer tmp-buf
          (insert tag-str)
          (cond
           ((eq format-type 'one-line)
            (insert " "))
           ((eq format-type 'multi-line)
            (insert "\n"))
           )))
      (kill-region first-tag-pos last-tag-pos)
      (goto-char first-tag-pos)
      (insert (with-current-buffer tmp-buf
                (buffer-substring-no-properties (point-min)
                                                (point-max))))
      (indent-region first-tag-pos last-tag-pos)
      (delete-horizontal-space))))
```

Now, I have a similar example as in this issue: https://github.com/abo-abo/lispy/issues/35

```elisp
(= (+ 2 3)
   (+ 3 4)
   (if t
       (+ 5 6)
     (+ 7 8))
   )
```

It can convert  back and forth between the above multiline and this oneline depend on the `formate-type` symbol you supplied, reliably:

```elisp
(= (+ 2 3) (+ 3 4) (if t
                       (+ 5 6)
                     (+ 7 8)))
```

Replace `=` with whatever function of your choice.

**Comment by tuhdo** [comment]
Forgot to incluide the command if you want to try it out:

```elisp
(lispy-one-or-multi-lines (car (semantic-parse-region (region-beginning) (region-end) nil 0)) 'multi-line)
```

Replace `'multi-line` with `'one-line` to try both, and remember to mark the sexp you want to transform.

**Comment by abo-abo** [comment]
> Replace 'multi-line with 'one-line to try both, and remember to mark the sexp you want to transform.

OK, I tried it. It doesn't work unless `semantic-mode` is on, which is a huge disadvantage.

Also, this isn't a proper form:

```el
(= (+ 2 3)
   (+ 3 4)
   (if t
       (+ 5 6)
     (+ 7 8))
   )
```

This is the proper form:

```el
(= (+ 2 3)
   (+ 3 4)
   (if t
       (+ 5 6)
     (+ 7 8)))
```

And this is actually what <kbd>M</kbd> produces.

**Comment by tuhdo** [comment]
> OK, I tried it. It doesn't work unless semantic-mode is on, which is a huge disadvantage.

Not really. I don't know but idle parser shouldn't run when you don't have new code inserted.

> And this is actually what M produces.

But the `if` form is not correct anymore:

```elisp
(progn (+ 2 3)
       (+ 3 4)
       (if t (+ 5 6)
         (+ 7 8)))
```

And my current function is still experimental.

**Comment by tuhdo** [comment]
Do you use `company`? If so, try removing `company-semantic` backend and you won't get idle parser get in the way when company starts gathering completion candidates for automatic popup. It should be fine to remove `company-semantic` since you already have a REPL with any Lisp to get completion candidates from (except the ones not loaded but then when you write Lisp code you usually load code as you write anyway).

**Comment by abo-abo** [comment]
> If so, try removing company-semantic backend

I'm using `company`, and I've had `company-semantic` off ages ago.
