### ISSUE TITLE
lispy-tab ... please ignore

### ISSUE THREAD

**Issue by p1llule** [abo-abo/lispy#581]
Hello please ignore this.

I had TAB mapped to lispy-tab and it was a cause of problems . 
lispy-tab must not be used as a generic command, i get it.
Or maybe use a modified version of special-lispy-tab with indent-for-tab-command in place of self-insert-command.

Sorry for the noise.

**Comment by pierre-rouleau** [comment]
@p1llule , do you have the ability to close this ticket?
