### ISSUE TITLE
Support for cider-debug via `xe'

### ISSUE THREAD

**Issue by bcarrell** [abo-abo/lispy#60]
It'd be awesome if I could instrument Clojure functions using Cider's _edebug-like_ interface.  The main entry function is `cider-debug-defun-at-point`, which instruments the function under point, so I think it's mostly a matter of dispatching to a mode-specific debug function similar to `lispy-eval`.

The problem is that Lispy's Clojure evaluation code doesn't support instrumented functions in the same way Cider does.  To be more clear, `cider-eval-last-sexp` will work with functions that have been instrumented, but `lispy-eval` won't.

I can investigate and work up a PR if you want if you'd rather work on other tasks.

**Comment by abo-abo** [comment]
Actually I've already committed this functionality by accident just 20 minutes ago.
But it won't work until my [PR to CIDER](https://github.com/clojure-emacs/cider/pull/1055) is merged.

**Comment by bcarrell** [comment]
Ah ha!  So you have.  Awesome!
