### ISSUE TITLE
Conflict with smartparens in dealing with quotes

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#62]
Because lispy loads paredit, it also changes the way I wish to deal with double quotes (specifically, whether or not to escape them)

I want `"|"` to become `""|` after pressing `"`. I get `"\"|\""`. How can I disable this?

**Comment by abo-abo** [comment]
> Because lispy loads paredit

It certainly doesn't. I'm guessing that you're using this theme (the default one):

    (lispy-set-key-theme '(special lispy c-digits))

You probably want this theme:

    (lispy-set-key-theme '(special paredit c-digits))

Paredit theme has the quote behavior that you want.

**Comment by sooheon** [comment]
Thank you. Where can I read more about these themes and their behaviour? ctrl-f in the README isn't giving me anything (not sure if I can completely understand the source code).

**Comment by abo-abo** [comment]
You can read more about themes in [this post](http://oremacs.com/2015/04/02/lispy-paredit-emulation/). Basically, they just build `lispy-mode-map` in large chunks. You can further refine it with e.g.:

    (define-key lispy-mode-map "\"" 'my-quote)
