### ISSUE TITLE
Conflicts with macrostep

### ISSUE THREAD

**Issue by andyque** [abo-abo/lispy#63]
I have installed the https://github.com/joddie/macrostep for interactively stepping through the expansion of macros in Emacs Lisp source code. 

But when in *macrostep* mode, the default key binding "c", "e" and "q" will be conflict with lispy.

And I know lispy has a "xf" command for expand macro, but it lacks the ability to collapse the macro.

If lispy could provide the ability of macrostep,it would be great.

I like lispy very much. Thanks very much for providing this awesome package.

**Comment by abo-abo** [comment]
I'll try to fix this later.
Meanwhile, to collapse a macro after <kbd>xf</kbd>, you can simply call `undo`. That's what I always do.

**Comment by abo-abo** [comment]
Let me know if it actually works. I just did a small test.

**Comment by andyque** [comment]
@abo-abo  How could I use the code?
The melpa repository doesn't point to the latest commit of this repository.
Should I download this package manually and test it?

**Comment by abo-abo** [comment]
I just checked and it's in MELPA. To use the work-around just customize the `lispy-compat` variable.
