### ISSUE TITLE
How to input raw "[" and "]" in a lispy enabled lisp buffer

### ISSUE THREAD

**Issue by andyque** [abo-abo/lispy#64]
I want to construct a vector in elisp, but when I input "[" and "]", it will call "lispy-backward" and "lispy-forward". 

I don't know how to input the actual character for "]" and "[".

BTW, I have read the docs many times, but still can't find it. 

Am I missing something here?

thanks.

**Comment by abo-abo** [comment]
Method 1: <kbd>C-q [</kbd> or <kbd>C-q ]</kbd>.
Method 2 (I like this one more): <kbd>}</kbd> will insert `[]`. Then I delete the one that I don't want,
but usually I want both of them. [short doc](http://oremacs.com/lispy/#lispy-brackets)

**Comment by andyque** [comment]
@abo-abo 
Thanks, it is working. 
When I input a "{", it will insert "{}" which is nice. But if I hit delete, I guess it will only delete the "{}" pair, but it also delete the previous s-expression before it.

eg.
(foo bar)
{}| (if I hit DELETE here, the (foo bar) will also be deleted. weired..

How to solve this?

**Comment by abo-abo** [comment]
Which mode are you using? This error doesn't occur in `clojure-mode` since `{}` is a valid list there.
In Elisp, `{}` isn't a valid list, e.g. you can name a symbol `{foo}`. Hence the error.

**Comment by andyque** [comment]
@abo-abo 
I'm using emacs-lisp-mode.

**Comment by abo-abo** [comment]
So what use do you have for `{}` in `emacs-lisp-mode`?

**Comment by andyque** [comment]
I don't use it, but just for testing purpose..
It seems the "{}" pair is transparent in emacs-lisp-mode.
Anyway I think it maybe a reasonable default.
The "{}" is invalid in elisp.

**Comment by andyque** [comment]
Thanks for the clarification.

**Comment by abo-abo** [comment]
OK, I can `lispy-left` and `lispy-right` buffer-local so that this error doesn't surface.
I'm just having a small problem with some test failing as a result.

**Comment by abo-abo** [comment]
Can't fix it right now. It seems that there's a bug in `setq-mode-local` that makes it useless for non-file buffers.

**Comment by Wilfred** [comment]
For anyone looking to disable this, the naive solution doesn't work:

```lisp
(define-key lispy-mode-map (kbd "[") nil)
(define-key lispy-mode-map (kbd "]") nil)
```

The correct solution is to use the lispy map:

```lisp
(define-key lispy-mode-map-lispy (kbd "[") nil)
(define-key lispy-mode-map-lispy (kbd "]") nil)
```

**Comment by bhurlow** [comment]
thanks for this
