### ISSUE TITLE
Proper workflow for appending non-sexp at start of line?

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#67]
Given this:
```
(defn foo [a]
  (let [acc 0
        bar (inc a)]
   baz)
```
Imagine I want to change `bar`. If I delete bar and have my cursor just in front of the opening paren (this state is very easy to get to in evil-mode with `cw`):
```
(defn foo [a]
  (let [acc 0
        |(inc a)]
   baz)
```
I can't type anything without moving the curser with `left arrow` because `lispy-special` takes precedence. The strange thing is that I seem to remember that in a previous version `lispy-space` accounted for this, so that `SPC` put the space between cursor and opening paren. It doesn't do this any more. Was I hallucinating this?

**Comment by bcarrell** [comment]
Let me take a guess on this one:  are you using `aggressive-indent-mode`?

**Comment by abo-abo** [comment]
> Imagine I want to change bar

You can delete `bar` with <kbd>Hj</kbd>.

> I can't type anything without moving the curser with left arrow
> because lispy-special takes precedence. The strange thing is that I
> seem to remember that in a previous version lispy-space accounted
> for this, so that SPC put the space between cursor and opening
> paren. It doesn't do this any more. Was I hallucinating this?

- <kbd>SPC</kbd> will shift `(inc a)` to the right.
- <kbd>o SPC</kbd> will get you out of special by inserting a space after cursor.
- The plain <kbd>SPC</kbd> only gets you out of special in case when you're jammed between two parens, which isn't the case here.

**Comment by abo-abo** [comment]
> Let me take a guess on this one: are you using aggressive-indent-mode?

I don't know if `aggressive-indent` could interfere. In any case, `lispy` already does 95% of the electric indenting, and in other cases there's <kbd>i</kbd>.

**Comment by bcarrell** [comment]
If he has `aggressive-indent-mode` on, `lispy-space` will do effectively nothing in this particular case because the code will be reindented to where the point is.  Without `aggressive-indent-mode`, the form would move one space with `lispy-space`.  Since he mentioned remembering previous behavior, I was wondering if he's since added `aggressive-indent`.

**Comment by sooheon** [comment]
I do have `aggressive-indent-mode`, but I toggled it off to test lispy default behaviour, and my experience was that SPC before opening paren moved both cursor and the sexp, keeping me in `special`. `o SPC` was the behaviour I was looking for (should `SPC` also function as `o SPC` in this case, as well as when jammed between parens?), but as @bcarrell observed it doesn't work with `aggressive-indent`. OTOH `Hj` is perfect in that it doesn't seem to trigger `aggressive-indent-mode`'s electric indent even at the start of line. I wonder if there is a way to advise evil deletion or change commands to do the same, but I guess that's not a discussion to be had here.

Just curious, @bcarrell, do you use aggressive indent? Is there a way to make it work or are aggressive-indent and let/loop bindings oil and water?

**Comment by abo-abo** [comment]
> should SPC also function as o SPC in this case, as well as when jammed between parens?

Probably not. The way it works now is just a simple self-insert, as if `lispy-mode` wasn't on. That's a reasonable and expected action.

**Comment by sooheon** [comment]
I'm still curious to discuss aggressive indent and other lispy behaviour, but the issue itself has been answered. Lispy is a beautiful thing, by the way, I'm really enjoying it. Just wish it was more mnemonically consistent with vi, but I know that was never intended (may get around to customising mappings when I'm comfortable).
