### ISSUE TITLE
Clojure `lispy-special-multiline` error: let*: Invalid read syntax: "#"

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#69]
Possibly along the lines of #55 
Happens with anonymous fn, hash map, regex special forms.

**Comment by abo-abo** [comment]
Please add some sample code for which it fails. It normally shouldn't, I've tested most Clojure forms.

**Comment by sooheon** [comment]
It seems it fails for every instance of `#` for me.

Regex:
```
(let [sentences (re-seq #"[.!?]" text)
      words (re-seq #"\W+" text)
      syllables (re-seq #"(?i)[aeiou]+" text)]
  (+ (* 0.39 (/ (count words) (count sentences)))
     (* 11.8 (/ (count syllables) (count words)))
     -15.59))
```

Lambda:
```
(defn sum
  ([a b] (+ a b))
  ([a] #(+ a %)))
```

Hash-map:
```
(def x #{:a 1 :b 2 :c 3})
```

**Comment by bcarrell** [comment]
Can confirm; happening for me too.

**Comment by abo-abo** [comment]
OK, I see it.

How about <kbd>T</kbd> (`special-lispy-alt-multiline`)? It's intended to replace <kbd>M</kbd> at some point anyway.

**Comment by bcarrell** [comment]
> No change.

Nothing happens.

**Comment by abo-abo** [comment]
> Nothing happens.

Try a bigger expression, toggle <kbd>OT</kbd>, it should work. Also look at `lispy-multiline-threshold`, try to set it to nil.

**Comment by bcarrell** [comment]
You're right -- larger expressions work using default settings and adjusting the threshold works for all.

**Comment by bcarrell** [comment]
Any reason why we can't just replace <kbd>M</kbd> with `alt-multiline`?  I've used it since you implemented it and it seems straight up better, but I haven't looked at the implementations.

**Comment by abo-abo** [comment]
> Any reason why we can't just replace M with alt-multiline? I've used it since you implemented it and it seems straight up better, but I haven't looked at the implementations.

I wanted to replace it once it's stable enough. If you haven't encountered any bugs with it, I can replace it right now.

**Comment by bcarrell** [comment]
I haven't encountered issues with it yet but I can understand if you want to wait on it.

**Comment by sooheon** [comment]
`lispy-multiline` on snippet from lispy demo 4:
```
(defn blue [red]
  (BigInteger/valueOf (/ (+ 1 (* 2 red)
                            (Math/sqrt (inc (* 8 red red))))
                         2)))
```
`lispy-alt-multiline`:
```
(defn
  blue
  [red]
  (BigInteger/valueOf
   (/
    (+
     1
     (* 2 red)
     (Math/sqrt (inc (* 8 red red))))
    2)))
```
The first is much closer to how I would manually split lines. (It would be even more consistent if the `(* 2 red)` sexp was on a newline, imo) I can see the structure of equal depth arguments to each function call easily. Alt-multiline seems much less useful, requiring multiple join-lines after each call. Would you share your rationale behind changing to this behaviour?

**Comment by sooheon** [comment]
Strange, certain `if` expressions are split incorrectly:
```
(if (= l w) nil (let [long (max l w)
                        short (min l w)]))
```
```
(if
      (= l w)
    nil
    (let [long (max l w)
          short (min l w)]))
```

**Comment by abo-abo** [comment]
> The first is much closer to how I would manually split lines.

This can eventually be adjusted.

> (It would be even more consistent if the (* 2 red) sexp was on a
> newline, imo)

Set `lispy-multiline-threshold` to nil to get full consistency. If it's an integer, the expressions that are shorter than this don't get multi-lined.

> I can see the structure of equal depth arguments to each function
> call easily. Alt-multiline seems much less useful, requiring
> multiple join-lines after each call. Would you share your rationale
> behind changing to this behaviour?

Here's what I get with the last commit:

```clojure
(defn blue [red]
  (BigInteger/valueOf
   (/
    (+
     1
     (* 2 red)
     (Math/sqrt (inc (* 8 red red))))
    2)))
```

And here's the config:

```elisp
(setq-local lispy--multiline-take-3 '(defn))
```

Here's what I get after `(setq lispy-multiline-threshold nil)`:

```clojure
(defn blue [red]
  (BigInteger/valueOf
   (/
    (+
     1
     (*
      2
      red)
     (Math/sqrt
      (inc
       (*
        8
        red
        red))))
    2)))
```

The configuration for `lispy--multiline-take-3` just needs to be extended a bit for Clojure. Then it will give a result that needs almost no further editing.  The old `lispy-multiline` isn't really customizable and it almost always needs to be adjusted a bit. But the function is still there, you can re-bind it if you wish.

**Comment by sooheon** [comment]
Ah I see. Would you be open to PRs in populating the lists for clojure?

**Comment by abo-abo** [comment]
> Ah I see. Would you be open to PRs in populating the lists for clojure?

Sure.

**Comment by abo-abo** [comment]
I think this can be closed, since <kbd>M</kbd> doesn't result in an error any more.
