### ISSUE TITLE
inserting [ and ]

### ISSUE THREAD

**Issue by jkitchin** [abo-abo/lispy#72]
How do you type a [ or ] in lispy? I do a lot of org-mode programming to make links and often need to put these in strings. But when I press the keys, the cursor moves to the boundaries instead of inserting the character I want.

**Comment by abo-abo** [comment]
To insert `[]`, press <kbd>}</kbd>. It's a bit symmetrical to <kbd>{</kbd>, which inserts `{}`.

I find it easier to navigate with `[` and `]` instead of <kbd>C-M-p</kbd> and <kbd>C-M-n</kbd>.

**Comment by jkitchin** [comment]
Thanks for the quick reply! That was the only thing driving me crazy about lispy!

**Comment by aaronjensen** [comment]
I was going to open the same issue. I was trying to type `(kbd "M-]")` and having a heck of a time. Even after finding this I still couldn't type a single `]` 😕

**Comment by abo-abo** [comment]
@aaronjensen

> I still couldn't type a single ]

I think navigation and editing >> insertion, so not being able to input `]` is an OK trade off to having easier navigation.

If you don't agree:

    (define-key lispy-mode-map-lispy "[" nil)
    (define-key lispy-mode-map-lispy "]" nil)

**Comment by aaronjensen** [comment]
Ok, but how would you typically insert a ]? Turn off lispy-mode?

**Comment by abo-abo** [comment]
Of course not. `C-q ]` is the standard Emacs method of inserting a key that's bound to something.

**Comment by aaronjensen** [comment]
Ah, thanks!
