### ISSUE TITLE
`lispy-backward-delete` with and without paredit key theme

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#75]
Given:

```
(|)
```

Calling `lispy-backward-delete` gives me:

```
 |
```

Notably, it leaves a space before the cursor and deletes the surrounding parens.

**Comment by abo-abo** [comment]
> Without `(lispy-set-key-theme '(special c-digits))), the same thing leaves a space before the cursor:

With this setting, <kbd>DEL</kbd> probably calls `backward-delete-char-untabify` - the default command of `emacs-lisp-mode`.  Which results in:

    |)

Not using either `lispy` or `paredit` in the `lispy-set-key-theme` call results in <kbd>DEL</kbd> not being bound in `lispy-mode`.  So whatever you're getting is the behavior of some other package. Check which command it is with <kbd>C-h k DEL</kbd>.

**Comment by sooheon** [comment]
Hm, I've completely fucked up the question, I've rephrased it to be clear.

**Comment by abo-abo** [comment]
OK, got it:)
