### ISSUE TITLE
Move lispy-ace-paren to avy

### ISSUE THREAD

**Issue by tuhdo** [abo-abo/lispy#77]
I think this command is useful even for people who don't use `lispy` and generalize it to `avy-goto-punctuation`, and then you can specialize it for `lispy` as `lispy-ace-paren`.

**Comment by abo-abo** [comment]
`lispy-ace-paren` uses some lispy-specific things, such as `lispy--remember` and `lispy--in-string-or-comment-p`.  That means that either `avy` has to depend on `lispy`, or the other way around. I think the current way is better.
