### ISSUE TITLE
forward-list: Scan error: "Containing expression ends prematurely", 29, 29

### ISSUE THREAD

**Issue by tuhdo** [abo-abo/lispy#78]
`lispy-left` and `lispy-backward` give such error when there's no closing parenthesis. For example:

```elisp
(defun []
```
`[]` is point.

**Comment by abo-abo** [comment]
> lispy-left and lispy-backward give such error when there's no closing parenthesis.

The error comes from `emacs-lisp-mode` on which `lispy` relies. There's nothing that can be done here.  Besides, the only way to get from a paren-balanced buffer to unbalanced is careless use of <kbd>C-w</kbd>.  Even with active region, `lispy` protects buffer if you use e.g. <kbd>j</kbd> and <kbd>&gt;</kbd> and not <kbd>C-f</kbd> and <kbd>M-f</kbd>.

So if this error occurs, you should either `undo` or make the buffer paren-balanced with <kbd>C-w</kbd>.  Requests for catch-all cases or work-arounds should be filed for `emacs-lisp-mode` using `report-emacs-bug`.

> [] is point.

The standard convention for point in `lispy` is `|`. See lispy-test.el.

**Comment by tuhdo** [comment]
I use this on REPL where I type code without closing paren. In SLIME, you can use `M-RET` to automatically close all opening parens. If a paren is automatically close, you won't be able to write multi-line code in the REPL.

At least `backward-up-list` can still go to opening parentheses correctly. Is it possible to make `lispy-left` use it?

**Comment by abo-abo** [comment]
> At least backward-up-list can still go to opening parentheses correctly. Is it possible to make lispy-left use it?

It's theoretically possible. But the change isn't straightforward: the tests are failing all over the place if I use `backward-up-list`. I'll try to look at this later.

**Comment by abo-abo** [comment]
> you won't be able to write multi-line code in the REPL.

Just a suggestion: you don't have to use a REPL with lispy. A scratch buffer and <kbd>2e</kbd> is almost equivalent, but a lot more powerful:

- you can save the buffer
- you can search the buffer
- use <kbd>n</kbd> or <kbd>c</kbd> as replacements for arrow keys in a REPL
- the undo context works much better in a buffer
- you can use outlines to obtain a sort of notebook functionality, like `org-mode` or `ipython`

I haven't used a REPL once since lispy got the ability to eval stuff.

**Comment by tuhdo** [comment]
I know. That's what I always do. However, sometimes I'm in the main code buffer, but I want to quickly test some functions without polluting my buffer and or without having to switch to the temporary buffer and back to my code buffer, it's nice to directly switch to the REPL for testing out.

For Emacs Lisp, a REPL is not really needed. What I'm using here is SLIME.

**Comment by abo-abo** [comment]
Thanks, I've finally made a change that doesn't break the tests. Let me know if it works OK.
