### ISSUE TITLE
lispy-bolp takes into account leading spaces and no TABs

### ISSUE THREAD

**Issue by sewkokot** [abo-abo/lispy#80]
The function lispy-bolp takes into account only leading spaces, but it can be spaces and tabs together.
This function behaviour gives different results for example in lispy-delete when point is at the comment-start. Sometimest the comment-start is indented with only spaces and elsewhere spaces and tabs. Then C-d behaves differently. 

Do you thing changing the existing line 
(skip-chars-backward " ") 
with
(skip-chars-backward " \t")
in defun lispy-bolp is reasonable?

**Comment by abo-abo** [comment]
> in defun lispy-bolp is reasonable?

Thanks. It's a reasonable change. I prefer to never have tabs in my source code.
I'd like lispy to work with tabs if possible, but it's not a priority.

With this setting, tabs never come up:

    (setq indent-tabs-mode nil)

**Comment by sewkokot** [comment]
Thank you for very fast action :) In fact I don't want TABs neither, so now I have this setting in my init.el
