### ISSUE TITLE
how to delete a pair of parens other than pressing "m i r"

### ISSUE THREAD

**Issue by sewkokot** [abo-abo/lispy#81]
Assume I have: 
|(beg)
And I want to delete perenthesis () and get only:
beg
I found that it is possible with pressing "m i r". Is there an easier way to do it?
Usage case:
First I want to write local args in let structure: 
(let ((beg ...)   ...)
then I decide to have
(let (beg) ...) 
and set beg variable later in the body.

**Comment by abo-abo** [comment]
You can do it with `lispy-splice`. Bound to <kbd>/</kbd> in special theme (on by default), and to <kbd>M-s</kbd> in paredit theme (off by default).

**Comment by abo-abo** [comment]
If you don't want the point to move afterwards, use <kbd>m/</kbd>, but usually the point moving is beneficial.

**Comment by sewkokot** [comment]
Thank you again. You can add it to the list of keybindings and functions http://oremacs.com/lispy/
I couldn't find it there.

**Comment by abo-abo** [comment]
OK, [added](http://oremacs.com/lispy/#lispy-splice).

**Comment by sewkokot** [comment]
I have another similar question. I have:
|(kbd "M-p") 
and I want to get just the string "M-p" (because e.g. bind-key macro have it inside).
So far I have reached the goal with the following sequence: m i i r m
Can I do it faster?

**Comment by abo-abo** [comment]
> Can I do it faster?

<kbd>2mrm</kbd> is one character less. Usually <kbd>2mr</kbd> is good, since you want to manipulate (wrap, move ...) what you just raised.

**Comment by sewkokot** [comment]
Thank you!!!
