### ISSUE TITLE
Error when using g or G with Helm

### ISSUE THREAD

**Issue by tuhdo** [abo-abo/lispy#82]
The error:

> lispy--action-jump: Unexpected tag: (#("tuhdo/post-init-auto-highlight-symbol                                packages.el" 0 37 (face font-lock-function-name-face)) #("tuhdo/post-init-auto-highlight-symbol" 0 37 (face font-lock-function-name-face)) "/home/hoangtu/.emacs.d/private/tuhdo/packages.el" [4483 5664]) [2 times]

To reproduce:

- Set `lispy-completion-method` to `'helm`
- `g` or `G` to jump to any tag.

**Comment by abo-abo** [comment]
Thanks.
