### ISSUE TITLE
lispy-kill appears to be too eager when sexp spans multiple lines

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#85]
```
(defun lispy-kill-test ()
  |(foo
   bar baz)
  (1 2 3)
  (a b c))
```
Calling `lispy-kill` results in:
```
(defun lispy-kill-test ()
  |)
```
One expects that it would kill the sexp containing foo bar baz, but why the other sexps which follow? If foo bar baz are on one line, the behaviour is as expected, so semantically the command acts inconsistently.

**Comment by tuhdo** [comment]
You kill current sexp at point with `C-,`. You kill everything in the same scope as current sexp with `C-k`, since stock `C-k` would delete a line and make your code broken.

**Comment by sooheon** [comment]
Ah I should have mentioned that I have `(lispy-set-key-theme '(special paredit c-digits))`. Still, I think the same command should not behave differently depending on indentation of the same sexps, no? To be clear, when the above is 
```
(defun lispy-kill-test ()
  |(foo bar baz)
  (1 2 3)
  (a b c))
```
it results in 
```
(defun lispy-kill-test ()
  |
  (1 2 3)
  (a b c))
```
Which is what I would expect for both cases.

**Comment by tuhdo** [comment]
It's true. This is a bug. I thought that was a feature lol

**Comment by abo-abo** [comment]
Thanks.
