### ISSUE TITLE
special-lispy-ace-symbol-replace sometimes replaces wrong symbol

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#89]
Paste the following into a 80 char wide buffer: 
```
(take 3 (map (fn [pair] (* (first pair) (second pair))) (partition 2 1 (filter odd? (iterate inc 0)))))
```

`hb` in special will replace `map`, not `3` as expected.

Guess it has something to do with `lispy-avy-style-symbol` being `pre` and shifting over text?

**Comment by abo-abo** [comment]
Thanks. The problem was the symbol length 1.
