### ISSUE TITLE
Swiper module not found

### ISSUE THREAD

**Issue by Rameshv** [abo-abo/lispy#90]
Hi when installing the lispy i am getting this error

```
http://melpa.org/packages/swiper-20150709.919.tar: Not found
```
Please look into it

**Comment by abo-abo** [comment]
This is most likely a MELPA hiccup. I've experienced it for other packages at times. An Emacs restart + `package-list-packages` should usually work.

**Comment by abo-abo** [comment]
Hopefully the issue went away. Reopen if not so.
