### ISSUE TITLE
`lispy-teleport` only teleports within top-level form

### ISSUE THREAD

**Issue by Peeja** [abo-abo/lispy#91]
I don't think this is intentional; at least it's not what the [screencast](https://youtu.be/BverGxP41cE?t=23m20s) demonstrates.

![scratch](https://cloud.githubusercontent.com/assets/2407/8652689/05eeb962-294e-11e5-9461-c7e21a85ea09.png)

Here, I have two top-level forms. I'd like to teleport the first one into the the second one's `baz` form. I put point before the first paren and press `t`.

![scratch -1](https://cloud.githubusercontent.com/assets/2407/8652697/0fd2fb78-294e-11e5-9770-9c2d74f83f50.png)

`lispy-ace-paren` only gives me options within that same top-level form, which means I can't actually move it anywhere. Now let's try it with the `(bar)` form.

![scratch -2](https://cloud.githubusercontent.com/assets/2407/8652738/41d361f8-294e-11e5-88af-3abc75b1e653.png)

I get the same options: anything within the top-level form I'm currently in.

Is this a bug or has the behavior changed since the screencast?

**Comment by abo-abo** [comment]
> Is this a bug or has the behavior changed since the screencast?

The behavior has changed for purposes of being reproducible. If all top-level forms were to be allowed, the letter sequence to do the same thing would change each time you scroll your buffer.  I didn't like that, since it makes it harder to explain how to use the command, and also harder to test it.

To work around this, you can move the thing to be teleported into the form where you want it.  For example, starting with:

    (defun foobar ()
      (func-1)
      (func-2))
    
    (progn
      |(func-3)
      (func-4))

You could do <kbd>ohokt</kbd>.

I could bring back the old behavior at <kbd>2t</kbd>, if you like.

**Comment by Peeja** [comment]
Ah, that makes sense. I think it would be nice to have a command for it; my use case here was to inline a `defun` I had just <kbd>xl</kbd>'ed into a `lambda`, which seems like a common case. Unless I'm missing a better way to do it?

Are those <kbd>o</kbd> commands documented somewhere? I don't quite have a grasp on what all of them do. Would it be appropriate to put this on <kbd>ot</kbd> instead of <kbd>2t</kbd>?

**Comment by abo-abo** [comment]
> my use case here was to inline a defun I had just xl'ed into a lambda, which seems like a common case. Unless I'm missing a better way to do it?

Can you describe in more detail? With a code example, before+after the desired command.

> Are those o commands documented somewhere? I don't quite have a
> grasp on what all of them do.

They're documented [here](http://oremacs.com/lispy/#lispy-other-mode).  You can also look at lispy-test.el if you want - each test is named the same as its command.

> Would it be appropriate to put this on ot instead of 2t?

It's possible, but I don't want to put too much stuff on <kbd>o</kbd> - it's a nice prefix for future commands.  Maybe I could put it on <kbd>tt</kbd>: give a small number of candidates after the first <kbd>t</kbd>, and a large number of candidates after the second <kbd>t</kbd>.

**Comment by Peeja** [comment]
> Can you describe in more detail?

Sure. Here's what I was doing:

```elisp
(defun set-up-clojure ()
  (lispy-mode 1)
  (clj-refactor-mode 1)
  (yas-minor-mode 1) ; for adding require/use/import
  (cljr-add-keybindings-with-prefix "C-c C-m"))

(add-hook 'clojure-mode-hook #'set-up-clojure)
```

I wanted to inline this function as a lambda, so I put point before the first `(` and used <kbd>xl</kbd>:

```elisp
(lambda ()
  (lispy-mode 1)
  (clj-refactor-mode 1)
  (yas-minor-mode 1) ; for adding require/use/import
  (cljr-add-keybindings-with-prefix "C-c C-m"))

(add-hook 'clojure-mode-hook #'set-up-clojure)
```

Then I wanted to teleport the lambda into the `add-hook` and remove the `#'set-up-clojure` to get:

```elisp
(add-hook 'clojure-mode-hook (lambda ()
                               (lispy-mode 1)
                               (clj-refactor-mode 1)
                               (yas-minor-mode 1) ; for adding require/use/import
                               (cljr-add-keybindings-with-prefix "C-c C-m")))
```

Was there a better way to accomplish that?

**Comment by abo-abo** [comment]
Shortcut-wise, you could do <kbd>xlojssmj DEL</kbd>. But actually it's preferable to not change the code at all.  Having a single function to setup a major mode, like `set-up-clojure`, means that you can alter it at any point and all new Clojure buffers will use the new rule, and the old ones can too with `revert-buffer`.

On the other hand, it's very hard to modify a lambda once you add it to a hook: you'd have to reset the hook, which isn't bad if you don't have anything else there, but I still think the above approach is better.

**Comment by abo-abo** [comment]
You should now be able to extend the range temporarily with <kbd>tt</kbd>. If you want to do so permanently, you can do it with:

    (setq lispy-teleport-global t)

**Comment by Peeja** [comment]
Ah, thanks for the advice! And thanks for the change!
