### ISSUE TITLE
FileNotFoundException while debugging clojure with `xj`

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#93]
Pressing `xj` to debug as per this [blog post](http://oremacs.com/2015/06/22/debug-clojure/) gives the following error:
```
FileNotFoundException /Users/sooheon/.emacs.d/elpa/lispy-20150724.505/lispy-clojure.clj (No such file or directory)  java.io.FileInputStream.open0 (FileInputStream.java:-2)
```
Navigating to that directory shows that yes, that file does not exist, and yet this repo has lispy-clojure.el. I've nuked the elope directory and reinstalled. What could be causing this?

**Comment by abo-abo** [comment]
Which Clojure code did you use <kbd>xj</kbd> on? It can't work for Java, only for basic functions. For example, this should work:

    |(find-doc "doc")

and bring you to `find-doc` definition in repl.clj with `re-string-or-pattern` equal to `"doc"`.

**Comment by sooheon** [comment]
Tried it on the snippet from the blog post. No amount of reinstalling lispy will get me that lispy-clojure.clj file... don't know what causes it.

**Comment by abo-abo** [comment]
Oh, I finally see it now! lispy-clojure.clj isn't bundled by MELPA, since the extension is .clj and not .el.
I'll try to fix this soon. Meanwhile, you can obtain lispy-clojure.clj from this repository.

**Comment by sooheon** [comment]
Thanks, will use that for now.

**Comment by abo-abo** [comment]
Please try again the MELPA version: it should now properly load lispy-clojure.clj.

**Comment by sooheon** [comment]
Confirmed, it does work. Thank you!
