### ISSUE TITLE
Conflict with clj-refactor (/)

### ISSUE THREAD

**Issue by Peeja** [abo-abo/lispy#94]
[clj-refactor](https://github.com/clojure-emacs/clj-refactor.el) provides a ["magic require"](https://github.com/clojure-emacs/clj-refactor.el/wiki#magic-requires) feature, which automatically adds a require to a namespace when a known common namespace alias is used in the code. It does this by rebinding <kbd>/</kbd> to a function which checks for a missing require. Because it binds <kbd>/</kbd>, Lispy doesn't get to use it for `lispy-splice`.

Luckily, they don't actually have to conflict, since there's no need for <kbd>/</kbd> to trigger clj-refactor's feature when the point is special. We'd just need `special-lispy-splice` to forward to `cljr-slash` (or, generically, whatever <kbd>/</kbd> has been re-bound to) when the point is not special, rather than leave the binding as-is.

Is that a reasonable feature request?

**Comment by abo-abo** [comment]
Try this code, after loading both `lispy` and `cljr-refactor`:

```elisp
(lispy-define-key lispy-mode-map "/" 'lispy-splice
      :inserter 'cljr-slash)
```

I don't see a convenient way to have this on by default though. It should probably go into personal config. Or a dedicated `lispy-enable-cljr-...`.

**Comment by Peeja** [comment]
My thinking was that `special-lispy-splice` could wrap whatever `/` was bound to, instead of just `self-insert`, and that would cover similar conflicts with any package. Does that not actually work?

**Comment by abo-abo** [comment]
I don't know of a good way to implement this.  `lookup-key` isn't an efficient solution, since it would have to go though many keymaps each time, with different results depending on which mode is active.  And un-reading events isn't reliable in Emacs.

**Comment by Peeja** [comment]
Oh, well. Thanks for the workaround!
