### ISSUE TITLE
lispy-eval with ARG 2 with list values display additional line

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#95]
I'm curious if the following is intended behaviour:
```
(sqrt 2)
;; => 1.4142135623730951

(list 1 2 3 4 5)
;; =>
;; (1 2 3 4 5)
```

**Comment by abo-abo** [comment]
Yes, this is intended. If the result is a list, it's likely that it doesn't fit on one line nicely, so a slightly different style is used.

This example looks better with the current style:

```elisp
(list '(1 2 (3 4) (3 4) (3 4) (3 4) (3 4) (3 4) (3 4)))
;; =>
;; ((1
;;   2
;;   (3 4)
;;   (3 4)
;;   (3 4)
;;   (3 4)
;;   (3 4)
;;   (3 4)
;;   (3 4)))
```

With the style that's used for `sqrt` it would look like it's indented too much.

**Comment by sooheon** [comment]
Got it. Thanks.
