### ISSUE TITLE
Lispy changes undo boundaries to single characters

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#96]
This took me a long time to find, but I've finally narrowed it down to lispy. Just loading the mode in the scratch buffer causes undo boundaries to be every single input, rather than 20 or so inputs as in the default. Can anyone else reproduce this?

**Comment by abo-abo** [comment]
Thanks, never noticed it before. Should be better now, please check. Restarting Emacs might be required.

**Comment by sooheon** [comment]
Confirmed fixed. Thanks.
