### ISSUE TITLE
Clojurescript-mode not supported for lispy-eval

### ISSUE THREAD

**Issue by sp3ctum** [abo-abo/lispy#97]
I discovered that when evaluating code in a clojurescript buffer, I get this error:
cond: clojurescript-mode isn't supported currently

I fiddled around and changed `lispy--eval` to include the mode, and the warning has gone away. See below:
```lisp
;;* Utilities: evaluation
(declare-function lispy--eval-clojure "le-clojure")
(defun lispy--eval (e-str &optional add-output)
  "Eval E-STR according to current `major-mode'.
The result is a string.

When ADD-OUTPUT is t, append the output to the result."
  (funcall
   (cond ((memq major-mode lispy-elisp-modes)
          'lispy--eval-elisp)
         ((memq major-mode '(clojure-mode
                             clojurescript-mode
                             nrepl-repl-mode
                             cider-clojure-interaction-mode))
          (require 'le-clojure)
          (lambda (x)
            (lispy--eval-clojure x add-output t)))
         ((eq major-mode 'scheme-mode)
          (require 'le-scheme)
          'lispy--eval-scheme)
         ((eq major-mode 'lisp-mode)
          (require 'le-lisp)
          'lispy--eval-lisp)
         (t (error "%s isn't supported currently" major-mode)))
   e-str))
```

But I'm wondering what the results of such a change could be. Do you think this could be a good idea to include in lispy? Or might there be some problem I can't see?

**Comment by abo-abo** [comment]
> But I'm wondering what the results of such a change could be. Do you think this could be a good idea to include in lispy? Or might there be some problem I can't see?

Yours is a correct change, thanks.

**Comment by sp3ctum** [comment]
Awesome. :)

I'd just like to say lispy has changed the way I view lisp editing. It's
awesome. I use it with evil-mode, and found it relatively easy to pick up
since I already have familiar movement commands to fall back to.

:+1:

2015-08-14 10:31 GMT+03:00 Oleh Krehel <notifications@github.com>:

**Comment by abo-abo** [comment]
> I'd just like to say lispy has changed the way I view lisp editing. It's awesome. I use it with evil-mode, and found it relatively easy to pick up since I already have familiar movement commands to fall back to.

Cool. I'm glad that it's useful. Somehow I'm getting a lot less issue reports for lispy than for my other repositories. That could be either because it's hard to get into, or there are no issues. In any case, don't hesitate to ask if you have more improvement ideas.
